### ISSUE TITLE
[FEATURE] Linear volume controls in internal player

### ISSUE THREAD

**Issue by telelisast** [robvdpol/RaceControl#10]
Currently only way to control volume in internal is either on or off. Linear volume controls with scroll wheel adjustment (VNC like) would be good since currently only way to do  is trough operating system volume mixer.

**Comment by Tralapo** [comment]
Adding to this: saving the volume state to the saved layout?

**Comment by robvdpol** [comment]
Will add both things to the todo list.

**Comment by robvdpol** [comment]
Volume slider added, also saves volume and mute state to layout.
https://github.com/robvdpol/RaceControl/commit/6efd3e8140eb0f8bf9739163a55c61dde420ae85

**Comment by robvdpol** [comment]
Added scrollwheel adjustment.
https://github.com/robvdpol/RaceControl/commit/483b99be7ea8f45448c390aeffb5b9363259a7f0
