### ISSUE TITLE
Window opens to large on 1366x768 screen[BUG]

### ISSUE THREAD

**Issue by Patrik-Hansson** [robvdpol/RaceControl#103]
**Describe the bug**
Starting applicationon low resolution laptop has the main windows larger than the screen. So can't grab the titlebar or make it smaller in size

**To Reproduce**
1. Use old laptop
2. Start application

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/58429567/116712451-27279b00-a9d4-11eb-9bd7-ba5abb1d898a.png)

**Desktop (please complete the following information):**
 - Windows 10 Pro

 - Version (see title bar) <- Can't see titlebar. Downloaded today (2021-04-30)

**Comment by robvdpol** [comment]
I will look into it. However, a little trick you can use to maximize the window is using key combination Windows + Up Arrow.

**Comment by Patrik-Hansson** [comment]
> I will look into it. However, a little trick you can use to maximize the window is using key combination Windows + Up Arrow.

Thanks, that little trick worked fine. 
And thanks for what seems to be a real nice application. The streaming via this app seems much more cpu-friendly than f1 tv's own web player. At least on my very old laptop.

**Comment by robvdpol** [comment]
Fixed in next release.
