### ISSUE TITLE
Question: Features of 1.8.2 on 2.1.0?

### ISSUE THREAD

**Issue by ricky732** [robvdpol/RaceControl#104]
I use your client to run multiple streams on vlc. In version 1.8.2 it was very grat to force live streamings to 720p instead of 1080 to run 5 streams without problems... Now that version stopped working this morning so I had to upgrade to 2.1.0, is it still possible to have streamings in 720p??? For my connection it would be much better than 1080... @robvdpol

**Comment by robvdpol** [comment]
Yes, you can force 720p by selecting 'Medium' video quality in the internal player window.

**Comment by ricky732** [comment]
Internal player gave me some big problems in 1.8.2.... It was good doing it
on vlc... Is there a way of doing it or should I try with internal
player?...

Il ven 30 apr 2021, 17:11 Rob ***@***.***> ha scritto:

**Comment by ricky732** [comment]
The problem is starting all the streams correctly and in synchro using just
a free VPN. Than I can stop the VPN and the stream still works, so the
problem is the beginning... 5 streams in 1080, will never start all them
😅😂

Il ven 30 apr 2021, 17:36 Rob ***@***.***> ha scritto:

**Comment by robvdpol** [comment]
You can set the video quality to medium and save the layout. Then, the next time you open the layout it will start immediately with the medium quality stream.

**Comment by ricky732** [comment]
I'll try tomorrow. Thank you!

Il ven 30 apr 2021, 21:04 Rob ***@***.***> ha scritto:

**Comment by ricky732** [comment]
Hiii! I started a replay and saved the layout but when I started it again
it was high quality... I went in the json file and it was video quality 1,
so I changed to 2, but when I restarted a replay it was high.. What am I
doing wrong? Does it work only for live sessions?

Il ven 30 apr 2021, 22:38 Riccardo Ferro ***@***.***> ha
scritto:

**Comment by ricky732** [comment]
There's a very very big problem with synchro. It's not allowed both on vlc
and internal player to stop the stream and resume it after 10 seconds to
make it synchronized... Is there a way to do it!?

Il sab 1 mag 2021, 09:56 Riccardo Ferro ***@***.***> ha
scritto:

**Comment by ricky732** [comment]
Hiiii mate!! The MPV syncro is very good but... How to set an higher cache
to all the streams without losing the syncro feature?? I need more or less
20 seconds more than the default cache on MPV (16 seconds if I'm not
wrong). How to set it taking still active the auto-syncro? 😁
