### ISSUE TITLE
[BUG] Unable to play via MPV, VLC or internal player.

### ISSUE THREAD

**Issue by charlesomer** [robvdpol/RaceControl#107]
**Describe the bug**
FP2 live stream seemed to work fine, then tried FP1 as a test and that worked fine. Paused FP1 for a while, came back to it later and it had closed and now I am unable to play via any of the players (tried restarting etc.).

Previously VLC and the internal player weren't working anyway but MPV did. I have tried copying the stream URL into VLC but there was no audio.

**To Reproduce**
1. Go to Grand Prix session.
2. Play stream via MPV, VLC or Internal Player.
4. Nothing happens with MPV and errors are shown for VLC and internal player.

**Expected behavior**
Expect each player to work (I have VLC installed).

**Screenshots**
![Internal Player 1](https://user-images.githubusercontent.com/32498151/116746300-2f8fce00-a9f4-11eb-93d1-daa810b16f2b.png)
![Internal Player 2](https://user-images.githubusercontent.com/32498151/116746301-30c0fb00-a9f4-11eb-9ee5-e63109f73e65.png)
![VLC](https://user-images.githubusercontent.com/32498151/116746306-30c0fb00-a9f4-11eb-9c62-ad72ef2db145.png)

**Desktop (please complete the following information):**
 - Windows 10 1909
 - System type 64bit
 - Version 2.1.0

**F1TV account**
- Subscription type Pro
- Tried multiple EU countries.
- VPN

My apologies if I've missed doing something obvious to get this to work!

**Comment by charlesomer** [comment]
Just tried reinstalling, doesn't seem to have changed anything. I've also checked in %localappdata% but there doesn't appear to be a Race Control folder.

**Comment by charlesomer** [comment]
Okay I’ve managed to fix VLC, just uninstalled and installed via Chocolaty (which added it to path). I have no idea why MPV now works again though 🤷‍♂️ but there we go.

Internal Player unfortunately still crashes but since I can use one of the other players that’s not too bad.

**Comment by robvdpol** [comment]
Probably fixed in next release.
