### ISSUE TITLE
Is Race Control now only works in Windows 10? 

### ISSUE THREAD

**Issue by vgbz48hr732** [robvdpol/RaceControl#109]
RC worked great until today, but I have a problem now. Is 2.0 only works in Win10?

I have a Win8/RC 1.8.1, and it was great until today. I updated to .NET 5.0 today, and I couldn't see any of the today's streams.

Any ideas? u/SpoIIie?I don't mind using the 1.8.1, do I have to downgrade the .NET?

Thanks guys (:

https://www.reddit.com/r/F1TV/comments/n2m9a8/is_race_control_now_only_works_in_windows_10/

**Comment by robvdpol** [comment]
Next release (2.1.1) should be compatible with Windows 8 again.
