### ISSUE TITLE
[BUG] Chromecast stream stops every time

### ISSUE THREAD

**Issue by molis83** [robvdpol/RaceControl#110]
**Describe the bug**
Chromecast(s) keep losing connection

**To Reproduce**
1. Scan network for chromecast
2. Play stream: world stream
3. Press button: cast
4. After some minutes, the tv screen goes black with blue chromecast logo on it.
This happens on all my chromecasts

**Expected behavior**
A stable stream

**Comment by vikdb** [comment]
Same here

**Comment by molis83** [comment]
On the computer I have 4 streams open (world, time, location and max), they all keep working.

**Comment by robvdpol** [comment]
Not much I can do about it, that's either an F1TV or a Chromecast issue. Once I send the stream to Chromecast it's out of my hands.
