### ISSUE TITLE
[BUG] Can't start Application

### ISSUE THREAD

**Issue by VolksDude** [robvdpol/RaceControl#112]
Trying to start application, (Installed from Microsoft Store), I receive this message.
https://imgur.com/4tPxAeS

I also, installed the latest .Net 5 manually.

Windows 10 20H2 64Bit

**F1TV account**
- Subscription (Pro)
- Canada
- No VPN or PROXY

**Comment by robvdpol** [comment]
Could you please post the relevant log file entries? This might already be fixed in the next release, but I'm not sure since I can't reproduce this.

**Comment by VolksDude** [comment]
I assume the logs are accessible through Event Viewer?

I've only found this in there..

[crashlog.txt](https://github.com/robvdpol/RaceControl/files/6412018/crashlog.txt)

**Comment by robvdpol** [comment]
Log file is located at %LOCALAPPDATA%\RaceControl

**Comment by VolksDude** [comment]
Folder "RaceControl" doesn't exist in LOCALAPPDATA. I've also checked in LocalLow and Roaming.

Anyhow, I've found the issue. It was totally me. I was trying the application on my HTPC using RDP for a quick test. Just started RaceControl directly on the system and worked perfectly. 

Sorry for taking some of your time.
