### ISSUE TITLE
[BUG] Racecontrol crashes when trying to watch with the "internal player"

### ISSUE THREAD

**Issue by ast1c** [robvdpol/RaceControl#117]
Hi,
I just downloaded the newest version of Race Control on my windows 10 Laptop today. When im trying to watch e.g. the portugese gp via the internal player (I press the "watch" button) Race Control just closes completely. I know there is the opportunity to watch the race with the 2 other players but I like the internal player the most. Hope you can help!
Thx 4 providing this app! :)

**Comment by robvdpol** [comment]
Did you get version 2.1.0 or 2.2.0? Because I just released 2.2.0 some hours ago which has fixed some issues. If you already have 2.2.0, please post relevant screenshots and/or log file entries.

**Comment by ast1c** [comment]
I`m using 2.2.0. Where can I find any logfiles?

**Comment by robvdpol** [comment]
%LOCALAPPDATA%\RaceControl

**Comment by ast1c** [comment]
I'm using the windows store app, so I think i have to install race control via github to see the logs right?

**Comment by robvdpol** [comment]
Nope, logs are always in that location.

**Comment by ast1c** [comment]
Unfortunately windows says this app can't be found.

**Comment by robvdpol** [comment]
I don't know what that means. Can you make a screenshot?

**Comment by SuRGeoNix** [comment]
Probably that was for the my .7z. You require to have 7-zip application to extracted. https://www.7-zip.org/download.html

**Comment by ast1c** [comment]
No it was for the logs. I thought this command:  %localappdata%\RaceControl\RaceControl.log must be paste in the windos-button + r search. 
Is this the right procedure? (sorry guys I'm not familiar with such things)

**Comment by ast1c** [comment]
and I have to add that this racecontrol crash does not happen everytime. Sometimes it's working sometimes not.

**Comment by robvdpol** [comment]
> No it was for the logs. I thought this command: %localappdata%\RaceControl\RaceControl.log must be paste in the windos-button + r search.
> Is this the right procedure? (sorry guys I'm not familiar with such things)

Yes, that will work, but you probably don't have a text editor configured to open .log-files. You could just go to the directory by pasting '%localappdata%\RaceControl' in windows explorer and then right-clicking the logfile to open it with notepad.

**Comment by ast1c** [comment]
I tried this with this command but I 

> > No it was for the logs. I thought this command: %localappdata%\RaceControl\RaceControl.log must be paste in the windos-button + r search.
> > Is this the right procedure? (sorry guys I'm not familiar with such things)
> 
> Yes, that will work, but you probably don't have a text editor configured to open .log-files. You could just go to the directory by pasting '%localappdata%\RaceControl' in windows explorer and then right-clicking the logfile to open it with notepad.

I tried it with this command but windows says this path could not be found. Probably race control is saved under a different name but I don't know why because I just downloaded it from the windows store and didn't do anything with race control except for playing videos (or at least to try).

**Comment by ast1c** [comment]
Edit: I reinstalled it now for the 3rd time and know it seems to be working all the time. I don't know what was causing this issue.

**Comment by robvdpol** [comment]
Ok, not sure what was going on then. Will close the issue.

**Comment by RickyNotaro** [comment]
> Nope, logs are always in that location.

I just wanted to let you know that windows don't allow access to users and administrative account to the folder if the installation is from Microsoft Store. 

![image](https://user-images.githubusercontent.com/6414422/117556956-4362b200-b03c-11eb-8259-cf90e895e583.png)
As you can see, the folder is visible when using the Save layout feature of the app. (App is running with another microsoft user priviledges) but now visible from my user account.

**Comment by robvdpol** [comment]
That's interesting, I wasn't aware of that.
