### ISSUE TITLE
[FEATURE]Add MPC-HC player support

### ISSUE THREAD

**Issue by tomidix** [robvdpol/RaceControl#120]
**Is your feature request related to a problem? Please describe.**
Add Media Player Classic support (like VLC is added) (MPC-HC, x64)

**Describe the solution you'd like**
When button MPC is clicked, media player classic should be opened 

**Describe alternatives you've considered**
Tried to use other players and I don't like them as much as MPC which can be easily used with the 'minimal preset' so no controls are shown. (and borderless)
Currently I'm using it manually with copy-paste link along with integrated player..

**Comment by robvdpol** [comment]
https://github.com/robvdpol/RaceControl/issues/114

I added support for MPC-HC yesterday, will be in the next release (probably next race weekend unless a critical bug pops up).
