### ISSUE TITLE
[BUG] Language Choice Not Working Properly (at least for Older Races)

### ISSUE THREAD

**Issue by nfrnc** [robvdpol/RaceControl#121]
Not sure if this is an actual bug or just a defect from the feed, but I am having an issue with the language settings for some of the older races (e.g., 2017 Bahrain Grand Prix). This manifests itself in two ways:

(1) When I use the "MPV", it defaults to audio track 1 "[zxx]" even though I have the "Default audio language" set to English. It also does this even if I also specify "alang=eng" in the "Additional MPV parameters:". The four tracks MPV shows when it's playing are [zxx], [en], [es], and [de].

(2) When I "Download" e.g., 2017 Bahrain Grand Prix, the audio tracks (languages) don't seem to map correctly. When I play the .ts file with Windows Media Player, it shows that there are four audio tracks and that all four are "English (United States)". The first of these, which it defaults to, is actually just the FX audio track. The second audio track is *actually* English. The third is actually Spanish. The fourth is actually German.

- Windows 10, 64-bit
- Race Control 2.2.0
- Subscription type: Pro
- Country: US subscription, accessing from Germany without VPN or proxy

**Comment by nfrnc** [comment]
Fyi, as the manual workaround of choosing the proper channel works as a fix, I wouldn't see this as an *urgent* issue. Just wanted to log it.

**Comment by robvdpol** [comment]
Ah, I kind of forgot to implement the 'default audio language' for MPV as well. It only works for internal player and casting at the moment. Will do it for next release.

As for issue 2 I'm not sure I can do much about it. I might even limit downloading of audio tracks to only the preferred audio language. Then you'll only have one audio track anyway and it should always be the correct one (for onboards it will be team radio).

**Comment by robvdpol** [comment]
Issue has been fixed.
