### ISSUE TITLE
[FEATURE] Is it possible to get markers on the players to resume watching when we left a live session ?

### ISSUE THREAD

**Issue by Pschirki** [robvdpol/RaceControl#13]
Idk if this would be possible for the other players than the internal, but it would be convenient to pick up watching where you left.

Thanks again for this gorgeous program!

**Comment by robvdpol** [comment]
Can you clarify a bit what you mean? Is it for watching replays or live sessions?

**Comment by Pschirki** [comment]
I mean when you stop watching a streamng session, it would be great to be able to resume it later on a replay maybe within the same minute where you left it

**Comment by robvdpol** [comment]
I have no idea how to do this, there's no way to get the timestamp when watching a live stream.

Closing this issue.
