### ISSUE TITLE
Internal player doesn't work

### ISSUE THREAD

**Issue by sigurasg** [robvdpol/RaceControl#130]
Version 2.2.0. Win 10 Pro, 19041.985.

Love the app, use it mainly for casting on race day. The internal player doesn't work for me anymore, however. It used to, but probably two updates ago. Same behavior on Windows store version and the .msi.

When I click "Watch" for any video, I get a couple of dialog popups. 
One says "Object reference not set to an instance of an object.", the other one is

--- cut here ---
HRESULT: [0x887A0001], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_INVALID_CALL/InvalidCall], Message: The application made a call that is invalid. Either the parameters of the call or the state of some object was incorrect.

Enable the D3D debug layer in order to see details via debug messages.
--- cut here ---

**Comment by SuRGeoNix** [comment]
Hi @sigurasg , the internal player has been changed lately and might still has some compatibility issue with old hardware/gpu. Can you please send two screenshots by running 'dxdiag' command (System/Display tabs)

**Comment by SuRGeoNix** [comment]
@sigurasg It should be fixed on 2.3.0, give it a try and let us know

**Comment by sigurasg** [comment]
2.3.0 works like a charm. Attaching the DxDiag output as well for good measure. Apologies for the tardiness, my email notification settings were messed up...
[DxDiag.txt](https://github.com/robvdpol/RaceControl/files/6502821/DxDiag.txt)

**Comment by sigurasg** [comment]
PS: Thanks!
