### ISSUE TITLE
[FEATURE] Notification/Toast when something goes live

### ISSUE THREAD

**Issue by StephanBruh** [robvdpol/RaceControl#137]
**Is your feature request related to a problem? Please describe.**
No Its not.

**Describe the solution you'd like**
Would be nice if we could have a option to get a notification (windows toast?) when something goes live. Only popups in the "Live Now" block now.

**Comment by maxverstappen** [comment]
+1

**Comment by robvdpol** [comment]
I looked into this, but toast notifications in Windows are such a big mess if you want to support Windows 7/8/8.1/10.

Maybe playing a sound would be fine?

**Comment by maxverstappen** [comment]
Yes. Works for me

**Comment by StephanBruh** [comment]
> I looked into this, but toast notifications in Windows are such a big mess if you want to support Windows 7/8/8.1/10.
> 
> Maybe playing a sound would be fine?

Yeah that will work for me, maybe also make it flash orange then aswell in the taskbar?

**Comment by robvdpol** [comment]
Will be available in next release.
