### ISSUE TITLE
[BUG] Nothing shows at "Live now"

### ISSUE THREAD

**Issue by mufraver2** [robvdpol/RaceControl#138]
**Describe the bug**
`Task<List<Session>> GetLiveSessionsAsync()` fails at the moment. There is nothing at the "Live now" even though the race is found at the "Sessions"

![image](https://user-images.githubusercontent.com/45003186/119254044-cb0ffb00-bbbc-11eb-993e-a9aebc2d8e4a.png)

For some reason one of the `container.Properties` is null at the moment and because of that there is no events at the "Live now"

![image](https://user-images.githubusercontent.com/45003186/119254085-04e10180-bbbd-11eb-8c8a-8b5e62edcfa9.png)

It seems that the container is correct but for some reason the API returns null for that "Properties" property. At the moment if you use null as the "SeriesUID" property the `GetSessionShortName()` fails because of that null
![image](https://user-images.githubusercontent.com/45003186/119254657-298aa880-bbc0-11eb-9b1c-95d584b563e8.png)

**To Reproduce**
1. Make sure "Porche Supercap" is selected
2. Nothing shows at the "Live now"

**Comment by robvdpol** [comment]
I couldn't reproduce this because the Supercup was already finished, but it should be fixed.

**Comment by MaggotMouth** [comment]
Will there be a new release before the race?

**Comment by robvdpol** [comment]
No, there aren't any major issues that have been fixed so not really needed. Goal is to have no more than one release per race weekend.

**Comment by MaggotMouth** [comment]
I thought this was a major issue - didn't know that the live sessions were still available via the session tab.  Thanks for an awesome app btw.

**Comment by mufraver2** [comment]
> I thought this was a major issue - didn't know that the live sessions were still available via the session tab. Thanks for an awesome app btw.

I think the API response for that Porche race was buggy or something like that. It has been working properly previosly and seems to be working normally at the moment
