### ISSUE TITLE
[FEATURE] Change logo to avoid copyright issues

### ISSUE THREAD

**Issue by jakecausier** [robvdpol/RaceControl#140]
**Is your feature request related to a problem? Please describe.**
The files appicon.png and splashscreen.png both use the official F1 logo, which is in violation of their guidelines on usage of their 'marks'. I've seen numerous applications and fan works be hit by them for this unfortunately, and I'd hate to see this one get hit too.

**Describe the solution you'd like**
Logo could be replaced with the icon used currently from FlatIcon, or the alternate below.

**Describe alternatives you've considered**
I've created a quick icon fitting for the application using the same style as the official logo if you'd like to use it as an alternate. I've attached a .zip with both PNG and SVG versions (preview below also).

![RaceControl](https://user-images.githubusercontent.com/37668780/119268037-9877f980-bbe0-11eb-8222-d971430f075f.png)
[RaceControl.zip](https://github.com/robvdpol/RaceControl/files/6528441/RaceControl.zip)

**Additional context**
The font used for writing 'Race Control' in splashscreen.png is also protected under their guidelines and cannot be used.
Full guidelines: https://www.formula1.com/en/toolbar/guidelines.html

**Comment by robvdpol** [comment]
Thanks, I used your icon as splashscreen and app icon.
