### ISSUE TITLE
[FEATURE] Remember the network interface for casting

### ISSUE THREAD

**Issue by thomaskirz** [robvdpol/RaceControl#141]
**Is your feature request related to a problem? Please describe.**
When Race Control is started, I always have to change the interface used for Chromecast discovery.
![image](https://user-images.githubusercontent.com/10871450/119319430-babe5580-bc7a-11eb-9a29-aad882b9ba5b.png)

**Describe the solution you'd like**
Race Control remembers, which interface was last used and selects it the next time it is opened.

**Comment by robvdpol** [comment]
Fixed in next release.
