### ISSUE TITLE
[BUG] A .NET application failed.

### ISSUE THREAD

**Issue by ispweb** [robvdpol/RaceControl#144]
Has been working without problems but today the app doesn't open anymore., the eventlog gives the below error. I tried the latest .NET 5.0 Desktop Runtime (v5.0.6) - Windows x64 Installer and latest version of F1 Rae Control.

Description: A .NET application failed.
Application: RaceControl.exe
Path: C:\Program Files\WindowsApps\16380RobvanderPol.F1RaceControl_2.3.1.0_x64__2z9spsj1fgqzr\RaceControl\RaceControl.exe
Message: Failed to load the dll from [C:\Program Files\WindowsApps\16380RobvanderPol.F1RaceControl_2.3.1.0_x64__2z9spsj1fgqzr\RaceControl\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from C:\Program Files\WindowsApps\16380RobvanderPol.F1RaceControl_2.3.1.0_x64__2z9spsj1fgqzr\RaceControl\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306

**Comment by ispweb** [comment]
The App from Windows Store doesn't work anymore, but the downloaded version from github works when i open it from the installed directory.

**Comment by robvdpol** [comment]
Yeah, I noticed that as well, Microsoft f***ed something up with Visual Studio 16.10. I had to revert to 16.9.6 to get the app package to build correctly. A hotfix is already in the Microsoft Store by now, so it should update itself on your end.

Please be aware that the Microsoft Store will list it as version 2.3.2.0 (I couldn't re-use the 2.3.1.0 version number), but in reality it's still Race Control version 2.3.1.0.
