### ISSUE TITLE
Unable to cast live stream to chromecast[BUG]

### ISSUE THREAD

**Issue by geintje** [robvdpol/RaceControl#148]
Since Monaco GP every live feed I am trying to cast give's ' Load failed' error
When I use F1 media android app from phone to stream to my Chromecast, it works flawless.
Any other cast ( from youtube) works fine.
Which makes me believe the issue is in the RaceControl App not in my Chromecast/home network.
Things I tried : 
- Logout and login again with working credentials
- uninstall RaceControl
- install RaceControl from GitHub and from Microsoft Store

Issue remains, any live feed gives ' Load failed' error.

[RaceControl.log](https://github.com/robvdpol/RaceControl/files/6602216/RaceControl.log)

All pre-recorded streams work fine, no issues there,

**Comment by petermbode** [comment]
exact same issue here

**Comment by Lineos** [comment]
Same here!

**Comment by maxverstappen** [comment]
Same here 
Work around playing via VLC  and rendering to chromecast. Is a good workaround

**Comment by robvdpol** [comment]
Duplicate of issue #132
