### ISSUE TITLE
[FEATURE] Ability to change shortcuts

### ISSUE THREAD

**Issue by haladynkamil** [robvdpol/RaceControl#149]
Ability to change shortcuts would be avesome.
Mainly there is one issue i have, that ESC button is used to close player window. When i watch on full screen, I tend to automatically click ESC to get out of fullscreen just like in youtube or netflix. 

Alternate solution for me would be to give ESC ability to close fullscreen and go back to normal window

**Comment by robvdpol** [comment]
What shortcut would be good for closing the player window? If I were to map ESC to exit fullscreen.

**Comment by robvdpol** [comment]
I made it so that ESC exits fullscreen when in fullscreen mode, otherwise it closes the player. Hope that helps.
