### ISSUE TITLE
[Bug] layout does not open correctly in MPV

### ISSUE THREAD

**Issue by Melantrix** [robvdpol/RaceControl#15]
I have a windows laptop that is connected to a 4k TV. Current resolution settings are:
- 3840x2160
- scale 125%

When i open race control and create a layout with the internal player (afaik this is the only method of creating a layout that can be saved?). Next i close all windows and press the button, open saved layout in MPV. The layout is then much smaller then it should be and it doesn't use the full screen. Attached are some screenshots for comparison. 

Note: opening the layout in internal player does work correctly and uses the full screen. 
This is the correct layout in the internal player:
![internal](https://user-images.githubusercontent.com/4669661/95651487-102e6380-0aeb-11eb-8987-92d9524eb01d.jpg)

This is the smaller layout in the MPV player. 
![MPV](https://user-images.githubusercontent.com/4669661/95651488-10c6fa00-0aeb-11eb-9b9c-1c922584b087.jpg)

**Comment by robvdpol** [comment]
I think I fixed it, the calculation to relative screen coordinates didn't respect the screen scale. I'll release a patch before qualifying.

By the way, be aware that using different screen scales on different screens in a multi monitor setup is not supported, you'll get all kinds of strange layout issues. So I recommend using the same screen scale on all your screens.

**Comment by Melantrix** [comment]
Thanks! i'll try it during qualifying and let you know if it works!

Fortunately i don't use a mixed screen scale setup. when i have my laptop connected to the tv, my laptop screen is disabled.

**Comment by robvdpol** [comment]
New release is out, please let me know if this works for you.

**Comment by Melantrix** [comment]
yes it works! thanks for the quick response and fix!!
