### ISSUE TITLE
[FEATURE] Do not play new live session detected during active live session

### ISSUE THREAD

**Issue by bobvandevijver** [robvdpol/RaceControl#151]
I just got surprised by the new live session detected sound while still looking at the post qualification interviews. I believe it should not be played when another live session is currently being played.

**Comment by robvdpol** [comment]
Good catch, I'll fix that.

**Comment by rens243** [comment]
Wouldn't mind a option to turn it off altogether. The sound spooked me a bit. 😅

**Comment by robvdpol** [comment]
This should do for now.
