### ISSUE TITLE
[BUG] When a stream does not load, the player cannot be closed

### ISSUE THREAD

**Issue by kkaja123** [robvdpol/RaceControl#153]
**Description**
The list of live streams during a race includes the Backup Stream. When trying to watch it (using the internal player), the stream does not load, but the player cannot be closed. The "x" button is disabled and the right-click option to close the player is also disable. When clicking "Close all players" the other players will be correctly closed, but the unloaded stream player remains open.

**To Reproduce**
1. Go to the live streams list.
2. Open the Backup Stream using the internal player. (Backup stream is used since it seems that F1TV has removed that stream.)
3. Observe that the stream does not load in the player. The X button is disabled/greyed out, and the player cannot be closed using the right-click menu.

**Expected behavior**
Even if a player cannot connect to the stream endpoint, it should still have the option to be closed through all normal avenues.

**Screenshots**
![image](https://user-images.githubusercontent.com/36752032/120929266-0119a880-c6ae-11eb-870c-5726f5521a22.png)

**Desktop (please complete the following information):**
 - Windows 10 21H1
 - 64-bit
 - Race Control 2.3.1

**F1TV account**
- Subscription type: Pro
- United States
- Using VPN or proxy? No.

**Additional context**
I haven't seen the Backup Stream actually connect during any of the 2021 season races, so perhaps that option should be removed from the live channel list.

**Comment by henshinger555** [comment]
I only see this issue happening with the Azerbaijan GP World Feed. All the other feeds don't have this issue, at least for me. This issue also affects casting.

**Comment by robvdpol** [comment]
Fixed this one.

@henshinger555 what you're reporting is a different issue. The replay of the Azerbaijan GP world feed seems to be incompatible with either Flyleaf or FFmpeg. I'll look into it.
