### ISSUE TITLE
[FEATURE] Change language for downloads

### ISSUE THREAD

**Issue by PaSas007** [robvdpol/RaceControl#156]
Hey guys,

first of all: amazing work, F1 is getting on another level because of your work.

I don't know if it's already a feature and I am just not finding it but is it possible to change the language for your downloads?
If not, could you implement it into the client?

Cheers from Germany!

**Comment by robvdpol** [comment]
Downloads will have all audio tracks included, so you can choose the desired audio track yourself from your media player.

**Comment by PaSas007** [comment]
Well, I didn't consider this as a solution. Thanks!

**Comment by robvdpol** [comment]
Just a heads up, I think the audio tracks are not properly named, so you might have to do fiddle around a bit to find the desired language.
