### ISSUE TITLE
Allow sort on channels by driver name

### ISSUE THREAD

**Issue by balaji8** [robvdpol/RaceControl#165]
**Is your feature request related to a problem? Please describe.**
It would be nice to have the onboard driver channels sorted by name. At the moment, the sort is based on channel type. Adding a second level of sort by name would be helpful. 

**Describe the solution you'd like**
When displaying the list of channels, allow the sort to be performed by channel type first (wif, additional, obc, backup) like it is now and then by driver first name or last name. The preference can be selected from a drop down in the settings panel with Default sort, and sort by ascending or descending by First or Last name of the driver.

**Comment by robvdpol** [comment]
Driver channels will be sorted by driver name for now.
