### ISSUE TITLE
[BUG] Austrian GP not showing up

### ISSUE THREAD

**Issue by rdlorama** [robvdpol/RaceControl#166]
**Describe the bug**
Austrian GP is not showing up in available list

**To Reproduce**
Start the program. Click on 2021 year, check available GPs

**Expected behavior**
Austrian GP is up on the f1tv site and is available in other 3rd party programs

**Screenshots**
![sessions](https://user-images.githubusercontent.com/86436797/123329295-f3cd3c80-d53c-11eb-95af-b2ab19e91412.png)

**Desktop (please complete the following information):**
Windows 10 Pro 21H1 19043.1055
64bit
Race Control 2.3.3 (same on 2.3.1)

**F1TV account**
Pro sub
No VPN/ no proxy

**Comment by robvdpol** [comment]
It was missing in the F1TV search API, but they have added it now.
