### ISSUE TITLE
[BUG] Object reference not set to an instalnce of an object

### ISSUE THREAD

**Issue by ElectricImpossible** [robvdpol/RaceControl#17]
**Describe the bug**
windowsdesktop-runtime-3.1.9-win-x64 installed 
Racecontrol 1.8.1 installed

**To Reproduce**
installed to c:\RaceControl
Open the app as administrstor
Get to login prompt
Enter any username/password and hit login button (valid/invalid credentials have the same effect)
after 2 seconds red text under password field " Object reference not set to an instalnce of an object."

**Expected behavior**
I expect to log in and browse streams presented to me. I have previously used your applicaiton on 1.8 which I upgraded to 1.8.1.

I have deleted the stored credentials in Windows
I have deleted \AppData\Local\RaceControl
I have run the installer again and deleted the app
I have rebooted
I have reinstalled the app and experienced the same issues.

**Screenshots**
https://i.imgur.com/IjcBGCY.png

**Desktop (please complete the following information):**
 - Windows 10 Pro N 1909 64bit

**F1TV account**
- Subscription type - Pro
- Country - NA
- Using VPN or proxy? Attempted with and without and same issue occurs

**Additional context**
When running the application I see a request for api.formula1.com hit my firewall and is forwarded.

**Comment by robvdpol** [comment]
I can reproduce the NullReferenceException when I login with invalid credentials. However, I'm able to login with my F1TV credentials with no problems. Could you please attach your log file? It's located in the \AppData\Local\RaceControl folder. It would be even better if you could record the login HTTP requests using Fiddler Classic and attach them. Please note there's two HTTP requests for logging in:

1. https://api.formula1.com/v2/account/subscriber/authenticate/by-password
2. https://f1tv-api.formula1.com/agl/1.0/unk/en/all_devices/global/authenticate

For now I will fix the NullReferenceException and give a more meaningful error when using invalid credentials.
