### ISSUE TITLE
[FEATURE] Button/context menu to bring main window to focus

### ISSUE THREAD

**Issue by balaji8** [robvdpol/RaceControl#172]
I usually have the world feed on my primary monitor and the pit lane tracker, timing screen, on board cameras on my secondary monitor. So the primary UI is kind of hidden from view. 

It would be helpful to have a button on the internal video player windows and if possible a shortcut bound to it, to allow the main window to come into focus (also launch it if its not open at the moment).

**Comment by robvdpol** [comment]
Added in upcoming release.
