### ISSUE TITLE
[BUG] Austrian GP is not visible

### ISSUE THREAD

**Issue by IkamG** [robvdpol/RaceControl#174]
**Describe the bug**
Austrian GP is not visible for 2021

**To Reproduce**
1. Go to 'Race Season 2021'

**Expected behavior**
Should be able to see Austrian Grand Prix under events and associated streams (currently driver pressers and weekend warmup)

**Actual behavior**
Not visible
 
**Screenshots**
![image](https://user-images.githubusercontent.com/24984183/124188009-aac13f00-da8c-11eb-9f73-b078c3bbd3d0.png)

**Desktop (please complete the following information):**
 - Windows 10
 - System type (64 bit)
 - 2.2.0

**F1TV account**
- Pro
- Canada

**Comment by nAffie** [comment]
Same as last week, the Styrian GP became visible on Friday so if you wanted to watch the driver press conferences on Thursday, you had to do it on the website or with the F1TV phone app.

**Comment by jagr200** [comment]
> Same as last week, the Styrian GP became visible on Friday so if you wanted to watch the driver press conferences or the weekend warm-up on Thursday, you had to do it on the website or with the F1TV phone app.

While that might be true this is the first time I have encountered it. I have always been able to use it on Thursdays.

**Comment by robvdpol** [comment]
> > Same as last week, the Styrian GP became visible on Friday so if you wanted to watch the driver press conferences or the weekend warm-up on Thursday, you had to do it on the website or with the F1TV phone app.
> 
> While that might be true this is the first time I have encountered it. I have always been able to use it on Thursdays.

Austrian GP is available now.

It's an issue on F1TV API side, but I think it will only be a problem for the Austrian GP's, since those were the only ones missing and were added last-minute.
