### ISSUE TITLE
[FEATURE] Full Screen Hotkeys for every player window

### ISSUE THREAD

**Issue by igor-martinovski** [robvdpol/RaceControl#18]
First of all; this is awesome!  Thank you for developing such a polished app with no frills that just works!

My feature request is to have a hotkey for every player window that toggles full screen. Currently you have to click on the window and press the full screen hotkey.
It would be nice to have keys 1-9 to toggle full screen for a specific window.

The specific full screen hotkeys can also mute all other windows and only unmute the full screen player.

Full screen should be local to the monitor that the screen is shown on

I am not sure what the best way would be to enumerate each window but maybe they can be enumerated based on the order they were opened,

**Comment by robvdpol** [comment]
I've added it to the to do list for version 1.9. It will be tricky to keep track of all the player windows, especially if you also close some windows, but I think it can be done.

Could you maybe explain the use case a bit more? Do you often switch between player windows while watching a race or qualifying session?

Thanks for the sponsor by the way!

**Comment by robvdpol** [comment]
First iteration of this feature has been implemented, I'll make a release tomorrow.

**Comment by igor-martinovski** [comment]
@robvdpol, just tried this; works well!
