### ISSUE TITLE
MPV Volume control or native player skip while live

### ISSUE THREAD

**Issue by jagr200** [robvdpol/RaceControl#180]
So when watching live I have noticed the native player doesn't allow me to manually skip the feed forward to sync streams. So I use the MPV player as it allows me to pause and skip forward within the cache. It usually has about 30 seconds in cache and this allows me to sync live feeds. When using MPV I am unable to adjust audio levels. Not sure if this is normal or not. But I would love to be able to set the main feed to say 75% and a driver feed 100% etc.

Is there a fix for this?

**Comment by robvdpol** [comment]
This is an MPV issue, right? For me, changing the audio volume in MPV works fine (using the '9' and '0' keys).

**Comment by jagr200** [comment]
> This is an MPV issue, right? For me, changing the audio volume in MPV works fine (using the '9' and '0' keys).

Well I personally like the player that you select on the far right. That says "watch" because of the little arrows that allow you to automatically place it in certain areas of the screen. MPV is hard to get to fill the screen correctly. I like to watch 4 in car feeds on one monitor and then the main feed on another monitor.

I didn't realize volume could be controlled using the 9 and 0 keys. So that is good to know.

**Comment by robvdpol** [comment]
Did you know you can create and save a layout using the internal player and then open it in MPV? That would solve your placement issues.
