### ISSUE TITLE
Force close on startup after login[BUG]

### ISSUE THREAD

**Issue by mayorizrod** [robvdpol/RaceControl#182]
Fresh install of F1RC from MS Store. Launching the app opens the main window for 1 second and then just closes. No error messages or any sort of feedback. The first time launch stayed alive until i entered my credentials and then force closed and keeps force closing since on startup. Reinstalling doesnt help.

Windows 10 x64 21H1 19043.1110
All windows updates installed.
3930K/32GB-DDR3/GTX1060-6GB
F1TV Pro subsrciption / Bulgaria
No proxy/VPN, just router NAT.

App works wonderfully on my other PC in the Netherlands but no dice here.

**Comment by robvdpol** [comment]
Is there anything in the log file?
