### ISSUE TITLE
[BUG] App not available on the MS Store in Brazil

### ISSUE THREAD

**Issue by LordMrcS** [robvdpol/RaceControl#184]
**Describe the bug**
The store says the app is not available. Only offers to redeem a code.

**To Reproduce**
1. Go to 'https://www.microsoft.com/pt-br/p/f1-race-control/9mwc9pj4jfww?wa=wsignin1.0&activetab=pivot:overviewtab'
2. Try to get the app
3. See error

**Expected behavior**
To be able to get the app then install.

**Screenshots**
[Screenshot](https://imgur.com/a/2bgMXQN)

**Desktop (please complete the following information):**
 - Windows 10
 - 64 bit
 - not installed

**F1TV account**
- Pro
- Brazil
- No proxy

**Additional context**
Able to use the app normally outside the store.

**Comment by robvdpol** [comment]
https://www.reddit.com/r/F1TV/comments/oln69u/fom_clampdown_on_3rd_party_tools_race_control/

In short, if you don't already own the store version, you will need to use the MSI installer.

**Comment by LordMrcS** [comment]
> https://www.reddit.com/r/F1TV/comments/oln69u/fom_clampdown_on_3rd_party_tools_race_control/
> 
> In short, if you don't already own the store version, you will need to use the MSI installer.

Thanks for the info, I was out of the loop.
