### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Juanson69** [robvdpol/RaceControl#186]
Downloads out of date
Downloads from early 1981 have no commentary while "streaming" does

**To Reproduce**
View the 1981 Brazilian Grand Prix on f1tv. Hear Murray.
Download the same race in Race Control. Hear nothing but natural sounds.

**Expected behavior**
...the same thing to be on the proper download as the "streaming" version.

**Desktop (please complete the following information):**
 - Windows 10... sadly

**F1TV account**
- Subscription type (none, Access, Pro) Pro
- Country UK
- Using VPN or proxy? No

**Comment by robvdpol** [comment]
Downloads will contain all audio tracks and it's up to your media player which audio track is played by default. You can simply switch to the different audio track yourself.
