### ISSUE TITLE
[FEATURE] Sort events in descending order

### ISSUE THREAD

**Issue by mufraver2** [robvdpol/RaceControl#193]
**Describe the solution you'd like**
For me it would be better to sort the events in descending order like the in the "Race Seasons" box. With descending order you don't need to use the scrollbar if it shows (i'm lazy). 

![image](https://user-images.githubusercontent.com/45003186/127656674-eaa66a25-16e1-4a16-ab08-cd8b248c67e0.png)

**Additional context**

![image](https://user-images.githubusercontent.com/45003186/127656774-b7c3cf70-82ed-4066-8573-b6f2d29f8f77.png)

**Comment by robvdpol** [comment]
Fixed in upcoming release
