### ISSUE TITLE
[BUG] Not Able to Update From Microsoft Store

### ISSUE THREAD

**Issue by Vallesuski** [robvdpol/RaceControl#194]
**Describe the bug**
I currently have Race Control v2.3.4 and I'm not able to update into v2.3.5 because is no longer in Microsoft Store.
Can you please explain how can I get the update? Should I 'uninstall' current version, then download the newest and install again?

**To Reproduce**
1. Go to 'Microsoft Store App' in Windows
2. Select See More '...'
3. Select 'My Library'
4. Select 'All Owned'
5. Race Control Is Not Showed =(

**Expected behavior**
I expect to see Race Control under My Library in Microsoft Store in order to get the update.

**Desktop (please complete the following information):**
 - Windows 10 Enterprise
 - System type (64 bit)
 - Version 20H2

**F1TV account**
- Subscription type (Pro)
- Mexico
- No VPN or proxy

**Additional context**
Can you please explain how can I get the update? Should I 'uninstall' current version, then download the newest and install again?

**Comment by jagr200** [comment]
Seeing the same issue. I wonder if F1 had it removed. But it isn't on the store anymore. Can't even find it in my download history.

Best option right now is to uninstall and install it from github. A few extra steps but won't be removed by MS.

**Comment by robvdpol** [comment]
Yep, FOM filed a complaint and Microsoft removed it from the store. I might be able to get it back on but for now you should use the MSI.
