### ISSUE TITLE
[BUG] Other application volumes get set to 100 when Race Control is open

### ISSUE THREAD

**Issue by Kelvinh95** [robvdpol/RaceControl#195]
**Describe the bug**
With Windows Volume Mixer you can set the volume level for each individual application.
The problem is when Race Control is open and you open a different application for which you had set the volume level it gets reset to 100. 
This only happens to applications which get start after race control was started, so applications which were already running do not get reset.

**To Reproduce**
1. Open an application, for this example Chrome
2. Play something with sound through Chrome so that Windows recognizes it as sound output in the volume mixer
3. Set the volume to something other than 100, for example to 30
4. Open Race Control
5. Close Chrome
6. Open Chrome
7. Play something with sound again. 
8. The volume is now reset to 100 because Race Control is open

**Expected behavior**
The expected behaviour is that the default behaviour for set volumes for the different application in the volume mixer does not get affected by Race Control.

**Screenshots**
Start situation:
![image](https://user-images.githubusercontent.com/5929773/127742362-9889a0ba-9c62-48f2-b079-143f25c01b87.png)
After reproduction:
![image](https://user-images.githubusercontent.com/5929773/127742462-a1a48a2c-0cf5-42df-b862-1566e61726ed.png)

**Desktop (please complete the following information):**
 - Windows 10 Home
 - 64 Bit
 - RC:2.3.5 ; Windows: 20H2

**F1TV account**
- Pro Subscription
- Netherlands
- No VPN or proxy

**Additional context**
The volume mixer you see in the screenshot is purely an UI addon. It does not have any functionality.

**Comment by Kelvinh95** [comment]
This appears to be an issue with Flyleaf (or one of the underlaying dependencies). Testing with the Flyleaf Winforms Sample results in the same issue.

**Comment by Kelvinh95** [comment]
Pullrequest created in Flyleaf repo https://github.com/SuRGeoNix/Flyleaf/pull/55

**Comment by robvdpol** [comment]
Should be fixed in upcoming release because I updated Flyleaf to latest version.
