### ISSUE TITLE
[BUG] Value cannot be NULL

### ISSUE THREAD

**Issue by mfkl** [robvdpol/RaceControl#21]
**Describe the bug**

This isn't critical, just FYI.

When using an expired session, clicking on any action button (download, copy, watch, etc) will result in an expected error message.

**To Reproduce**
1. Go to Pre-season Testing 2020, I selected Test 2 - Day 3, session 2, but others likely work as well
2. Try to copy URL

**Expected behavior**
Probably another well defined error message.

**Screenshots**

![bug-report-f1tv-null](https://user-images.githubusercontent.com/3928834/97138600-27c44800-178b-11eb-9579-6e7f546871d3.PNG)

**Desktop (please complete the following information):**
 - Windows 10
 - System type 64 bit
 - Version latest

**Comment by mfkl** [comment]
Just figured out that my VPN was reset to my default location, putting back to NL and now that error window is gone. Quite the edge case haha! But thought you might be interested.

**Comment by robvdpol** [comment]
Fixed.
