### ISSUE TITLE
[BUG] F1TV backend changes breaks playback with most video players / downloads

### ISSUE THREAD

**Issue by NadimAsad** [robvdpol/RaceControl#210]
**Describe the bug**
Currently, downloads / playback with internal player / playback with mpv are all broken due to this backend change. Before for retrieving the master playlist and all the media segments from the media playlists from the master playlist was as simple as doing a GET request to the segment/playlist. However, now it seems like F1TV wants to use cookie "playToken" to authenticate GET requests to content server. Most video clients (ffmpeg, mpv, RaceControl's internal player) doesn't seem to be able to set and send the cookie correctly. As a result, all content fail to load via the above mentioned players. VLC Media Player however is able to load the content without issue it seems like.

**To Reproduce**
Open any video stream with RaceControl's Internal Player or MPV, or download them.

**Expected behavior**
Video to play / download properly.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11 Pro 64-bit

**F1TV account**
- Subscription type: Pro
- Country: Canada
- Using VPN or proxy: No

**Additional context**
Why it actually fails? Requesting media segments, media playlists without "playToken" cookie returns a 400 Bad Request from F1TV.

~~**Fix for MPV Playback**~~
~~Add `--cookies` to "Additional MPV parameters:" in "Options" to fix MPV playback!~~

**Comment by LuXe5** [comment]
Only VLC is able to live stream at the moment

**Comment by Pschirki** [comment]
> Only VLC is able to live stream at the moment

MPV worked for me too during FP3 in Spa, since changing language to German in VLC stops the stream :(

**Comment by Lolihunter1337** [comment]
MPV Seem to work again 🤔

**Comment by ragnos** [comment]
As far as I can tell the new cookie authentication is currently only used during F1 sessions.

**Comment by robvdpol** [comment]
This is fixed in the upcoming release. I added support for playToken cookies to the internal player and downloads (using a HEAD-request as suggested to retrieve the playToken cookie). VLC and Chromecast already properly support cookies. For MPV I use the BIG_SCREEN_HLS moniker, which doesn't require playTokens at the moment. All the other players use the WEB_HLS moniker now.
