### ISSUE TITLE
[BUG] Option to open with VLC missing with VLC installed on device

### ISSUE THREAD

**Issue by NadimAsad** [robvdpol/RaceControl#211]
**Describe the bug**
The button to open videos with VLC media player is missing from Race Control on my system. Latest VLC media player is installed with [the registry key used to detect VLC presence](https://github.com/robvdpol/RaceControl/blob/8a55b3e62adbb25650df46182b323bb245586b61/RaceControl/RaceControl/ViewModels/MainWindowViewModel.cs#L602) is also present in my system.

**To Reproduce**
1. Go to any VOD / HLS.
2. The buttons to download / play doesn't show VLC as an option.

**Expected behavior**
Ability to open VODs / HLS with VLC.

**Screenshots**
VLC key present in registry
![image](https://user-images.githubusercontent.com/73384968/131025742-de6c2933-5dac-4f7d-ad7f-662901a190ec.png)

Option to open with VLC missing
![image](https://user-images.githubusercontent.com/73384968/131025781-14626c3d-6aca-4ca5-9362-29c0336539a1.png)

**Desktop (please complete the following information):**
 - Windows 11 Pro

**F1TV account**
- Subscription type: Pro
- Country: Canada
- VPN or proxy: No

**Additional context**

**Comment by robvdpol** [comment]
Which version of VLC are you using? I uninstalled VLC and reinstalled it (latest version 3.0.16) and the registry key is there.

**Comment by NadimAsad** [comment]
It is version 3.0.16 as well, used winget to install VLC, which downloads from [videolan.org](https://download.videolan.org/vlc/3.0.16/win64/vlc-3.0.16-win64.msi)

![image](https://user-images.githubusercontent.com/73384968/131593009-e3a72dab-2472-41a6-a717-76653021d4c3.png)

With that, only InstallDir is provided in registry for me.

![image](https://user-images.githubusercontent.com/73384968/131593049-d2bf19cf-77db-4fcb-a30b-461089740b63.png)

**Comment by robvdpol** [comment]
This is what I get when I install VLC 3.0.16:

![image](https://user-images.githubusercontent.com/56960828/131618251-9d622dde-3cb5-4036-9bff-b205396788b0.png)

Very weird, maybe it's an issue with winget? Anyway, I'll change the code so it will support your case as well.

**Comment by robvdpol** [comment]
Fixed in upcomin release.
