### ISSUE TITLE
[BUG] Installer asks for administrator rights when installing 'just for me'

### ISSUE THREAD

**Issue by tomidix** [robvdpol/RaceControl#212]
**Describe the bug**
Trying to install the app with 'just for me' option and providing with the C:\LocalData\F1_Race_Control folder (which I do have rights to use) and having the UAC prompt for admin rights is I think strange at least. If we know that windows store version works in sandbox mode, I think it should be possible here too.

**To Reproduce**
1. Try to install for current user which does not have admin rights

**Expected behavior**
Ability to install and use the app on the pc where you don't have the admin rights (like it was possible when store version was published)

**Screenshots**
/

**Desktop (please complete the following information):**
 - Windows 10 21H1
 - 64 bit
 - Build 19043.1165

**F1TV account**
/

**Additional context**
/

**Comment by robvdpol** [comment]
I might simply create a 'portable' release as a zip-file.

**Comment by tomidix** [comment]
That would be nice solution ☺

**Comment by robvdpol** [comment]
Portable version 2.4.0 released.
