### ISSUE TITLE
Crashes when trying to download a video

### ISSUE THREAD

**Issue by raulongo** [robvdpol/RaceControl#220]
Downloaded some stuff on September 1st, but I'm trying to download things today and it crashes (the program vanishes and it's force closed). I would provide the log, but can't find it.

**Comment by roniel06** [comment]
Hi @raulongo , you can find the Log file at C:\Users\your_user\AppData\Local\RaceControl

please find it and post it here please.

**Comment by robvdpol** [comment]
Should be working in upcoming release, please report back if it's still not working.
