### ISSUE TITLE
[BUG] when using the Open internal video layout option volume settings are not restored correct

### ISSUE THREAD

**Issue by n4ppy** [robvdpol/RaceControl#23]
I have 3 windows set up in the racecontrol.layout.json i have "Volume": 0 for two windows and "Volume" : 100 for one.

If i use Open internal they are all opened at 100%
If i close all 3 and open internal again still 100% 
But if i set one window to say 22% and close that as the **last** window the windows set to 0 are at 22% volume when all are opened with open internal.

If i set a non 0% volume for a window and save to the json then it's set to the correct volume when open internal is used.

So seems to only impact windows set to 0% volume picking up the volume of the last closed window

**Comment by robvdpol** [comment]
Does it work if you set 'IsMuted' to 'true' in the layout json?

Anyway I will have a look tonight.

**Comment by n4ppy** [comment]
The is muted trick works :) Volume is 100% but no sound (having two just out of sync makes for some weird phasing sounds :)

So I've got a work around.

PS using version 1.8.2

**Comment by robvdpol** [comment]
Fixed with 834ce795858ea81f6dc73cacef8aacc75d0e74eb
