### ISSUE TITLE
Force Max Resolution/Resolution Selector

### ISSUE THREAD

**Issue by jasonlitka** [robvdpol/RaceControl#230]
I've tried to download the 2021 Russian Grand Prix twice now and I'm getting a 512x288 file, around 2GB.  I checked the web site and there is a 1080p stream available.  This happened a few weeks back too but on the second attempt I ended up with the 1080p file.

Can you add something so that we can manually select the stream before it downloads?

**Comment by frostedpanda** [comment]
I'm having the exact same issue. Tried downloading it 3 times and got the 288p file each time.

**Comment by willwagner602** [comment]
Confirmed same issue with stream on internal viewer, works fine in both MPC and VLC.

**Comment by AresDraco** [comment]
Confirmed, just downloaded Russian Grand PRixx on 512x288

**Comment by m4ha7m4** [comment]
Same issue on multiple computers.  When using internal player or downloading files the video is always on the lowest quality stream, even when selecting a different quality.  MPV, VLC  

Of note, this is ONLY for the Russian Grand Prix "RACE" Sessions.  Practice, qualifying, pre-race, post-race all showed correct quality.  All "Race" session streams from the 2021 Italian Grand Prix were full quality.

Hopefully just a parsing error in Race Control isolated to this Grand Prix

**Comment by robvdpol** [comment]
Strange, it should always pick the highest resolution video stream. I'll look into it.

**Comment by robvdpol** [comment]
I think this has been solved.
