### ISSUE TITLE
[BUG] The type initialized for 'FlyleafLib.Master' threw an exception

### ISSUE THREAD

**Issue by brinkie2004** [robvdpol/RaceControl#234]
Was working fine last race, but now throws an error at startup:
![image](https://user-images.githubusercontent.com/11051677/136528497-c8ddb57a-9b2f-4983-aec3-926cca2c3c96.png)

Reinstall doesn't resolve the issue. Maybe a restart in between will help, but can't test that right now.

**Comment by robvdpol** [comment]
Possibly fixed in upcoming release. Please report back.
