### ISSUE TITLE
[FEATURE] Pre-select video quality

### ISSUE THREAD

**Issue by frenym2021** [robvdpol/RaceControl#237]
Today the video quality defaults to High. It is not possible to change the quality to a lower quality until the video stream has been established. When on a bad upstream connection, like mobile or otherwise shared, the viewer might be unable to connect at High video quality (Internal viewer, but I think it is similar with the VLC/MPV). It would therefore be desireable to either set the video quality requested before the viewer attempts to connect or to make it possible to change video quality as soon as the viewer window has been opened even before the stream has been established.

Another benefit when running mulitple streams at the same time to keep track of both main broadcast, driver track, timing and possible some driver's camera to for example have high quality on the main video while keeping driver tracking and timing at low quality (do not need HD quality on these streams).

**Comment by robvdpol** [comment]
Fixed in upcoming release.
