### ISSUE TITLE
[FEATURE] Media Control Key Shortcuts to Play/Pause/Forward/Back

### ISSUE THREAD

**Issue by pironic** [robvdpol/RaceControl#239]
**Is your feature request related to a problem? Please describe.**
I'm listening to the streams at work and need to pause when a phone call comes in. Switching applications and finding the pause button is cumbersome. 

**Describe the solution you'd like**
My keyboard includes play/pause buttons and it would be great if we could hook into the windows media key shortcuts to listen to those key-presses. 

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by robvdpol** [comment]
Added in upcoming release.

**Comment by pironic** [comment]
That's great news! Thank you Rob! You Rock!
