### ISSUE TITLE
Request - Change default sound device?

### ISSUE THREAD

**Issue by andejx** [robvdpol/RaceControl#24]
Would be nice to be able to change which sound device the internal player sends audio out to.

**Comment by robvdpol** [comment]
Could you please explain the use case a bit? Would this be a global setting that applies to all video player instances or do you want to be able to change it for individual video player instances?

**Comment by andejx** [comment]
A global setting would be enough.
- I have it open while I'm playing a game on another screen. Would be nice to push the audio to my speakers while my game audio goes to my headset default device.
- I occasionally discord stream the race with a friend, and if i could set the audio output to a specific device i could isolate the race control video player audio, instead of it catching all sounds on windows.

**Comment by robvdpol** [comment]
Ok, that makes sense. I should be able to include this in the next release.

**Comment by robvdpol** [comment]
https://github.com/robvdpol/RaceControl/commit/9d7d1aeacfb20178130c2edcba4744c9f75309c3

Still need to do some work on the GUI.

**Comment by robvdpol** [comment]
https://github.com/robvdpol/RaceControl/commit/63b7d8719484349d3fd9e31712f2f349c17dd575
https://github.com/robvdpol/RaceControl/commit/b75584d56f4da1f101bcca9067a392b10912a9f3
https://github.com/robvdpol/RaceControl/commit/5e9214f88daeeb6c20210d5896ebfaa256970086

Will be available in the coming release this week.

**Comment by andejx** [comment]
hey mate hope everything's ok. Did this release get delayed?

**Comment by robvdpol** [comment]
Yeah, sorry, I wasn't feeling well for a while so I didn't spend much time on the project. Was also having some issues with the auto hiding of the new menu bar in the video player, and I didn't want to release it when it's not working perfectly. Will try to fix it this week. But the season is over now anyway, so probably not much interest in new releases for a while :)

**Comment by andejx** [comment]
yeah all good 👍 thanks

**Comment by Coasternaut** [comment]
> Could you please explain the use case a bit? Would this be a global setting that applies to all video player instances or do you want to be able to change it for individual video player instances?

I would want this on a per-player instance so I could route each stream into different Voicemeeter channels, but I understand that it's a niche use-case. I feel like a left/right audio slider for each player could also be a simpler feature so you could listen to commentators in one ear and driver radio in the other.

**Comment by robvdpol** [comment]
Current implementation is per-player and is also saved in the layout :)

**Comment by robvdpol** [comment]
Version 2.0 released.
