### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by flipjj** [robvdpol/RaceControl#247]
Similar to https://github.com/robvdpol/RaceControl/issues/236, but when you correct the audio to 1/7 (onboard audio) from 2/7 (world feed) with the MPV sync on, the stream goes to 5.00 sync speed and freeze, never to recover

**To Reproduce**
1. Go to any live session with MPV sync on
2. Play stream any onboard
3. Press button play, change audio to 1/7 from 2/8

It worked perfectly until a couple of races ago. 

**Screenshots**
![20211022 132137](https://user-images.githubusercontent.com/53481674/138489660-5778073f-bacf-497c-92d2-4bf49f55bdf3.png)
![20211022 132156](https://user-images.githubusercontent.com/53481674/138489666-c86f5585-dc24-4c9b-976b-89692b6a3386.png)
![20211022 132204](https://user-images.githubusercontent.com/53481674/138489668-a38b4aa3-ea92-456c-9fea-fd37792bf375.png)

**Desktop (please complete the following information):**
 - Windows 10 11H1
 - 53 bit
 - Version 2.4.1 (was present in the earlier version)

**F1TV account**
- Pro
- Brazil
- Using VPN or proxy? No

Race Control is a treasure, and hopefully you can fix it. Thank you for your hard work in creating and maintaining it.
You are a star.

**Comment by robvdpol** [comment]
Since #236 has been fixed, this might be fixed as well. Please try once the new release is out.
