### ISSUE TITLE
[BUG] Changing quality ferezes and its impossible to do it 

### ISSUE THREAD

**Issue by loord617** [robvdpol/RaceControl#248]
I've been having this problem fast 2 months. When i ty to switch quality of the stream it freezes then crashes its impossible to change the quality.  I have 2.4.1 version but it also crashed before

**Comment by robvdpol** [comment]
Probably fixed in upcoming release, please report back if you still get the error.

**Comment by heinserparedes** [comment]
just tried the new release 2.5.0 pre selected potato and the video started stuck ! none of the 3 windows opened played! and  trying to click on play does nothing.
