### ISSUE TITLE
Easy layouts for multiple streams [FEATURE]

### ISSUE THREAD

**Issue by sercast** [robvdpol/RaceControl#25]
Resizing and organizing more than 4 streams is difficult and time consuming.

Would it be possible to have preset window sizes and/or layouts that would accommodate more than 4 windows?

We could have a size that would fit 3x3 windows, one that would fit 5 (3x3 sized windows) and 1 larger window in the remaining space (that takes the space of 4 3x3 windows). Or perhaps just a way to autosnap when resizing the windows (1/4 width, 1/2, 3/4 etc).

Example of a nice layout with more than 4 equally sized windows:
![image](https://user-images.githubusercontent.com/25207936/99319883-f857a700-282f-11eb-9160-855df5dc2e5b.png)

**Comment by robvdpol** [comment]
Will look into it.

**Comment by robvdpol** [comment]
I added shortcuts F1 through F9 to position a window in a 3x3 layout (F1 = top left, F2 = top center, F3 = top right, etc.). Hope this helps.

https://github.com/robvdpol/RaceControl/commit/aa805e8e178a5edf1a3fbd15b9e037034a2b89bd
