### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Trevorrm16** [robvdpol/RaceControl#251]
**Describe the bug**
I tried to open Race Control and got stuck at the login screen. Waited for a bit, then an error said "Operation Timed Out". Tried manually typing my username and password in. Internet's fine, updated from 2.4.0 to 2.4.1 thinking that would work, it didn't. Kinda sucks as the race is just about to start.

**To Reproduce**
1. Open the app
2. Try to log in

**Expected behavior**
To be able to log in and use Race Control normally

**Screenshots**
Didn't take any sorry. It's just an error message

**Desktop (please complete the following information):**
 - Windows 10 Home Version	10.0.19042 Build 19042
 - 64-Bit
 - 2.4.1

**F1TV account**
- Pro
- United States
- No VPN or proxy

**Comment by roniel06** [comment]
@Trevorrm16  I just logged in without any problem. Please provide the log files if possible.

**Comment by Trevorrm16** [comment]
Yeah I was able to log in as well just now. Must've been something on my end. Sorry about that.
