### ISSUE TITLE
[BUG] v2.5.0 Stream not playing

### ISSUE THREAD

**Issue by SnowLeopard71** [robvdpol/RaceControl#257]
**Describe the bug**
Just upgraded to new 2.5.0 version this morning and Mexico Fp1 stream is not working.   F1TV site works okay, reverted to version 2.4.0 and stream works perfectly.

**To Reproduce**
1. Upgrade to 2.5.0
2. Play live FP1 Mexico stream and get no sound or video.

**Desktop (please complete the following information):**
 - Windows 10 pro
 - 64-bit
 - Race Control 2.5.0

**F1TV account**
- Subscription type:  Pro
- Country:  Canada
- Using VPN or proxy?  Neither.

**Additional context**
Reverting to version 2.4.0 works.

**Comment by robvdpol** [comment]
I'm pulling the release, something is not working with the live streams. Please revert to version 2.4.1.

**Comment by steffbp** [comment]
VLC player works, just a FYI.

**Comment by gerritjm** [comment]
> I'm pulling the release, something is not working with the live streams. Please revert to version 2.4.1.

Removed 2.5 and reinstalled 2,41. Load Fail remains when trying to cast.

**Comment by heinserparedes** [comment]
> VLC player works, just a FYI.

yes plays with no issues! however does not play on preselected quality!  i selected potato and the videos just start on hd quality!

**Comment by robvdpol** [comment]
The quality presets only work for the internal player (and for MPV in the next release)

**Comment by robvdpol** [comment]
Please try version 2.5.1, should be fixed.
