### ISSUE TITLE
LOAD FAIL 

### ISSUE THREAD

**Issue by gerritjm** [robvdpol/RaceControl#258]
**Describe the bug**
LOAD FAIL message when trying to cast. Internal player doesn't run proper. MPV player works 

**To Reproduce**
1. Go to  live race and try to cast'

**Desktop (please complete the following information):**
 - WIN 10 x64 
 - System type 64 
 - Version 2.5

**F1TV account**
- Subscription type Pro
- Netherlands 
- Using VPN or proxy no

**Additional context**

**Comment by geintje** [comment]
Same here, I updated to latest Racecontrol and have same issue.
Load fail and cast does not happen.
My advice is to roll back to previous release (pretty please)

**Comment by gerritjm** [comment]
> Same here, I updated to latest Racecontrol and have same issue. Load fail and cast does not happen. My advice is to roll back to previous release (pretty please)

Removed 2.5 and reinstalled 2.41, casting problem remains.

**Comment by heinserparedes** [comment]
tried playing 3 onboards and a world feed! preselected potato! just loads an stuck image (internal player), tried playing on vlc, however the vlc player does not open the videos in the preselected potato quality! and mpv! also the videos dont play in preselected potato quality.

**Comment by gerritjm** [comment]
Todays log. First part = 2.5, further down the file it's 2.41
[RaceControl.log](https://github.com/robvdpol/RaceControl/files/7488301/RaceControl.log)

**Comment by robvdpol** [comment]
For the casting I didn't change anything in Race Control. They must have changed something again on the F1TV backend, maybe the ApplicationID? This is currently set to B3E81094, is anyone able to figure out if this has changed?

**Comment by robvdpol** [comment]
@bartdevriendt How did you figure out the application ID last time?

**Comment by bartdevriendt** [comment]
I did it by closing chrome/edge completely and then running the browser from instructions found here: https://www.chromium.org/for-testers/enable-logging 
In the logfile you end up with lines containing:  VERBOSE1:cast_message_handler.cc.  If you analyse those I managed to find the correct appid.  

The app id seems to be changed to 233637DE but when changing it in code of race control I get invalid command error now.  So it will need further investigation.

**Comment by bartdevriendt** [comment]
Oops, application id is still B3E81094 according to the log.  Something else seems to have changed...

**Comment by bartdevriendt** [comment]
Seems they now include a JWT token in the request:

[31632:25760:1106/164240.371:VERBOSE1:cast_message_handler.cc(445)] SendCastMessageToSocket: channel_id: 1, message: {source_id: 163621335445129490, destination_id: 06e97b69-ecc3-4eb3-9425-77a6150d6624, namespace: urn:x-cast:com.google.cast.media, payload_utf8: {"autoplay":true,"currentTime":4.377775,"media":{"contentId":"https://ott-video-fer-cf.formula1.com/hls/F1_SUT_1636163488985_1636163982950/index.m3u8?kid=1042&exp=1636299754&ttl=1440&token=M6hbQUkJL2MJlYNphL5T2muWLhUryjwlQm6kH-tVVRw_","contentType":"application/x-mpegURL","customData":{"metadata":{"ascendontoken":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9......jD4","requestChannel":"WEB_HLS"},"options":{"manifestWithCredentials":true,"withCredentials":true}},"streamType":"BUFFERED","tracks":[]},"requestId":8,"sessionId":"06e97b69-ecc3-4eb3-9425-77a6150d6624","type":"LOAD"}}

**Comment by robvdpol** [comment]
@bartdevriendt Thanks for pointing me in the right direction, I think I managed to fix it. At least it's working on my Chromecast now.
