### ISSUE TITLE
When changing language, player hangs

### ISSUE THREAD

**Issue by stfrbrntyu** [robvdpol/RaceControl#259]
**Describe the bug**
When changing the language to an other language the player hangs.

**To Reproduce**
1. Press "watch"
2. change language

**Desktop (please complete the following information):**
 - Windows 10 Pro, 20H2
 - 64bit
 - RC 2.5.1

**F1TV account**
- Pro
- NL
- Using VPN or proxy?  NO

**Comment by robvdpol** [comment]
Yeah I'll release a fix tomorrow.

**Comment by robvdpol** [comment]
Should be fixed in version 2.5.2. Sometimes it takes a while before audio or video resumes playback, so be patient.
