### ISSUE TITLE
[FEATURE] Enable recording on playback videos in internal player

### ISSUE THREAD

**Issue by telelisast** [robvdpol/RaceControl#26]
Currently recording in internal player is possible only for live sessions, it would be nice if it could be done for playbacks as well, similar to VLC which can also do both.

**Comment by robvdpol** [comment]
Replays can already be downloaded entirely using the download-button, is that not sufficient? Do you only want to record a fragment?

**Comment by telelisast** [comment]
It's a convivence thing. Sometimes there's a specific happening on track that's lasting less than a minute, so it's wasteful to download full replay for that. I prefer internal player to vlc, because its responsiveness is much better and because of all the other features specific to f1tv.

**Comment by robvdpol** [comment]
Recording functionality had to be dropped because I removed Streamlink integration. I might re-add it when I figure out how to do it with VLC library. Downloading of full sessions afterwards is still possible.
