### ISSUE TITLE
[FEATURE] Audio Language Naming on Downloads

### ISSUE THREAD

**Issue by Vallesuski** [robvdpol/RaceControl#262]
It would be very nice if the downloaded file already contains audio language name, same as in main window.
English, Spanish, German, etc....

Right now there is no way to know what language are all audios included, you need to listen 1 by 1 to choose yours.

Is this possible?

**Comment by robvdpol** [comment]
@SuRGeoNix What do you think?

**Comment by SuRGeoNix** [comment]
Yes, that might be an issue. When I used ffmpeg to copy streams to the downloaded file it might not saving the metadata (which includes the language) for each audio stream. I will have a look and come back to you.

**Comment by robvdpol** [comment]
Fixed in version 2.5.3.

**Comment by Vallesuski** [comment]
> Fixed in version 2.5.3.

Thank you so much for adding this feature. It's really helpful.
