### ISSUE TITLE
[BUG] screens freeze when using 4 screens (2 x 2 docked)

### ISSUE THREAD

**Issue by erwinvang** [robvdpol/RaceControl#265]
**Describe the bug**
I use the latest version. at the beginning of the race I chose the live race. upon launch I choose pit lane channel, live standings, max on board and Ham on board. 
screens freeze when using 4 screens (2 x 2 docked)

For a random number of minutes all is fine. But than 1 on board freezes (and stays like that for a long time. 

Than if I leave on of the frozen screens as is, after a while, also the other on board freezes. 

I use the same computer as before and I experienced this for the last 2 races now. 

**To Reproduce**
2. Play stream '...'
3. Press button '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows edition and version
 - System type (32 or 64 bit)
 - Version (see title bar)

**F1TV account**
- Subscription type (none, Access, Pro) PRO
- Country:  NL
- Using VPN or proxy? N/A

**Additional context**

**Comment by jpd1968** [comment]
Although I'm only using one stream (World Feed) the freezing of the screen is happening. I've looked in the log for errors but there is none to be found. 
This is what is in the logfiles around the time the screen freezes:
_2021-11-14 19:27:20.0381 INFO Querying live sessions...
2021-11-14 19:28:17.3950 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?contentId=1000004832'...
2021-11-14 19:28:20.1209 INFO Refreshing live sessions...
2021-11-14 19:28:20.1209 INFO Querying live sessions..._

The problem first occured in version 2.5.1 as far as I know.

**Comment by robvdpol** [comment]
I'll probably revert to earlier Flyleaf version until this problem has been fixed.

**Comment by robvdpol** [comment]
Please try version 2.5.3 and report back.

**Comment by erwinvang** [comment]
Hi,

Despite the update it still froze.

Rgds
Erwin

Op do 18 nov. 2021 om 21:33 schreef Rob ***@***.***>
