### ISSUE TITLE
Live session not present/showing in "Live Now" section of the app. 

### ISSUE THREAD

**Issue by rickschwarz** [robvdpol/RaceControl#266]
Live session not present/showing in "Live Now" section of the app. 
No audio message "New Live Event"

**Comment by robvdpol** [comment]
This was on Sunday? I didn't have any problems on Saturday, but didn't use Race Control on Sunday.

I will have to check this Friday.

**Comment by robvdpol** [comment]
I think it's working fine this race weekend?
