### ISSUE TITLE
[BUG]Internal player audio stutters a few minutes in. Then app freezes and crashes completely. (Was also present in previous version?)

### ISSUE THREAD

**Issue by GHDutch** [robvdpol/RaceControl#270]
**Describe the bug**
Opened Internal player layout. (4 streams at the same time, world feed, data, gps and one onboard) After 10 or 15 minutes audio starts stuttering. (like skipping record) When closing the stuttering stream the app freezes and crashes completely. All open players then crash (Or when they don't crash audio keeps stuttering). Was also present in previous version? I noticed the timers on the bottom don't work properly either. Happened multiple times in FP1 already.

**To Reproduce**
1. Go to '...' Open Internal
2. Play stream '...' plays automatically
3. Press button '...' nvt

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows edition and version Win10pro
 - System type (32 or 64 bit) 64
 - Version (see title bar) 

**F1TV account**
- Subscription type (none, Access, Pro) Pro
- Country NL
- Using VPN or proxy? No

**Additional context**

**Comment by SuRGeoNix** [comment]
Hi @GHDutch, your issue seems to be a hardware performance issue. 

Would be possible to provide task manager (performance tab with GPU selected) while this happening?
Can you confirm that it happens only when you have multiple windows opened and not just one?
Can you also tested with other players (mpv, vlc) and see if you have the same problem?
You might also check the Event Viewer -> Windows logs -> Application whether you get a detailed error there.

@robvdpol Users might experience those issues because of Video Acceleration failure. I suspect that could happen because of HEVC codec (might requires license or additional installation or just GPU doesn't support it? have to check). It is possible that F1TV provides more than one video streams with the same resolution but different codec and might be better to choose H264 (more bandwidth less hardware) by default instead of H265 (HEVC) to avoid this kind of issues.

**Comment by GHDutch** [comment]
> Hi @GHDutch, your issue seems to be a hardware performance issue.
> 
> Would be possible to provide task manager (performance tab with GPU selected) while this happening? Can you confirm that it happens only when you have multiple windows opened and not just one? Can you also tested with other players (mpv, vlc) and see if you have the same problem? You might also check the Event Viewer -> Windows logs -> Application whether you get a detailed error there. Can you also try while this happening to ensure that if you use a laptop that it is plugged to the power and open a video on browser (this will make the windows to work with high performance timer and might fix the issue - just let us know if that's the case so we can fix it)
> 
> @robvdpol Users might experience those issues because of Video Acceleration failure. I suspect that could happen because of HEVC codec (might requires license or additional installation or just GPU doesn't support it? have to check). It is possible that F1TV provides more than one video streams with the same resolution but different codec and might be better to choose H264 (more bandwidth less hardware) by default instead of H265 (HEVC) to avoid this kind of issues.
> 
> Should also review thread pool min/max threads and opened handles. As when you open more players you have will have more threads opened. (another possible reason why the timer doesn't refresh properly as mentioned above)
> 
> I also suspect a possible bug in the flyleaf's library with multiple players and windows performance timers TimeBeginPeriod/TimeEndPeriod((1). I came across this one before. I will also do some further testing.

**Comment by GHDutch** [comment]
Provide task manager? How? Live?
I'm not sure if it happens on replays. But I will check that now. It doesn't seem to happen on VLC, but the delay on VLC is significant so it's not really a fix for live sessions. First thing i noticed that in replay mode the timers work perfect. So i think it's not the same. 
I have a gtx3070 So not sure if it's supported. Would be surprised if not.

**Comment by GHDutch** [comment]
So far, in replay not any issues... Performance manager screenshot here:
https://ibb.co/nknKfhK

**Comment by GHDutch** [comment]
Checked the log. All is info except:
2021-11-19 23:39:09.6712 WARN Could not find MPC-HC installation.

**Comment by SuRGeoNix** [comment]
@GHDutch GPU it does not seem to be the problem at all. So the issue is happening probably only on live streams and when you use multiple windows, right? The audio shutters but the video continues without issues? I also read that you had different behavior (no crash to other players) with previous version, which one was the previous version that you were using?

**Comment by GHDutch** [comment]
Version on bug submission: 2.53, previous version I don't know. I updated it previous weekend.  No when audio starts stuttering, image freezes as well. But other players continue. Sometimes i can close the stuttering/frozen stream, and restart (this happened multiple times last race) And yesterday it crashed the whole app at least twice...  So since 2.53 it seems a bit different.

**Comment by SuRGeoNix** [comment]
@GHDutch OK, capture a task manager screenshot during the freeze if possible and we will investigate it

**Comment by GHDutch** [comment]
> @GHDutch OK, capture a task manager screenshot during the freeze if possible and we will investigate it

First crash occured within minutes of stream starting

https://i.postimg.cc/DZ7zs0Qp/Untitled.png

**Comment by GHDutch** [comment]
Another crash occured another few minutes after restarting. Logging seems to be continuing when audio is stuttering and image is frozen. Nog logs that give away anything. 

https://ibb.co/ZW0nkCw

**Comment by SuRGeoNix** [comment]
@GHDutch Just cloned RC and it seems that I'm able to reproduce it and debug it, hopefully will find it soon

**Comment by GHDutch** [comment]
Good to hear. Good job. I used MPV for the remainder of the session without any issues.

**Comment by SuRGeoNix** [comment]
@robvdpol Those important [lines](https://github.com/robvdpol/RaceControl/commit/7da67dbc17569e05885ff7f734f15e2886ba39a8#diff-6d3e02a29ce6145bb86c76c1b01d6c9865f9fe63a4df31f9d4101ed55eba8c6bL221) have been removed during Flyleaf's integration from 2.4.X to 2.5.X which are now causing a critical null reference exception which causes TimeBegin/EndPeriod to de-sync and not initialize the decoder properly.

I have also notice in case of multiple windows as the bandwidth increases you might want to increase also the read timeout to prevent the demuxer from stopping (Config.Demuxer.ReadTimeout currently is default 10 seconds)

From my side I might force TimeBeginPeriod(1) once static for the whole library to ensure that nobody will touch it

**Comment by robvdpol** [comment]
Please try version 2.5.4 and report back.

**Comment by GHDutch** [comment]
> Please try version 2.5.4 and report back.

Tried again with 4 internal players. Live feed, driver tracker, data channel and car33 Verstappen onboard. 
First observations: 

1. Timer is still frozen. It's shows the time when the stream was started. 
2. Moments after opening, i cannot resize the 4th internal player anymore. 
3. Changing audio output device while streams are on works well now. Thank you.
4. 15mins in. All seems stable. Will close this when I finish the race without crashing. Thanks everyone!

**Comment by SuRGeoNix** [comment]
@GHDutch Live stream timers are implemented different. Let say a live stream provides you with last 30 minutes of the stream. You will have 0 to 30 minutes duration and you will be for example at 29minute always as it is live. I guess that's the case for 1.

**Comment by GHDutch** [comment]
Made it through the race without crashes. Well done guys! Thanks again.
