### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DrMurgz** [robvdpol/RaceControl#272]
**Describe the bug**
While watching and also when recording from the internal player, the app crashes either midway or as mostly at the end of the playback or live stream.

**To Reproduce**
1. Go to Watch with internal player.
2. Play stream.
3. Press record button. 
4. Continue watching.
5. It crashes after a while or at the end.

**Expected behavior**
Watch and record without the app crashing and the save file being in a playable format.

**Screenshots**
Not available.

**Desktop (please complete the following information):**
 - Windows edition: Windows 10 Pro.
 - System type: 64 bit
 - Version: 21H1

**F1TV account**
- Subscription type: Pro.
- Country: Kenya, Africa.
- Using VPN or proxy? No.

**Additional context**

**Comment by robvdpol** [comment]
Please try version 2.5.4 and report back.

**Comment by robvdpol** [comment]
Should be fixed in 2.5.5
