### ISSUE TITLE
Crash on Download with 2.5.1+

### ISSUE THREAD

**Issue by jasonlitka** [robvdpol/RaceControl#273]
All versions starting with 2.5.1 crash during downloads for me.  Could be at 2%, could be at 20%, but none will finish.  If I uninstall and go back to 2.5.0 then everything is fine.  I see the following three error in Windows Event Viewer (with RC 2.5.3):

-----
Application: RaceControl.exe
CoreCLR Version: 5.0.1221.52207
.NET Version: 5.0.12
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Collections.Generic.KeyNotFoundException: The given key '2' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at FlyleafLib.MediaFramework.MediaDemuxer.Demuxer.UpdateCurTime(Boolean useLastPts)
   at FlyleafLib.MediaFramework.MediaDemuxer.Demuxer.RunInternal()
   at FlyleafLib.MediaFramework.RunThreadBase.Run()
   at FlyleafLib.MediaFramework.RunThreadBase.<Start>b__29_0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ThreadHelper.ThreadStart()
-----

-----
Application: RaceControl.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code e0434352, exception address 00007FFF27A6466C
-----

-----
Faulting application name: RaceControl.exe, version: 2.5.3.0, time stamp: 0x614cbf2c
Faulting module name: KERNELBASE.dll, version: 10.0.22000.318, time stamp: 0x095a2f2a
Exception code: 0xe0434352
Fault offset: 0x000000000004466c
Faulting process id: 0x493c
Faulting application start time: 0x01d7de0ad090307d
Faulting application path: C:\Program Files\Race Control\RaceControl.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 0b8b491d-a132-467b-97cd-00510de85515
Faulting package full name: 
Faulting package-relative application ID: 
-----

**Comment by Vallesuski** [comment]
Hi Guys, sadly I have to say downloads are not working again on newest version 2.5.3
These are my logs -->

Log #1

```
Application: RaceControl.exe
CoreCLR Version: 5.0.1221.52207
.NET Version: 5.0.12
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Collections.Generic.KeyNotFoundException: The given key '7' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at FlyleafLib.MediaFramework.MediaDemuxer.Demuxer.UpdateCurTime(Boolean useLastPts)
   at FlyleafLib.MediaFramework.MediaDemuxer.Demuxer.RunInternal()
   at FlyleafLib.MediaFramework.RunThreadBase.Run()
   at FlyleafLib.MediaFramework.RunThreadBase.<Start>b__29_0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ThreadHelper.ThreadStart()
```

Log #2
```

Faulting application name: RaceControl.exe, version: 2.5.3.0, time stamp: 0x614cbf2c
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1348, time stamp: 0x76fcd692
Exception code: 0xe0434352
Fault offset: 0x0000000000034f69
Faulting process id: 0x2f18
Faulting application start time: 0x01d7de210a811b9b
Faulting application path: C:\Race Control 2.5.3\RaceControl.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 2357dc97-1815-48c3-ac95-951d09fde8ba
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by SuRGeoNix** [comment]
That weird error message again. Can you confirm that it is happening only on live streams?

**Comment by robvdpol** [comment]
@SuRGeoNix downloading is disabled for live streams.

**Comment by SuRGeoNix** [comment]
@robvdpol Why? In my custom version it downloads fine

**Comment by SuRGeoNix** [comment]
@robvdpol How is this possible that 2.5.0 was working for this one?

**Comment by robvdpol** [comment]
I guess I can enable downloads for live broadcasts as well, but it's kind of weird because you would download the broadcast from the current time and not from the beginning, right?

For downloading, nothing changed between 2.5.0 and 2.5.1. Maybe it was working in 2.4.1? Since that was using older Flyleaf version.

**Comment by SuRGeoNix** [comment]
You could seek(0) before start downloading if you want from the beginning.

@jasonlitka should verify that as I am not able to reproduce it generally.

**Comment by robvdpol** [comment]
Yeah it's strange, I can't reproduce it either. I just successfully downloaded a full broadcast.

**Comment by SuRGeoNix** [comment]
Hm.... maybe the read timeout

**Comment by jasonlitka** [comment]
The download issue definitely started for me on 2.5.1 and is still there on 2.5.3. As soon as I uninstall and then install 2.5.0 the downloads complete with no issues.

The release notes for 2.5.1 say FlyLeaf was upgraded.

@SuRGeoNix not sure what you mean by seek(0). I’m just clicking the download button after picking the race and event. Not trying to download a live stream or download while playing.

If there’s a download button within the player I can try that in a couple hours. I’m not at home at the moment.

**Comment by SuRGeoNix** [comment]
@jasonlitka They seek(0) it was for @robvdpol not for you! no worries!

@robvdpol This is very strange if it happens in 2.5.0 and not in 2.5.1

**Comment by Vallesuski** [comment]
I don't see version 2.5.0 in the list of releases, not sure how @jasonlitka is able to grab that version.
If I use version 2.4.1 downloads works great, no problem at all.

Starting from 2.5.1 is when we have the problem.

**Comment by robvdpol** [comment]
You're right, I remember now, 2.5.0 was pulled because of some critical issues.

**Comment by SuRGeoNix** [comment]
@Vallesuski Yes probably @jasonlitka made a mistake there. Would you be able to do some testing if I prepare a .dll to replace so we can identify it?

**Comment by robvdpol** [comment]
> @robvdpol is it possible that the following line changes the flyleaf's lists?
> 
> ```
> var videoStream = videoStreams.GetVideoStreamForQuality(_settings.DefaultVideoQuality) ?? videoStreams.OrderByDescending(s => s.Height).ThenByDescending(s => s.Width).ThenByDescending(s => s.Fps).First();
> ```

Not sure what you mean? Which list does it change?

**Comment by SuRGeoNix** [comment]
@robvdpol You do 

```
var videoStreams = _downloader.DecCtx.VideoDemuxer.VideoStreams;
```

No copy but reference

**Comment by robvdpol** [comment]
@SuRGeoNix That code is fine, it doesn't change your list.

**Comment by SuRGeoNix** [comment]
@Vallesuski @jasonlitka It would help if you patch 2.5.3 with this FlyleafLib.dll which will produce a FlyleafLog.txt file after crashing. First make sure if the download finishes successfully and in any case you send us here the log file.

**Comment by jasonlitka** [comment]
I overwrote the original DLL with that one but I'm not getting a log file after the crash.  I thought it might be because you can't write to Program Files unless you're an admin so I tried again with Run as Administrator and still no log after the crash.  Race Control just blinks out of existence.

Maybe related, I tried the watch button and about 20% of the time it does the same thing when playback starts.  The whole app just closes.  I only get two errors in the event log though so maybe it's not the exact same thing.  The one with the stack trace is missing.

That said, as I wrote this and was about to submit, I saw you released 2.5.4.  Same thing happens with that one.

**Comment by jasonlitka** [comment]
Not sure if it matters, but the computer I've been using is running Windows 11.  It's a Dell XPS 13 9310 (i7-1165G7, 32GB RAM) and it's connected via WiFi.  I tried a desktop (Windows 11, Ryzen 9 5950x, 64GB) which was wired and while it seems more stable, I managed to snag Qatar Qualifying, when I tried to download P3 it crashed again at about 40%.

**Comment by SuRGeoNix** [comment]
@robvdpol Can you try the specific video for download to see if you can reproduce it?

**Comment by jasonlitka** [comment]
Maybe it’s a Windows 11 thing. I’ve got a Server 2019 VM I use for testing and it’s working well. 4 downloads in a row and no crashes. Slow though, probably more a matter of resources. 2 vCPU & 8GB.  I’ll test a few more downloads on the VM later.

**Comment by Vallesuski** [comment]
If you want me to test anything please let me know. I'm currently on 2.4.1

**Comment by Vallesuski** [comment]
I just noticed 2.5.4 enabling Live downloads.... It means we can download Live streaming including all languages or just the one is currently selected? (I would prefer having all audios included)

**Comment by robvdpol** [comment]
Downloads will have all languages.

**Comment by jasonlitka** [comment]
I'm up to 12 successful downloads on the WS2019 VM.  I remoted into another W11 machine I've got in my office (i9-11900KB, 32GB) and that downloaded one file fine but crashed on the next 3 tries in a row.

That's a totally different bit of hardware, different network gear, and different ISP.  This feels like Windows 11 is somehow to blame.

**Comment by SuRGeoNix** [comment]
@Vallesuski mention the same issue in Win10 as well. So, I don't think it's an OS issue but more likely a hardware or .NET 5 version

**Comment by SuRGeoNix** [comment]
Guys, I think that I've finally found (more likely understand) and [fixed](https://github.com/SuRGeoNix/Flyleaf/commit/1540ee9f8512b73f388d93d2ecb37cd60fa4055c) the issue for this one even I was not able to reproduce it. You can download the patch from [here](https://drive.google.com/file/d/13KBWrxsSwzQcs5MZlC-56scRlqpQXAQ7/view?usp=sharing) or wait for the next RC version to try it.

**Comment by tinchox1717** [comment]
i cant watch or download anything.

i get Request resource doesnt contain a valid shceme for an empty client base URL

what im doing wrong?

https://i.imgur.com/L38mplh.png

**Comment by SuRGeoNix** [comment]
@tinchox1717 This is a different issue and probably 'client side' meaning yours. If not then it RC's issue. But first check the file and network access (run as administrator and check your antivirus / firewall and internet connection)

**Comment by Jochem2500** [comment]
> Guys, I think that I've finally found (more likely understand) and [fixed](https://github.com/SuRGeoNix/Flyleaf/commit/1540ee9f8512b73f388d93d2ecb37cd60fa4055c) the issue for this one even I was not able to reproduce it. You can download the patch from [here](https://drive.google.com/file/d/13KBWrxsSwzQcs5MZlC-56scRlqpQXAQ7/view?usp=sharing) or wait for the next RC version to try it.

I had the exact same issue as you, and your patch fixed it for me. Thanks!

**Comment by jasonlitka** [comment]
Ok, so good news/bad news.  Good news is that with your new DLL Race Control no longer crashes.  Bad news is that instead, the files just randomly go to 100% and stop downloading, probably when it would have crashed with the original DLL.

**Comment by SuRGeoNix** [comment]
@jasonlitka It seems like a network issue / read time out, possible firewall issue as well. You can verify this by checking the task manager (detailed) while downloading and check the bandwidth speed that RC uses. Do you still have issues also with playback?

**Comment by jasonlitka** [comment]
I agree it sounds like a network issue, but I'm not sure how it could be.  I'm testing with two totally different computers in two different locations, my home, Verizon FIOS 1G/1G with OPNSense, and my office, Zayo 10G/10G with Fortigate. WS2019 works fine, W11 does not.

The download speed from Race Control isn't great, but it hovers between 20-40Mbps (Turkish GP P1).  If I try downloading 4 files simultaneously I get an aggregate 60-80Mbps (Turkish GP P1-Q).

When I get a partial file it is playable, up until the point it stopped downloading, that is.

I just tried playback of Saudi Arabia P2 and about 6 minutes in Race Control just closed on me, Event Viewer says Unhandled Exception.

```
Application: RaceControl.exe
CoreCLR Version: 5.0.1221.52207
.NET Version: 5.0.12
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFC944C2B72
```

```
Faulting application name: RaceControl.exe, version: 2.5.4.0, time stamp: 0x61732c02
Faulting module name: igd10iumd64.dll, version: 30.0.100.9864, time stamp: 0x611ff70e
Exception code: 0xc0000005
Fault offset: 0x0000000000152b72
Faulting process id: 0x4788
Faulting application start time: 0x01d7e9025b0b6ea9
Faulting application path: C:\Program Files\Race Control\RaceControl.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_9728e7b2c25d83cc\igd10iumd64.dll
Report Id: 6339ce18-ede3-451a-aa71-d2c662778a8e
Faulting package full name: 
Faulting package-relative application ID: 
```

All of my Windows 11 systems are upgrades from Windows 10.  I'm going to blow one out on Sunday and do a clean install of W11 and see if that makes a difference.

**Comment by SuRGeoNix** [comment]
@jasonlitka Before re-install the whole OS you might look just for this specific error. It seems that some windows updates created a similar [issue here](https://docs.microsoft.com/en-us/answers/questions/569341/office-2019-apps-crashing-after-various-updates.html) that might help you.

Might this issue was also happening to others and RC was crashing.

**Comment by robvdpol** [comment]
Please try version 2.5.5
