### ISSUE TITLE
How to use the Save and Import layout functionality

### ISSUE THREAD

**Issue by evkrieken** [robvdpol/RaceControl#277]
Hi, maybe this question doesn't belong here but I couldn't find another source of information on RaceControl. If I am wrong please inform me on where I can find more info or sollution
I am just starting with the use of RaceControl, so cut me some slack When I use Racecontrol I select year, location,, upcoming activity and than choose 4 channels which I configure in a 2x2 layout with 2 of them with a resizeable window. That works great. After I found my perfect configuration I pushed the button Save layout. The following use of RaceControl I want to use the same setup and click on Import Layout. In the folder C:\Users\evkrieken\AppData\Local\RaceControl I find the json file called "RaceControl.layout.json". In the same folder I also see a file called "RaceControl.settings.json" which I don't import. I would expect the system to automatically open the 4 channels as I used before including the 2 resized channels. But completely nothing happens. 

What am I doing wrong or do I misinterpret this Save - Import layout functionality?

Hope to hear from you and keep up the good work. 
Erik

**Comment by robvdpol** [comment]
You don't need to use Import layout, that's only useful if you have multiple (different) layout files that you want to switch between.

In your case you can simply save the layout (which you've already done) and then click the 'Open internal' button. This will open the selected session in the layout that you saved.
