### ISSUE TITLE
New basic functionality

### ISSUE THREAD

**Issue by evkrieken** [robvdpol/RaceControl#278]
I see lots of Issues, but I think all of them are purely technical oriented not on the provided information / content within the channels. Are you also considering adding new functionality on the current system or do you consider the content of the channels to be pure responsibility of Formula One which you only stream in a user-friendly way?

I am already a long time searching for a program, website, android-app or whatever which provides me information on laptimes. I don't mean the laptime of the last driven lap, but all laptimes per driver, so I can see the trend or so for a single driver, but also can compare laptimes between drivers, so not on 1 single lap but over more laps. That kind of info I would like to see and I think with my many more F1 enthousiasts. I have created a document in which I have detailed a lot on this functionaltiy but would like to know first from you whether you think this is something you might consider to add to RaceControl and in what kind of timeline?

**Comment by robvdpol** [comment]
This is not in scope for this project.
