### ISSUE TITLE
[FEATURE] Ability to change aspect ratio

### ISSUE THREAD

**Issue by ErolTR** [robvdpol/RaceControl#28]
Loving this program! 
With your built-in video player, can you add the option to change aspect ratio?
Currently I use MPV and when I do SHIFT+A I can switch aspect ratios.

Very useful for ultrawide screens as it allows for more screen area to be used, plus the image stretching gets fixed by your brain in a few seconds anyways

Thanks!!

**Comment by robvdpol** [comment]
Will look into it for version 1.9.1.

**Comment by robvdpol** [comment]
Fixed in upcoming release.
