### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LeenVeen** [robvdpol/RaceControl#288]
2..5.4 portable, download mp4 crashes. No errormsg, random progress. 

f.i. 2.3 portable, works but downloads .ts ,
and the LANG is wrong ([DE]German instead  the set [ENG]English

Concerns NON live files. f.i. todays " 2021 Abu Dhabi Grand Prix - World Feed" [Download]
.mp4 crashes. .ts download is oke.

live and play works oke 

cannot find the log.

Win7x64
Pro account

**Comment by robvdpol** [comment]
I will release a fix this week.

**Comment by robvdpol** [comment]
Should be fixed in 2.5.5
