### ISSUE TITLE
Download crash at 8%

### ISSUE THREAD

**Issue by noibla74** [robvdpol/RaceControl#290]
Download a feed leaves the app crashing at 8-9 % completion

**Comment by noibla74** [comment]
clicking the download buttun initiatiates the download of the video feed. However, the download stops around 8-10% and the Race Control app closes. Race Control 2.5.4

**Comment by robvdpol** [comment]
Please check the log file and post relevant entries.

**Comment by robvdpol** [comment]
Never mind, this has already been fixed but not released yet. I will create a new release this week.

**Comment by noibla74** [comment]
Great, how do I get the logs?  would be nice to have a new release before 16 december

**Comment by robvdpol** [comment]
Should be fixed in 2.5.5
