### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by jansuper26** [robvdpol/RaceControl#296]
Sometimes the races are downloaded in FX or in english.

Is there a way to decide which audio track is downloaded?
If not, i would like to see it.

**Comment by C0Nd3Mnd** [comment]
Downloaded videos should contain all available audio tracks. You have to switch to the desired audio track in the video player you're using, in VLC for example:

![image](https://user-images.githubusercontent.com/47672946/147895945-abd63da0-98bb-4674-a453-b61024a0c0ed.png)

Note that many (especially older) videos often only include 1-2 audio languages.
