### ISSUE TITLE
[FEATURE] Always on top toggle for videoplayer

### ISSUE THREAD

**Issue by drikkeau** [robvdpol/RaceControl#3]
When watching + using computer, the videoplayer moves to the background when switching between programs (alt+tab).
Request for an "always on top" toggle within the videoplayer.

**Comment by Tralapo** [comment]
Yes I would like to see this as well.
I like to watch the world feed fullscreen with the onboard channel of one driver on top in the corner.

It is already possible to do this with VLC, but then I'm not able to save and load the layout.

**Comment by robvdpol** [comment]
Done, will be available in the release for this race weekend.

**Comment by Tralapo** [comment]
Works great @robvdpol. Is it possible to switch the always on top and the resizable window buttons around?
I put the driver stream in the top corner, but then it hides most of the buttons, including the resize window one. The always on top one is the only one visible.

I like to resize the window and then disable resizing, so the borders are gone. This is not possible now.

**Comment by robvdpol** [comment]
I'll switch the checkboxes around.

As a workaround you can edit the RaceControl.layout.json file in a text editor and set the ResizeMode to 0 for this channel.

**Comment by Tralapo** [comment]
Thanks! Although the JSON thing works, I'm not able to close the stream then, as the close button is hidden as wel. Switching them will fix that, thanks!

**Comment by robvdpol** [comment]
You can press Escape to close the active video window ;)
