### ISSUE TITLE
[BUG] All races prior to 2018 are unavailable

### ISSUE THREAD

**Issue by Arcegis** [robvdpol/RaceControl#309]
**Describe the bug**
When we click on a year that is inferior to 2018, none of the Race Replays is available in any language

**Expected behavior**
For a given year from 1983 to 2017, all Race Replays should display and be able to be watched.

**Screenshots**
Hereby joined as an example. https://pixheb.ovh/images/1964dbefa13b43bd87704e5a2ef85df7.png

**Desktop (please complete the following information):**
 - Windows 10 Pro, 21H2
 - System type : 64 bits
 - Version 2.5.4

**F1TV account**
- Subscription Type : Pro
- Country : France
- No VPN or Proxy

**Comment by robvdpol** [comment]
F1TV didn't exist before 2018, so there are no events/sessions/channels for those years. You have to look under 'episodes' to see what's available.

**Comment by Arcegis** [comment]
Wow ! Sorry for this post 🙇 I did not look where it was needed. Thank you for the heads-up !
