### ISSUE TITLE
Mac OS version

### ISSUE THREAD

**Issue by Monkeey** [robvdpol/RaceControl#328]
Do we have any chance to see a Mac OS version of RaceControl in the future?
Thanks!

**Comment by Edivad99** [comment]
Probably yes, when using dotnet MAUI

**Comment by robvdpol** [comment]
Even then it will be tricky since Flyleaf depends on DirectX. External media players would probably work.

I'm aware of the demand for a Mac OS version but it's simply not feasible at the moment.
