### ISSUE TITLE
[Q] Did F1TV move to .mp4 streaming from f1prodlive.akamaized.net m3u8?

### ISSUE THREAD

**Issue by PostMalone** [robvdpol/RaceControl#332]
Bahrain testing just started and i immediately noticed that we are no longer getting _f1prodlive.akamaized.net_ M3U8 in Race Control client. 

Is this due to F1TV or RaceControl? It seems like the stream is performing worse than before.

**Comment by robvdpol** [comment]
This is due to F1TV, I can't control this. BTW stream works fine on my side.

**Comment by PostMalone** [comment]
Got it. I thought so.

What i always did is Copy the M3U8 from RC then put it in my VLC and watch it. But now that I'm getting _ott-video-cf.formula1.com_ its no longer as stable as before.

However, watching on Website seems to be fine.

Thank you anyway mate.
