### ISSUE TITLE
keeps asking me to download .NET 5.0 even though already did and installed

### ISSUE THREAD

**Issue by peponovich** [robvdpol/RaceControl#334]
wondering if anyone can help

Keep getting this when I try to run "RaceControl" installer
![image](https://user-images.githubusercontent.com/101339345/157675027-835fd847-9c20-47ba-994a-54437cd6ebb2.png)

Thanks.
P.

**Comment by peponovich** [comment]
is just showing me this:
![image](https://user-images.githubusercontent.com/101339345/157696021-e8ee3ccb-a70d-4cf6-a46c-1bfccf27005d.png)

**Comment by robvdpol** [comment]
Please type 'dotnet --info' in a command line prompt and paste the output.

**Comment by robvdpol** [comment]
By the way, the readme already redirects to .NET 6.0 desktop runtime, which is the incorrect one for the current release. The upcoming release will be .NET 6 though.

**Comment by ch8rt** [comment]
Are you saying we should be using 5 and not 6 at this time? I have 6 installed, and I still get this message on startup, only without a specific version being detailed.

**Comment by robvdpol** [comment]
For the latest release (2.6.0) you need .NET 6 desktop runtime: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.3-windows-x64-installer
