### ISSUE TITLE
[BUG] Missing first 10 seconds when downloading Episodes

### ISSUE THREAD

**Issue by JCAMAR0** [robvdpol/RaceControl#339]
Downloaded Tech Talk for Day 1 & 2 of the Bahrain Pre-Season Test, but the video doesn't include the first 10 seconds.  Not a big deal for those specific videos, as the intro is longer than 10 seconds.  I then tried the Day 1 & 2 Wrap videos, and those also cut off the first 10 seconds.  As those videos do not have an intro, I am losing some parts of the conversation.  Tried with MPC-HC and VLC, same issue.  When streaming the episodes from RC though, I can watch the whole video.  Also, the actual tests in the Sessions section are downloading just fine and are not cut off.

Desktop:

- Windows 10 Home
- 64 bit
- Windows Version 21H2
- Race Control Version 2.5.5

F1TV Account:

- Subscription type: Pro
- Country: USA
- Using VPN or proxy: No

Other:

- No MPV paths or parameters
- Default Video: High
- Default Language: English
- Download location is external drive using Windows Storage Spaces RAID 0

**Comment by robvdpol** [comment]
Fixed in next release.

2a5516e6535258d84b9e35e7e0b13a6df51c993a
