### ISSUE TITLE
[FEATURE] Overscan / window size control

### ISSUE THREAD

**Issue by politbureau** [robvdpol/RaceControl#34]
Ability to change overscan for each window (ie increase or decrease the size of each stream within it's window). Especially useful on 16:10 monitors or when you want to maximize the action on a certain feed (like the data tracker, where I like to enlarge just the main data panel and cut off the rest).

**Comment by robvdpol** [comment]
Current release (2.1) has ability to change aspect ratio. Next release will also have zoom in/out functionality. Will that be sufficient?
