### ISSUE TITLE
[BUG] - Internal player stutters every 5 ish seconds. MVP and external Flyleaf are fine.

### ISSUE THREAD

**Issue by IrishTLR** [robvdpol/RaceControl#341]
**Describe the bug**
New to RaceControl. Well done, fantastic program.

I've been testing the program today with 2022 Pre Session Test Day 3. Audio/Video is perfect with the MPV player. However the Internal player [the WATCH button] is spotty at best. Every 5 seconds or so, the audio and video pauses for a second or two, then resumes automatically. This happens every 5 to 10 seconds indefinitely on all live sessions. This happens on all stream qualities from HIGH to POTATO.
I even also the latest standalone version of Flyleaf [v3.4.7], copied the stream url from RaceControl  and the stream is perfect.

As it works in MVP and Flyleaf, I don't believe it to be a network buffering issue. CPU and GPU aren't breaking a sweat at all, either. 

**To Reproduce**
1. Login to RaceControl with F1TV Pro account details.
2. Navigate to the current live stream.
3. Press MVP button for the current World Feed and watch for a while. No problems. 
4. Close MVP player
5. Press WATCH button for the current World Feed and watch for a while. Video and Audio stalls for a second or two every 5 or 10 seconds.

**Expected behavior**
Internal player should work normally with no stuttering.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows edition and version : Windows 10 Pro
 - System type (32 or 64 bit) : 64bit
 - Version (see title bar) : 2.5.5
 - CPU : Intel i9 9900K
 - GPU : nVidia RTX 2080
 - RAM : 32GB

**F1TV account**
- Subscription type (none, Access, Pro) : Pro
- Country : USA
- Using VPN or proxy? : Proton VPN Visionary "fastest" server with about 20% load

**Additional context**

**Comment by ForthtuN** [comment]
Seems my comment disappeared, however also having the same problems. Sound stutters, tested with different samplingrates to no help.

**Comment by robvdpol** [comment]
I'll release a new version which has the latest version of Flyleaf tonight. Please report back if the issue persists.

**Comment by ForthtuN** [comment]
> I'll release a new version which has the latest version of Flyleaf tonight. Please report back if the issue persists.

Wooohooo it seems like its working now, tested for a little while now and no stutter yet, whereas it was almost instantly after starting it before :)

So for me atleast, its fixed!

**Comment by IrishTLR** [comment]
Problem persists for me even after uninstall and re-install. However, seeing as it's resolved for @ForthtuN, I'll assume that's it's a problem with my machine and happy to close the bug.
