### ISSUE TITLE
[BUG] Version 2.6.0 not starting

### ISSUE THREAD

**Issue by kleepMan** [robvdpol/RaceControl#345]
**Describe the bug**
- Installed via the installer and clicked the RaceControl icon -> Nothing happens (even the logo doesn't show)
- Tried to run the portable version -> Nothing happens (even the logo doesn't show)

**Additional context**
Not sure if there is something wrong with my PC or not. I can run RaceControl from the Visual Studio and also if I publish it from the Visual Studio the app runs normally.

Edit. Not sure that does it matter but the locally published `RaceControl.exe` file size is a little bit larger than the released portable version. Other files seems to be the same size (didn't check all the files).
![image](https://user-images.githubusercontent.com/45003186/158456536-10130dfe-c082-4097-be60-ebd14b872211.png)

![image](https://user-images.githubusercontent.com/45003186/158454934-0e2b0b12-c938-479f-a1fe-01af70c694d6.png)

**Comment by robvdpol** [comment]
Weird, is there an error in Windows event viewer?

**Comment by kleepMan** [comment]
> Weird, is there an error in Windows event viewer?

Actually the event viewer hangs and it's not working. I'm going to try to install the new version to my another PC tomorrow. I think somebody else would have complained already if this would have been a global bug for everybody. Might be just that my PC is messed up (even though publish via VS is working 😆 )

**Comment by ForthtuN** [comment]
Note that you need to install the latest Net 6 Runtime, linked at the frontpage. It didn't start for me either while the previous versions did, install of Net runtime 6 fixed it. Guess alot of users are going to need to do that hehe

**Comment by kleepMan** [comment]
> Note that you need to install the latest Net 6 Runtime, linked at the frontpage. It didn't start for me either while the previous versions did, install of Net runtime 6 fixed it. Guess alot of users are going to need to do that hehe
> 
> *Oh just to say, it don't know if its this error that appears here, since i didn't get a cmd menu, just that when launching race control nothing happend untill i installed latest runtime 6

Interesting. It really needs the .NET 6.0.3 version. Version 6.0.1 didn't work for me. But it's working now!
