### ISSUE TITLE
blijft me vragen om .NET 6.0 te downloaden

### ISSUE THREAD

**Issue by Walddyk** [robvdpol/RaceControl#348]
**Describe the bug**

**To Reproduce**
2. Play stream '...'
3. Press button '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows edition and version
 - System type (32 or 64 bit)
 - Version (see title bar)

**F1TV account**
- Subscription type (none, Access, Pro)
- Country
- Using VPN or proxy?

**Additional context**
![Schermafbeelding 2022-03-16 174654](https://user-images.githubusercontent.com/101736966/158644258-331a51d7-2231-4d6e-bed3-7fa279a5bba3.png)

**Comment by robvdpol** [comment]
Please type 'dotnet --info' in a command prompt and paste the output here.

**Comment by robvdpol** [comment]
You need to download the .NET 6 desktop runtime: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.3-windows-x64-installer

**Comment by Walddyk** [comment]
Hartelijk dank voor uw snelle reactie , race control werkt weer top

**Comment by hoogends** [comment]
thanks!

Much appreciated
