### ISSUE TITLE
[BUG] Just installed version 2.6 and keeps saying I miss something in the .NET

### ISSUE THREAD

**Issue by cocaras** [robvdpol/RaceControl#349]
Ok so the title says everything, I think.
I already installed the .NET 6 but this message keep opening and I can't use Race Control. Have I missed something?

![imagem](https://user-images.githubusercontent.com/101754427/158696380-2dbd5d0a-6464-4631-85e5-5e9aa29a41cf.png)

**Comment by scns** [comment]
Do you have installed this dotnet (the runtime desktop)


https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.3-windows-x64-installer







Met vriendelijke groet,

Maarten Schmeitz




Verstuurd vanaf mijn iPhone

Op 16 mrt. 2022 om 22:48 heeft cocaras ***@***.***> het volgende geschreven:

﻿

Ok so the title says everything, I think.
I already installed the .NET 6 but this message keep opening and I can't use Race Control. Have I missed something?

[imagem]<https://user-images.githubusercontent.com/101754427/158696380-2dbd5d0a-6464-4631-85e5-5e9aa29a41cf.png>

**Comment by cocaras** [comment]
Problem solved. Thank you.

I had both the .NET 5 and .NET 6 installed and apparently was making that mistake to happen. I uninstalled the .NET 5 and installed again the .NET 6 and now works perfectly.
