### ISSUE TITLE
[BUG] Casting races before 2018

### ISSUE THREAD

**Issue by SamPro910** [robvdpol/RaceControl#35]
When I watch a race BEFORE 2018 (not available through 'Race Seasons') I **can not cast** to my THOMSON (android) TV.

How To Recreate:
1. Click on 'Full Race', and select anything
2. Click Cast
3. Not Connecting.

I have F1 TV Access.

**Comment by robvdpol** [comment]
Probably a VLC bug, will look into it.

**Comment by robvdpol** [comment]
I just implemented native Chromecast functionality instead of using the VLC proxy function, so this should be fixed in the next release (I tested it and it works).

b3164c5a62999edad304d07cadcb553f82937022
