### ISSUE TITLE
[BUG] Incorrect .NET 6.0 download link

### ISSUE THREAD

**Issue by ch8rt** [robvdpol/RaceControl#350]
The link in both the installation instructions in the readme and the alert box upon opening the app points to .NET core, rather than Desktop, which is required. (I assume core is not?)

**Comment by robvdpol** [comment]
The link points to the .NET 6 download page, which is fine, you just need to select the correct download. I clarified the readme a bit.

I don't want to give a direct link because it will have to be updated for each minor .NET update (we are at version 6.0.3 right now).

**Comment by ch8rt** [comment]
Yep, you're right. My mistake. :D
