### ISSUE TITLE
[BUG] RaceControl does not open anymore after updating to 2.6.0

### ISSUE THREAD

**Issue by Lolihunter1337** [robvdpol/RaceControl#351]
**Describe the bug**
It wont open anymore after updating
**To Reproduce**
Open RaceControl

**Expected behavior**
It should open 

**Screenshots**

![image](https://user-images.githubusercontent.com/17437302/158834072-47b38407-aea7-438c-b9e2-9fff14d80095.png)

**Desktop (please complete the following information):**
 - Windows 11 Pro 22527.100
 - 64 bit

**Comment by JPAhnen** [comment]
Did you install the .NET 6 Runtime? https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime for Desktop apps

**Comment by Lolihunter1337** [comment]
yup
![image](https://user-images.githubusercontent.com/17437302/158870875-ffd3ff42-b902-4adf-b0a6-8a076b902446.png)
