### ISSUE TITLE
[Bug] FileLoadException when starting the application

### ISSUE THREAD

**Issue by RyadaProductions** [robvdpol/RaceControl#352]
After the latest update I am unable to start the application.
There is no message shown to the user or anything.

The following is reported in the eventlog:
```Application: RaceControl.exe
CoreCLR Version: 6.0.121.56705
.NET Version: 6.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException: Could not load file or assembly 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
```

From my experience this is normally caused by an update in the dependencies and having mismatched file dependencies.

Compiling the source and running a fresh build seems to work just fine. It's just the upgrade from the previous version to the one released 3 days ago that seems to do something to cause the error above.

**Comment by csutcliff** [comment]
The error is the WPF dll so part of the framework, make sure you have the latest .net 6.0 "Desktop Runtime" installed, https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.3-windows-x64-installer

**Comment by lucade2210** [comment]
> The error is the WPF dll so part of the framework, make sure you have the latest .net 6.0 "Desktop Runtime" installed, https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.3-windows-x64-installer

I had the same issue. Can confirm that this is the solution.

**Comment by RyadaProductions** [comment]
I had the 6.0.3 preview installed due to personal development. Somehow it didn't resolve the dependency until I uninstalled the preview version and installed the release version as you stated above. Thanks for the help.
