### ISSUE TITLE
[BUG] Missing F1 Live Stream

### ISSUE THREAD

**Issue by DaanSchuitmaker** [robvdpol/RaceControl#354]
**Describe the bug**
In race control i'm able to select the world feed this reflects with the option "International" in the app.

But the App option "F1 Live" i'm missing in Race Control.

Channels added as image
Languages added as image
![Channels](https://user-images.githubusercontent.com/50987977/159005202-937b2d9c-02e4-407e-8f51-b1f07d7b45d8.png)
![Audio-chromecast](https://user-images.githubusercontent.com/50987977/159005206-c19480ce-3e14-4fcc-9c80-a1b39f83e00e.png)
![Audio-worldfeed](https://user-images.githubusercontent.com/50987977/159005208-ba204a27-a51e-40bf-af11-00b91a3e007a.png)
e

**Comment by robvdpol** [comment]
Yep, they renamed the Pitlane Channel to 'F1 LIVE' and the World Feed is now called 'International'. I'll try to implement it today.

**Comment by JohnLBergqvist** [comment]
> Yep, they renamed the Pitlane Channel to 'F1 LIVE' and the World Feed is now called 'International'. I'll try to implement it today.

Yes, they've renamed them in their front-end only. Their API still refers to the International Feed as "WIF" and F1 Live as "Pit Lane".

**Comment by robvdpol** [comment]
Fixed in upcoming release.

**Comment by JohnLBergqvist** [comment]
@robvdpol To be fair, the World Feed always has been technically the "International Feed". "WIF = Wide International Feed". (And NIF = "Narrow International Feed" which has 4:3-safe graphics)
