### ISSUE TITLE
[BUG] asking to install .NET runtime after having installed it. 

### ISSUE THREAD

**Issue by joao44289** [robvdpol/RaceControl#355]
**Describe the bug**
I am on Windows 10 with the latest version of race control installed, and it keeps asking me to install .NET runtime after having installed it. I have tried reinstalling .NET and using the portable and .msi versions of race control. Always the same error. Also tried restarting my computer several times. 

**Desktop (please complete the following information):**
 - Windows edition and version: Windows 10 Home/ 21H2
 - System type (32 or 64 bit): 64bit
 - Version (see title bar):2.6.0

**Comment by robvdpol** [comment]
This has been posted multiple times in the past couple of days. You need the .NET 6 **desktop runtime**. Download it at https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.3-windows-x64-installer
