### ISSUE TITLE
[BUG] Cannot open the RaceControl more than once

### ISSUE THREAD

**Issue by mbrouwer** [robvdpol/RaceControl#356]
Cannot open the RaceControl more than once. It now gives the error : The process cannot access the file 'C:\Users\<username>\AppData\Local\RaceControl\Flyleaf.log' because it is being used by another process.

**To Reproduce**
1. Open RaceControl
2. Create new Virtual Desktop (Win+Alt+D)
3. Open RaceControl

The way I used the application was create multiple Virtual Desktops in Windows, like one for some onboard camera, one for Driver Tracker, etc. I used to do this by opening the application more than once on the different Virtual Desktops and switch between them. Another way to do this is to open the windows and drag them between the Virtual Desktops, but that's a hassle.

It now gives the error:
<img width="279" alt="image" src="https://user-images.githubusercontent.com/933902/159011745-50d30e4d-3ba9-4762-8dd2-0ce795319084.png">

It also doesn't 

I have "fixed" it in my own fork by renaming the flyleaf.log to string flyLeafLogFile = $"{DateTime.Now.ToString("yyyy-MM-dd-HH-mm-ss")}_Flyleaf.log";

But I'm not sure this is the best way to do this.

**Desktop (please complete the following information):**
 - Windows 11 Pro x64
 - Version 2.6.0

**Comment by dhuit90** [comment]
A work around might be using the portable version

**Comment by mbrouwer** [comment]
Good idea, I wanted to try that, unfortunatly, same error... 

It seems to have been introduced in https://github.com/robvdpol/RaceControl/commit/7ead463abb9ca72af243364abf1380c6a8e882fc with the upate to Flyleaf 3.4.7. Commenting ```LogOutput = FolderUtils.GetFlyleafLogFilePath(),``` in App.xaml.cs will fix it but I cant really judge disabling this log file would mean.

**Comment by Ascathon** [comment]
It's not just "more than once" but also just the scenario where you close the main window and open it again to start another stream. Probably exactly the same but just rewriting the issue.

**Comment by IrishTLR** [comment]
When I'm running RaceControl, I only have one instance open but many instances of the player. Just keep clicking the WATCH [or MVP/VLC] button for the desired feeds. Resize players to suit.

**Comment by robvdpol** [comment]
Fixed in upcoming release.
