### ISSUE TITLE
After update and updating dotnet-runtime RC keeps asking for net 6 and refuses to start.

### ISSUE THREAD

**Issue by seth-space** [robvdpol/RaceControl#357]
used the intern link: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.3-windows-x64-installer
tried install, repair to no avail.

**Comment by koshibb** [comment]
I have the same issue.

**Comment by robvdpol** [comment]
Please type 'dotnet --info' in a command prompt and paste the output. Also, please check Windows event viewer for errors.

**Comment by koshibb** [comment]
I was able to fix it by using NetFxRepairTool and reinstall NetCore from scrach.

**Comment by seth-space** [comment]
Microsoft Windows [Version 10.0.19044.1526]
(c) Microsoft Corporation. Alle rechten voorbehouden.

C:\Windows\System32>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.405
 Commit:    63325e1c7d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.405\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  5.0.405 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

C:\Windows\System32>

**Comment by koshibb** [comment]
@seth-space I was able to fix it by using NetFxRepairTool - https://www.microsoft.com/en-us/download/details.aspx?id=30135 
And then reinstalled the correct version of both the desktop and dotnet version of 6.0.3 for x64.

**Comment by robvdpol** [comment]
@seth-space Your output seems to suggest that the .NET 6 Desktop Runtime is not installed.

**Comment by seth-space** [comment]
But it is, several times including repair option. 
Description: A .NET application failed.
Application: RaceControl.exe
Path: C:\Program Files\Race Control\RaceControl.exe
Message: It was not possible to find any compatible framework version
The framework 'Microsoft.WindowsDesktop.App', version '6.0.0' (x64) was not found.
  - The following frameworks were found:
      5.0.14 at [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.WindowsDesktop.App&framework_version=6.0.0&arch=x64&rid=win10-x64

**Comment by robvdpol** [comment]
Apparantly, the install of .NET 6 desktop runtime somehow fails on your machine. The error message is quite clear about that. This is not a Race Control issue.

**Comment by seth-space** [comment]
i uninstalled all dotnet and installed the complete sdk
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.201-windows-x64-installer
seems to solve it.

**Comment by PieterPinpoint** [comment]
Had similar problems. 
Link is for core installer. Problem solved by installing **desktop** version:

https://dotnet.microsoft.com/en-us/download/dotnet/6.0

**Comment by robvdpol** [comment]
Yep the correct link is: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.3-windows-x64-installer

**Comment by seth-space** [comment]
i used the link SC gave so probably change the link in the program?
