### ISSUE TITLE
[BUG] Muted streams in saved layout show up as muted, but produce audio

### ISSUE THREAD

**Issue by Caelarius** [robvdpol/RaceControl#358]
**Describe the bug**
I have 4 streams (world feed, data channel, driver tracker, Max Verstappen boardcam) saved in a layout. When opening a session in the internal player the 4 streams open, and the audio button shows that the streams are muted. However, they put out audio.

Workaround: manually unmute and mute each channel again using the "toggle mute" button twice.

**To Reproduce**
See bug description. 
Noteworthy: the stream layout was saved in RC 2.5.x. Muting worked correctly for these prior versions. This bug started appearing in 2.6.0. Could be a migration issue? Possible relation to the Dutch commentary not being available (yet) this season, but being present in the config files?

**Expected behavior**
Internal player windows are opened, toggle mute button shows up as "muting", no sound is output.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10, 64 bit
 - RC 2.6.0

**F1TV account**
- Subscription type (none, Access, Pro): Pro
- Country: Netherlands
- Using VPN or proxy? No.

**Additional context**

**Comment by robvdpol** [comment]
Can reproduce, will see if I can fix it.

**Comment by robvdpol** [comment]
Fixed in 7c24a5a43eca6a544d0530216ea68645f5cedd8d

**Comment by Caelarius** [comment]
Confirmed fixed. Tyvm.
