### ISSUE TITLE
[BUG] The application doesn't load

### ISSUE THREAD

**Issue by Deco71** [robvdpol/RaceControl#359]
**Describe the bug**
After Updating the Race Control to the latest version, i'm unable to open it.
I've also tried to reinstall it and i've .net 6.0 installed correctly on my PC

**To Reproduce**
1. Try to open the program
2. The RC logo doesn't show up and the app doesn't load

**Expected behavior**
The RC logo should appear and the app should start

**Desktop (please complete the following information):**
 - Windows 10 21H2 19044.1586
 - System type 64 bit
 - Version 2.6.0

**F1TV account**
- Subscription type Pro
- Using VPN or proxy VPN

**Additional context**
The app doesn't load neither with or without the VPN
I've also tried the portable version, but with no luck

**Comment by wiljums** [comment]
I had the same issue, solved installing [this version of .NET 6.0](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.201-windows-x64-installer)

**Comment by reharmsen** [comment]
I thought I had the same issue...
I installed the .NET 6.0.3 Runtime.. after installing the .NET 6.0.3 **Destkop** Runtime.. I got it solved.

**Comment by Spexxel** [comment]
@robvdpol Shouldnt it be possible to publish RaceControl as self-contained? That way no-one needs to install the specific version themself.

**Comment by Deco71** [comment]
@wiljums Thanks a lot for the reply!
I've just tried and now Race Control works again.
I'm closing the issue
