### ISSUE TITLE
[FEATURE] Hotkey Swappable FullScreen Streams

### ISSUE THREAD

**Issue by Possemaster** [robvdpol/RaceControl#362]
I like to view F1 on TV. But I'd like to switch between views like on the F1TV App (Only they have a shitty app so I is not instant and you have to wait for the stream to catch up), Like three streams (Main Race view, Max Verstappen driver Cam and Statistics)
I like to be able to have those streams run at the same time layered on top of each other, but only 1 with audio that is in front. And as soon as I click/use my Hotkey I like to swap to that that set Stream screen and swap Audio (So mute the prior and unmute the focussed one).
So All streams can run in the background (enough bandwidth anyway :D ), so You do not have to buffer and you can swap on the fly.

Above feature would be a Killer one (I tried to make it with some Autohotkey magic but the window names keep changing so it is a bit of a hassle)

**Comment by robvdpol** [comment]
You can kind of do this by using the M button (to toggle mute) and the 1-9 buttons to toggle fullscreen for a specific window.

**Comment by robvdpol** [comment]
You don't even need the mute button, just pressing 1-9 switches fullscreen for a specific window. And when going fullscreen, it mutes the other windows and unmutes the current one.

**Comment by Possemaster** [comment]
That is a lot of help already.
So when for example I have below Layout in JSON. Will the top one always have ID 1?

`{
  "Instances": [
    {
      "Top": 587.0,
      "Left": -4473.0,
      "Width": 3840.0,
      "Height": 2160.0,
      "FullScreen": true,
      "ResizeMode": 0,
      "VideoQuality": 0,
      "Topmost": false,
      "IsMuted": false,
      "Volume": 100,
      "Zoom": 0,
      "AspectRatio": "Keep",
      "AudioDevice": "Default",
      "AudioTrack": "eng",
      "ChannelName": "WIF"
    },
    {
      "Top": 526.0,
      "Left": -4175.0,
      "Width": 3840.0,
      "Height": 2160.0,
      "FullScreen": true,
      "ResizeMode": 0,
      "VideoQuality": 0,
      "Topmost": false,
      "IsMuted": true,
      "Volume": 100,
      "Zoom": 0,
      "AspectRatio": "Keep",
      "AudioDevice": "Default",
      "AudioTrack": "teamradio",
      "ChannelName": "Max Verstappen"
    },
    {
      "Top": 668.0,
      "Left": -4546.0,
      "Width": 3840.0,
      "Height": 2160.0,
      "FullScreen": true,
      "ResizeMode": 0,
      "VideoQuality": 0,
      "Topmost": false,
      "IsMuted": true,
      "Volume": 100,
      "Zoom": 0,
      "AspectRatio": "Keep",
      "AudioDevice": "Default",
      "AudioTrack": "eng",
      "ChannelName": "DATA"
    }
  ]
}`

**Comment by Possemaster** [comment]
I use Open in MPV so it is borderless. 1 and 2 is Contrast change en 3 and 4 Brightness. Do i have to user the Internal preset? Or am I doing something wrong.

**Comment by robvdpol** [comment]
Yes I'm talking about internal player. For MPV I cannot control its behavior.

**Comment by robvdpol** [comment]
> That is a lot of help already. So when for example I have below Layout in JSON. Will the top one always have ID 1?
> 
> `{ "Instances": [ { "Top": 587.0, "Left": -4473.0, "Width": 3840.0, "Height": 2160.0, "FullScreen": true, "ResizeMode": 0, "VideoQuality": 0, "Topmost": false, "IsMuted": false, "Volume": 100, "Zoom": 0, "AspectRatio": "Keep", "AudioDevice": "Default", "AudioTrack": "eng", "ChannelName": "WIF" }, { "Top": 526.0, "Left": -4175.0, "Width": 3840.0, "Height": 2160.0, "FullScreen": true, "ResizeMode": 0, "VideoQuality": 0, "Topmost": false, "IsMuted": true, "Volume": 100, "Zoom": 0, "AspectRatio": "Keep", "AudioDevice": "Default", "AudioTrack": "teamradio", "ChannelName": "Max Verstappen" }, { "Top": 668.0, "Left": -4546.0, "Width": 3840.0, "Height": 2160.0, "FullScreen": true, "ResizeMode": 0, "VideoQuality": 0, "Topmost": false, "IsMuted": true, "Volume": 100, "Zoom": 0, "AspectRatio": "Keep", "AudioDevice": "Default", "AudioTrack": "eng", "ChannelName": "DATA" } ] }`

Yes the first one should always have ID 1.
