### ISSUE TITLE
[FEATURE] Maybe 5.1 sound??

### ISSUE THREAD

**Issue by drag0nst0ne** [robvdpol/RaceControl#366]
I don't know if its already possible to do. But I was watching a replay the other day and I was able to listen the audio in 5,1 channels. Now, after the new updates I'm not getting that.

**Comment by robvdpol** [comment]
F1TV streams only have 2 channel audio, so this is not possible.

**Comment by drag0nst0ne** [comment]
I figured it out, if I use "Speaker Fill" and use MPV player, I get comments on center channel and car sounds on side speakers. Frontal speakers remain the same, outputting both voice and engine sounds.
