### ISSUE TITLE
Do I need F1TV subscription to use this Application??

### ISSUE THREAD

**Issue by MXNOJBE** [robvdpol/RaceControl#367]
**Describe the bug**

**To Reproduce**
2. Play stream '...'
3. Press button '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows edition and version
 - System type (32 or 64 bit)
 - Version (see title bar)

**F1TV account**
- Subscription type (none, Access, Pro)
- Country
- Using VPN or proxy?

**Additional context**

**Comment by scns** [comment]
Yes. You need an subscription.

Met vriendelijke groet,

Maarten Schmeitz




Verstuurd vanaf mijn iPhone

**Comment by MXNOJBE** [comment]
Thanks a lot for assisting



Met vriendelijke groet,




Manoj B E
