### ISSUE TITLE
[BUG] Race Control 2.6.1 does not start due to .NET error (.NET is installed)

### ISSUE THREAD

**Issue by expor** [robvdpol/RaceControl#368]
**Describe the bug**
Race Control does not start on latest version due to .NET error. .NET 6 is installed however! It worked fine on earlier versions.

![image](https://user-images.githubusercontent.com/8403232/159168642-69e2ceee-980e-4fcf-9e8c-24ff9036ae9a.png)

**To Reproduce**
1. Start Race App 2.6.1

**Expected behavior**
I expect installing .NET 6 to fix the issue but it persists (also after reboot).

**Screenshots**
.NET 6 x64/86 is installed:
![image](https://user-images.githubusercontent.com/8403232/159168692-8bc8425f-790e-4dda-b882-6ffedfd78097.png)

**Desktop (please complete the following information):**
 - Windows 10 Pro
 - 64-bit
 - Version 2.6.1

**F1TV account**
- Pro
- Netherlands
- No

**Additional context**
N/A.

**Comment by hvdmeer** [comment]
I had the same problem and solved it by installing .NET runtime 5 
I uninstalled that version due to the message in the latest update

**Comment by expor** [comment]
I have 4.6, 4.8, 5.0 and 6.0 installed but no luck:
![image](https://user-images.githubusercontent.com/8403232/159170283-b8463c86-c67a-4f0a-95d3-dea08da4f844.png)

**Comment by hvdmeer** [comment]
I don't see the desktop runtime it stated
![image](https://user-images.githubusercontent.com/7062995/159171515-9047022d-1d36-4f33-bfca-916efcbfe878.png)

**Comment by expor** [comment]
I see, that fixed it. Was not ware there's a difference between 'Runtime' and 'Desktop Runtime' and I missed there's different options on the .NET6 download page :\

**Comment by FlyingFrisian** [comment]
Well, tough times starting control. Found right software at https ://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.3-windows-x64-installer
