### ISSUE TITLE
[FEATURE] Update to new API

### ISSUE THREAD

**Issue by anthonylavado** [robvdpol/RaceControl#37]
**Is your feature request related to a problem? Please describe.**
As of the end of February 2021, the F1TV website has been redesigned and has a new API that serves video. This new API has all newly added video content, and serves 50fps video when available. The old API currently used should be considered deprecated.

**Describe the solution you'd like**
Update to the new API in order to continue accessing content with the best quality possible.

**Describe alternatives you've considered**
N/A

**Additional context**
It is possible that this will be a larger effort, so I am creating similar issues for all F1TV related repositories. Hopefully there is a way we can all collaborate.

**Comment by robvdpol** [comment]
I've been capturing the website traffic for a bit, but unfortunately it seems that the API has changed significantly (also from a security point of view). I'm afraid this will require a complete rewrite of the API interface. I've also noticed that the Android app (which was updated 2 days ago) is still using the old API.

Please feel free to add any info about the API you may have discovered.

**Comment by robvdpol** [comment]
Some initial findings:

**GET**
https://f1tv.formula1.com/1.0/R/ENG/WEB_HLS/ALL/CONTENT/PLAY?contentId=1000001393
(may require some additional HTTP headers such as correlationid, sessionid, ascendontoken, entitlementtoken and cookie)

returns some JSON that contains a tokenized stream URL.
```
{
	"resultCode": "OK",
	"message": "200",
	"errorDescription": "200",
	"resultObj": {
		"entitlementToken": "eyJhbGciOiJIU....(shortened)....TGRmtYVM",
		"url": "https://f1prodvod.akamaized.net/f1vodprod/625/768/1598810310384/2007_Belgium_RaceHighlights_7min_F1TV-563295813107-master.m3u8?hdnea=st=1615022128~exp=1615022428~acl=/f1vodprod/625/768/1598810310384/*~hmac=f67e55f865134312824e0585ff471ba87d1076d99ce620a72cec8effbf8be0e5",
		"streamType": "HLS"
	},
	"systemTime": 1615022128593
}
```

**Comment by anthonylavado** [comment]
For reference, they're using the Bitmovin Player on the new site, which is how they've gotten Chromecast support "for free". If you look at the [Bitmovin example page](https://bitmovin.com/demos/chromecast), it's the same design for the "Playing on _____" screen.

I'm not sure if their documentation can provide any more hints on the video playback authentication. Knowing what technology the player uses could also be a start towards seeing if anyone else has worked with it before.

**Comment by robvdpol** [comment]
The login form on the website still uses the same old authenticate-URL (https://api.formula1.com/v2/account/subscriber/authenticate/by-password). This returns a subscription token that can be used to obtain an entitlement token:

**GET**
https://f1tv.formula1.com/1.0/R/ENG/WEB_DASH/ALL/USER/ENTITLEMENT
ascendontoken: <subscriptiontoken>

Response:
```
{
	"resultCode": "OK",
	"message": "Entitlement check successful",
	"errorDescription": "200",
	"resultObj": {
		"entitlementToken": "eyJhbGciOiJIUz....(shortened)....AvUogLkrkBQV4"
	},
	"systemTime": 1615037247215
}
```

Not sure yet what the entitlementToken is needed for.

**Comment by robvdpol** [comment]
First attempt at implementing the new API:
79f5e5042a0fca342b8357d419d60c0a14e6b460

To be continued soon.

**Comment by robvdpol** [comment]
Will close this issue now, basic support for new API has been implemented. Still need to focus on race archive and video on demand archive.
