### ISSUE TITLE
Pitlane channel

### ISSUE THREAD

**Issue by rickschwarz** [robvdpol/RaceControl#372]
Is the Pitlane Channel removed.
I dont see the option ?

**Comment by mbrouwer** [comment]
I believe that has been renamed to "F1 Live" in 2.6.1
https://github.com/robvdpol/RaceControl/releases/tag/2.6.1
`Renamed 'World Feed' to 'International' and 'Pit Lane' to 'F1 Live' (2022 season)`

**Comment by rickschwarz** [comment]
Yes i know but it did not show the pitlane channel.
It shows the same as international. Worldfeed

**Comment by rickschwarz** [comment]
Please tell me what to do

**Comment by ForthtuN** [comment]
> Please tell me what to do

As i think they said, it has been removed and replaced.

**Comment by robvdpol** [comment]
> Yes i know but it did not show the pitlane channel. It shows the same as international. Worldfeed

As sais, the PLC from before is now called F1 Live, and it doesn't show the pit lane anymore. It's basically the world feed with a different commentator team.
