### ISSUE TITLE
[BUG] Race Control missing frameworrks for .NET 

### ISSUE THREAD

**Issue by KroontjesPen** [robvdpol/RaceControl#376]
Windows Home 10/64. Version 21H2. Build 19044.1586.
dotnet-runtime-6.0.3-win-x86.exe
dotnet-runtime-6.0.3-win-x64.exe

Also both files with CCleaner deleted and installed again.

**Comment by robvdpol** [comment]
You need the desktop runtime.

Duplicate of issue #355 (and many others).
