### ISSUE TITLE
[FEATURE] Extended Highlights

### ISSUE THREAD

**Issue by Jacques-eMediaIT** [robvdpol/RaceControl#378]
Please add the feature to watch / download the extended highlights (30min) for races.

**Comment by robvdpol** [comment]
It's already there under episodes:

![image](https://user-images.githubusercontent.com/56960828/159423288-d91a8843-c0bd-4995-9314-e62124faa3d8.png)

**Comment by Jacques-eMediaIT** [comment]
Thanks, I missed that - was looking for it under sessions. btw, thanks for the cool and useful app and your time + effort :)

**Comment by Jacques-eMediaIT** [comment]
btw, I've developed a couple of C# WPF apps and I've used this package to easily apply themes: https://mahapps.com/
