### ISSUE TITLE
[BUG] Message "dispatcher processing has been suspended but messages are still being processed"

### ISSUE THREAD

**Issue by harerton** [robvdpol/RaceControl#382]
Hi,

Whenever I try to play something I get the message "dispatcher processing has been suspended but messages are still being processed".

The playback window opens but nothing happens.

F1TVPro, accessing from Brazil.

W10 Pro 64 21H1

Thanks!

**Comment by Spexxel** [comment]
- What race control version are you running?
- Does this happen for every stream/content? (Events/episodes)

**Comment by harerton** [comment]
Hi,

 

Latest version (2.6.1) and it seems to happen with every content. I haven´t tested with live streams yet, as I´ve just started my F1TV Pro subscription.

 

Thanks!

 

De: Khaak ***@***.*** 
Enviada em: quarta-feira, 23 de março de 2022 15:36
Para: robvdpol/RaceControl ***@***.***>
Cc: harerton ***@***.***>; Author ***@***.***>
Assunto: Re: [robvdpol/RaceControl] [BUG] Message "dispatcher processing has been suspended but messages are still being processed" (Issue #382)

 

*	What race control version are you running?
*	Does this happen for every stream/content? (Events/episodes)

**Comment by Spexxel** [comment]
Hi, Thanks for your reply.

Couple of things:
- Are you able to watch F1TV content through the F1TV website?
- Can you provide the RaceControl log file? You can open the file through RaceControl, top left, File -> Open Log File

**Comment by harerton** [comment]
Hi,

Yes, I can watch through the website.

I have attached the log file.
[RaceControl.log](https://github.com/robvdpol/RaceControl/files/8341911/RaceControl.log)

Thanks

**Comment by robvdpol** [comment]
Do you have latest version of .NET 6 Desktop Runtime installed (currently 6.0.3)? Otherwise try reinstalling it.

**Comment by harerton** [comment]
Yes, and I have reinstalled it.

Issue also happens with portable version.

Issue still happens with 2.6.2.

Hopefully, I still can watch content using MPV.

Thanks.

**Comment by harerton** [comment]
Hi,

I updated my video driver and now everything works again.

Thanks!
