### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by arjanhs** [robvdpol/RaceControl#384]
**Describe the bug**
After updating to the latest build I got the error message that i have to install some missing frameworks for .NET, after installing the same message appears again

**Screenshots**
![image](https://user-images.githubusercontent.com/42713716/160088103-a27b6f2e-df4b-41f9-8de4-04ab5518fa50.png)

**Desktop (please complete the following information):**
 - Windows edition and version - WIndows 11 Pro Insiders Preview
 - System type (32 or 64 bit) - 64
 - Version (see title bar) Build 22581

**F1TV account**
- Subscription type (none, Access, Pro) Pro
- Country NL
- Using VPN or proxy? None

**Comment by arjanhs** [comment]
The used URL when hitting the Yes button in the screen leads to another download file then which is added into the description, with the one in the description the app is working.

**Comment by robvdpol** [comment]
Yes, I think it's a limitation of the installer.
