### ISSUE TITLE
[BUG] F1 Live channel no longer picked up by application due to internal name change

### ISSUE THREAD

**Issue by eXhumer** [robvdpol/RaceControl#387]
**Describe the bug**
F1 Live channel is now called "F1 LIVE" internally instead of "PIT LANE". As a result, RaceControl can't pick it up due to hardcoded detection used by RaceControl (https://github.com/robvdpol/RaceControl/blob/master/RaceControl/RaceControl.Common/Constants/ChannelNames.cs#L6)

**To Reproduce**
1. Go to 2022 Season, Saudi Arabia Grand Prix, Practice 1 and try to locate F1 Live channel. It is missing.

**Expected behavior**
F1 Live channel to appear as it does in F1TV website.

**Screenshots**
![image](https://user-images.githubusercontent.com/62310242/160137213-b9bb1008-f8e8-4b2b-b76e-81d749dcbfb8.png)

**Desktop (please complete the following information):**
 - Windows edition and version: Windows 11 Pro
 - System type (32 or 64 bit): 64 bit
 - Version (see title bar): 2.6.1

**F1TV account**
- Subscription type (none, Access, Pro): Pro
- Country: Canada
- Using VPN or proxy: No

**Additional context**

**Comment by robvdpol** [comment]
I will change it to 3.0, was already planning to do so.

**Comment by robvdpol** [comment]
Should be fixed by e047d92599ddf25af7ffb03a755b2877e12db2c7
