### ISSUE TITLE
[BUG] Recording is Not Working

### ISSUE THREAD

**Issue by tankaan** [robvdpol/RaceControl#388]
**Describe the bug**
I tried to record a part of the todays practice session (F2), record button is clickable but it's not functioning.
I also tried to record some older sessions, I couldn't record them aswell.

**Desktop (please complete the following information):**
 - Windows 10
 - 64 bit
 - 21H1

**F1TV account**
- Subscription type (Pro)
- TR
- Using VPN or proxy? NO

**Additional context**

**Comment by robvdpol** [comment]
Seems to be fixed with ec6eac8abf4366c3a98cd9a9ce78326abe9c327f

Don't ask me why...

**Comment by SuRGeoNix** [comment]
@robvdpol That's mine. Requires at least info to properly work for now. I've found the issue and I will fix it soon.
