### ISSUE TITLE
[FEATURE] 'Internal' MPV does not read config files

### ISSUE THREAD

**Issue by RoL0NL** [robvdpol/RaceControl#39]
Not sure if really a bug, but the internal MPV player does not read the config from the 'default' MPV config file location (%AppData%/mpv/mpv.conf).

I would like to change the render mode (vo) from 'gpu' (shaders) to 'direct3d' because my relatively old GPU can not handle more than 1 stream in this default configuration and works fine with the latter. I could use the 'external' MPV option, but then I lose the handy shortkey options.

Is is possible to somehow change the configuration of the internal player?

**Comment by robvdpol** [comment]
What is the name of this setting? I can add it to the Race Control settings so it's passed as a parameter to MPV.

For reference:
https://mpv.io/manual/master/#gpu-renderer-options

**Comment by RoL0NL** [comment]
That would be nice! The option is 'vo' (Video Output) (CLI argument --vo=...)

The available options can be listed by using `mpv --vo=help`:
```
Available video outputs:
  libmpv           render API for libmpv
  gpu               Shader-based GPU Renderer
  direct3d         Direct3D 9 Renderer
  sdl                 SDL 2.0 Renderer
  null                Null video output
  image            Write video frames to image files
  tct                 true-color terminals
```

The default seems to be 'gpu' (shaders), where 'direct3d' rendering reduces gpu load for me.

**Comment by robvdpol** [comment]
I added a setting where you can specify additional MPV parameters, which will be passed to MPV. This setting will be saved to the Race Control settings file, so you only have to specify it once.

5c25f5dc4844bb94784613f3482ddf8ac0d68788

**Comment by RoL0NL** [comment]
Hmm, this seems not to work (release 2.0.1). Parameters that I put in the 'additional MPV parameters'-box seems not to be picked up by the player. If I for example add '--fs' (full screen). the video still does not open in full screen. The external MPV player _does_ open in fulls screen, but this feature was meant to alter the 'internal' MPV player (with the shortkeys), right?

**Comment by robvdpol** [comment]
No, this feature is for the external MPV player. The internal player is based on VLC, not MPV.
