### ISSUE TITLE
[BUG]F1 Live channel is missing from Saudi Arabian Grand Prix

### ISSUE THREAD

**Issue by Dimmidice** [robvdpol/RaceControl#390]
**Describe the bug**

**To Reproduce**
1. Go to 'Saudi Arabian Grand Prix'
2. Play stream 'Practice 1 or Practice 2'
3. Look at channel list
4. See no F1 Live stream.
5. It is available on the official site however. 

**Expected behavior**
To see the F1 live channel same as in the Bahrain Grand Prix

**Screenshots**
![RaceControl_2022-03-25_18-29-37](https://user-images.githubusercontent.com/30963362/160171723-16600104-a65d-4996-9f46-f9dbb8a92434.png)

**Desktop (please complete the following information):**
 - Windows 10 Home
 - System type 64 bit
 - Version : 2.6.1

**F1TV account**
- Subscription type : Pro
- Country : Belgium
- Using VPN or proxy? Nope

**Comment by Mariuss811** [comment]
I got the same Problem.

**Comment by Rhytmick** [comment]
@robvdpol I just wanted to express my thanks, this software is fucking awesome and i really appreciate you working on it/fixing bugs.
