### ISSUE TITLE
Live International Channel not synchronized[BUG]

### ISSUE THREAD

**Issue by TxaEkis** [robvdpol/RaceControl#396]
**Describe the bug**
The International channel while watching Live is 5 to 6 seconds behind all other channels, doesn't matter if i close it and reopen it.

**Expected behavior**
I expected the channel to be synched like it used to be.

**Desktop (please complete the following information):**
 - Windows 10 pro 21H2
 - 64bits
 - RC 2.6.2

**F1TV account**
- Subscription type: Pro
- Country: Mexico
- Using VPN or proxy?: None

**Additional context**
Compared it whitin RaceControl channels and F1 Tv on web browsers.. the gap is massive.

**Comment by robvdpol** [comment]
That's an issue on F1TV platform, not Race Control.
