### ISSUE TITLE
[BUG] • Pit Lane channel still missing

### ISSUE THREAD

**Issue by hangro** [robvdpol/RaceControl#397]
Hallo Rob,

**Describe the bug**
Zie titel: **Pit Lane channel** still missing.

**Desktop (please complete the following information):**
 - Windows 10 Pro 21H2
 - 64 bit
 
**F1TV account**
- Subscription type: Pro
- Country: NL

Dank voor je werk en je fantastische 'Race Control'.

Groet, Hans Groener

**Comment by Spexxel** [comment]
Sinds dit seizoen is er geen pit lane channel meer. In plaats daarvan is er nu "F1 Live"

Ik kwam onderstaande overzicht tegen:
Pitlane channel = F1 Live (F1TV commentators)
Main channel = F1 International (broadcast commentators from Sky UK and other languages)

En de omschrijving van de F1TV website:

> F1 Live is a dedicated channel produced by Formula 1 covering F1 only. Here you will get all the angles with expert commentary (English only) and guests. 
> F1 International is the live race action with selected commentary in your chosen local language. 
> F1 Live / International are not available for F2, F3 and Porsche Super Cup, but these will continue to be broadcast as previous years.

Voor de vorige seizoenen is de pit lane nog wel gewoon beschikbaar. De fix voor de juiste weergave van deze namen zit erin vanaf versie 2.6.1

**Comment by robvdpol** [comment]
As mentioned above, the Pit Lane channel has been replaced by 'F1 Live' for the 2022 season.

**Comment by hangro** [comment]
Dank voor jullie antwoorden. Jammer, maar helaas; niet echt een verbetering...
