### ISSUE TITLE
[BUG] Windows cannot be dragged around

### ISSUE THREAD

**Issue by natpate** [robvdpol/RaceControl#40]
Stream windows are unable to be dragged around by the new menu bar.

Open any stream
Click and drag on the menu bar
Nothing happens

Main Race Control window can be dragged by the menu bar, streams cannot

Windows 10 Pro 64bit V2.0.0

Shouldn't matter but Pro access, US, no VPN

**Comment by robvdpol** [comment]
Works as designed. You're supposed to drag by clicking and holding the actual video, not the menu bar.

The main window actually has a title bar and not a menu bar.

**Comment by natpate** [comment]
I am dumb, that is way better. Thanks for all the work you've done!
