### ISSUE TITLE
[FEATURE] Multiple ChromeCast devices.

### ISSUE THREAD

**Issue by beerse** [robvdpol/RaceControl#401]
`**Is` your feature request related to a problem? Please describe.**
Here in house, there are more ChromeCast devices. it would be nice to adres them all from RaceControl.

**Describe the solution you'd like**
Hence the ability to adres multiple ChromeCast devices. It would be nice if they list with their name in the list of targets.
Maybe aditional: adress all chromecasts at once.

**Describe alternatives you've considered**
My alternatives are using hdmi-cables and adress the schreens as computer-screens.

**Additional context**
For now I donnot care about displays not in perfect sync. The displays are in different rooms.

**Comment by robvdpol** [comment]
You can already do this I think.

When you've started casting to device A, you can select device B from the list and start casting to that device as well (can be a different stream or channel if you want). The stream on device A will keep going.

Or am I missing something?

**Comment by robvdpol** [comment]
Please re-open if I misunderstood the request.

**Comment by beerse** [comment]
It is good to see multiple chrome-cast devices can be used. It was just not at the location where I expected it.

I expected to be able to connect multiple chrome cast devices at the left-down menu, that could show up as targets for video streams, each with their own label.

Or optionally, once multiple chrome-cast devices are connected to the app, the chromecast button next to the video stream shows a sub-menu listing every chromecast device (and optionally 'all chromecasts').
