### ISSUE TITLE
[BUG] "Windowed/Fullscreen" displayed at bottom of internal video player when opening layout

### ISSUE THREAD

**Issue by Peatote** [robvdpol/RaceControl#403]
**Describe the bug**
When opening an internal video player layout, "Windowed" or "Fullscreen" is stuck at the bottom of each internal video player.

**To Reproduce**
1. Open internal video streams.
2. Set video players in desired positions.
3. Click on "Save layout" under the Video player layout section.
4. Click on "Open internal" button under the Video player layout section.

**Expected behavior**
Prior to Version 2.6.2 the "Windowed" or "Fullscreen" text wasn't persistently displayed at the bottom of an internal video player.  

**Screenshots**
![RC](https://user-images.githubusercontent.com/102432639/160253147-ba39e777-b651-44ec-a075-9bda6e5198ec.png)

**Desktop (please complete the following information):**
 - Windows 11 Pro Version 21H2. OS build 22000.56. 
 - System type 64bit
 - Version 2.6.2
 
**F1TV account**
- Subscription type - Pro
- Country - USA
- Using VPN or proxy? No

**Additional context**
- Bug persists when the video player is both manually dragged to a location on the screen, or moved to a location by the arrows, then saving layout.  
- Bug doesn't occur when watching a stream not opened by the video player layout.

**Comment by robvdpol** [comment]
Ah crap, I'll try to fix this tomorrow.

**Comment by Lochtie** [comment]
For me a quick work around was to open the 'windowed' screen in fullscreen mode and then switch back to windowed for each of the 4 streams I had open.

**Comment by robvdpol** [comment]
Fixed in ca747ce58565e06e87b96eddc026e0f15dc68748
