### ISSUE TITLE
[BUG] Internal video player window doesn't return to its original dimensions when exiting full screen mode

### ISSUE THREAD

**Issue by fergalt** [robvdpol/RaceControl#404]
**Describe the bug**
The internal video player window doesn't return to its original dimensions when exiting full screen mode

**To Reproduce**
1. Open four streams in the internal video player
2. Place each stream in each of the four locations using the 2x2 layout function
3. On the Top Right window, expand to full screen using the Full Screen Toggle
4. Once this window is full screen, click the Full Screen Toggle button again, to exit full screen
5. Top Right window is now smaller than it was before being full screened, and requires resizing to return to original layout.

**Expected behavior**
Window should return to its original size and location on exiting full screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/29102967/160258106-40d64aaa-e492-4e09-a4dc-463e05cfe946.png)
![image](https://user-images.githubusercontent.com/29102967/160258112-d5862f93-98df-4bfe-ae13-1ff20e728da8.png)
![image](https://user-images.githubusercontent.com/29102967/160258114-831055b4-8cf7-471d-829b-272da41ff5da.png)

**Desktop (please complete the following information):**
 - Windows edition and version: Microsoft Windows 10 Pro, 10.0.19042 Build 19042
 - System type (32 or 64 bit): 64bit
 - Version (see title bar): 2.6.2

**F1TV account**
- Subscription type (none, Access, Pro): Pro
- Country: 
- Using VPN or proxy?: 

**Additional context**
This also occurs when a window has been placed into fullscreen from a 3x3 layout
Screen resolution: dual 2560x1440 screens. (It is repeatable on both primary and secondary monitors)

**Comment by robvdpol** [comment]
Fixed in 86339acf2715ad9730d028bbf88f7e4e851e4e6f
