### ISSUE TITLE
[BUG] Race Control 2.6.x not starting

### ISSUE THREAD

**Issue by stevenhoekerd** [robvdpol/RaceControl#407]
**Describe the bug**
Any Version of Race control past 2.6.0 does not start on my machine/

**To Reproduce**
Unsure of how to reproduce, no error is given.

**Desktop (please complete the following information):**
Edition	        Windows 10 Pro
Version	        21H2
Installed on	‎12/‎07/‎2021
OS build	        19044.1586
Experience	Windows Feature Experience Pack 120.2212.4170.0

**F1TV account**
F1TV Pro
The Netherlands
No VPN/Proxy

**Additional context**
I have made sure to install the correct .Net version, this did not fix the problem.
Any version before 2.6.0 works just fine.

Let me know if you need any additional info, or if you need me to try some situations to get some data.

**Comment by Sjohn21** [comment]
I had the same issue.
After removing Race Control, .NET 50 Desktop Runtime & .NET 6.0 Desktop Runtime I installed Race Control again.
While starting Race Control obviously requested to install .NET 6.0.3 Desktop Runtime.
After doing that, Race Control worked again.
Hope this helps.

**Comment by stevenhoekerd** [comment]
Welp this one is totally on me, while rereading the install page i realized it specifically states you need the x64 .NET version, where as i installed the x86 version. i assume letting race control download it for you makes it automatically choose the correct version, so that is propably fixed it for you then.

Thanks for the help, it all works now!
