### ISSUE TITLE
[BUG] No access  to race archive (races pre 2018 season) in version 2?

### ISSUE THREAD

**Issue by amjoythis** [robvdpol/RaceControl#41]
**Describe the bug**
In RaceControl 1.8.2, I could access the F1TV archive. In version 2.0, I can not find it. Content pre-2018 seems unavailable. May be it is a bug?

**To Reproduce**
Just launch the software and try to find the race archive.

I am sorry if I am just blind and congratulations for this superb project! The key reason I pay for F1TV.

**Comment by robvdpol** [comment]
Still working on that, the new API is a pain to work with. If you're only interested in the old races I would recommend sticking to the previous release for now.

**Comment by amjoythis** [comment]
Thank you! I only became aware of the impact of the background changes now.

**Comment by robvdpol** [comment]
Race archive added.

53c0ee871d118ea4fd016259b179f96f2a86c7bc
