### ISSUE TITLE
[BUG] missing .NET frameworks

### ISSUE THREAD

**Issue by MTrintignant** [robvdpol/RaceControl#416]
**Describe the bug**
Having installed the latest version (2.6.3) i receive an error message "To run this application, you must install missing frameworks for .NET. Would you like to download it now?"

I have clicked yes and downloaded and installed the .NET version from the link (Microsoft .NET runtime 6.0.3 x64). This installed correctly, and is shown under Apps.

However, Race Control still shows the error message of missing .NET framework with the link to the same version. Unfortunately, i cannot see if there is something more specific missing for the app to run.

**To Reproduce**
2. Play stream '...'
3. Press button '...'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/103243512/162383677-33c4e097-710b-4c9a-b659-ee0116c86b1f.png)
![image](https://user-images.githubusercontent.com/103243512/162383732-1564a739-7c0c-43d0-906f-064f3a60a3b6.png)

**Desktop (please complete the following information):**
 - Windows edition and version
 - System type (32 or 64 bit)
 - Version (see title bar)

Windows 10 x64 

**F1TV account**
- Subscription type (none, Access, Pro)
- Country
- Using VPN or proxy?

F1TV Pro. working from the web-interface from Germany without VPN

**Additional context**

**Comment by dhuit90** [comment]
You need the desktop framework: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.3-windows-x64-installer

**Comment by MTrintignant** [comment]
Great, that works. Seems quite obvious in hindsight...  At least that was an easy fix, thanks a ton! (now just down to the "forbidden" issue)
