### ISSUE TITLE
Great Job Rob, thanks for the update

### ISSUE THREAD

**Issue by rickschwarz** [robvdpol/RaceControl#418]
Again Rob fixed it !
Save by the bell !
Great job fixung de login issue !

**Comment by foobarinigo** [comment]
Hell. Yes. I was attempting to watch FP3 last night, no joy. Wake up this morning and delicious quali was waiting for breakfast.

**Comment by BoleMNE** [comment]
Is this also a fix for DRM issue for live sessions?

**Comment by JohnBruil** [comment]
Thnx Rob, much appreciated

**Comment by MSBBZBL** [comment]
But I have a small problem with the audio. There are in all streams (german /english) small interruptions every 4-5 seconds with the internal player.

**Comment by Mascot68** [comment]
Without this application I doubt I would keep my F1 TV subscription. Their web interface is that bad. Thanks a ton. :)

**Comment by robvdpol** [comment]
> Is this also a fix for DRM issue for live sessions?

That will take some more time, there's much work to do to make that happen.
