### ISSUE TITLE
New Login Screen just white

### ISSUE THREAD

**Issue by TheButsmuts** [robvdpol/RaceControl#419]
**Describe the bug**
When starting the app a popup appears, with the race control logo in the corner an Login as the title. But only white in the popup

**To Reproduce**
1. download version 2.6.4
2. install it.
3. Open it (with or without administrator rights.)
4. Login popup appears.

**Expected behavior**
I expected a login screen...

**Screenshots**
![image](https://user-images.githubusercontent.com/103340083/162594873-a615a99d-71ed-49aa-8232-5ed8053ee088.png)

**Desktop (please complete the following information):**
 - Windows 10 Pro
 - System type 64 bit)
 - Version 2.6.4

**F1TV account**
- Subscription type Pro
- The Netherlands
- Using VPN or proxy? No

**Comment by nalyu** [comment]
Make sure the [Microsoft Edge WebView2 Runtime](https://go.microsoft.com/fwlink/p/?LinkId=2124703) is installed on your system.

Because I believe that is used to make a f1tv login screen.

**Comment by TheButsmuts** [comment]
yes that does work, thank you.
