### ISSUE TITLE
[BUG]Can't move Windows 

### ISSUE THREAD

**Issue by Pschirki** [robvdpol/RaceControl#42]
**Describe the bug**
Thanks again for your program. I can't move any window to position it at any place of the desktop. Moving them by the arrows beneath instead works. Seems like i'm unable to get a focus on the window. And i must add, i use 2 Monitors.

![image](https://user-images.githubusercontent.com/70758565/111032774-2af46380-840e-11eb-9996-9fe138fda240.png)

Desktop Gerätename	SpassMaschine
Prozessor	Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz   4.00 GHz
Installierter RAM	16,0 GB
Geräte-ID	DFA40D09-D252-4C3F-A708-C596D401AEC7
Produkt-ID	00330-80000-00000-AA371
Systemtyp	64-Bit-Betriebssystem, x64-basierter Prozessor

**F1TV account**
- Subscription type (Pro)
- Country  Germany
- Using VPN or proxy? no

**Additional context**

**Comment by robvdpol** [comment]
Strange, I can not reproduce this. Are you dragging on the actual video and not the menu bar?

**Comment by Pschirki** [comment]
No, on the menu bar.

Am Sa., 13. März 2021 um 15:49 Uhr schrieb Rob ***@***.***>:

**Comment by Pschirki** [comment]
Ok, maybe i had setup something wrong, but i couldn't imagine what.
btw, would that be ok if i share your reddit link on Twitter?

Am Sa., 13. März 2021 um 17:59 Uhr schrieb Jochen Pampus ***@***.***

**Comment by robvdpol** [comment]
You have to drag on the video, not the menu bar.

Yes, sharing is fine of course!
