### ISSUE TITLE
[BUG] Unable to watch in live sessions

### ISSUE THREAD

**Issue by ferros97** [robvdpol/RaceControl#422]
**Describe the bug**
DRM stream problem in live sessions, when i play a stream live, the screen is all blured

**To Reproduce**
1. Play a session live

**Screenshots**
![image](https://user-images.githubusercontent.com/33987104/162606348-27259e3f-70a5-4f53-863e-4707f55447ad.png)
**Desktop (please complete the following information):**
 - Windows 10
 - 64 bit
 - 2.6.4

**F1TV account**
- Pro
- Portugal
- Using VPN or proxy? - No

**Comment by ferros97** [comment]
I don't know if it is the same as #413 if so please close it
Thanks for your work!

**Comment by zierbeek** [comment]
Please read the other issues. This is a known issue #413
