### ISSUE TITLE
[BUG] Video stream grey (Live/newer VoD)

### ISSUE THREAD

**Issue by D3XX3R** [robvdpol/RaceControl#423]
**Describe the bug**
No matter which video player I use, the player always outputs a grey image only. There are sometimes some lines in it but that's pretty much it. Older videos are being shown like before.

**To Reproduce**
1. Login using any account
2. Use any of the play buttons ("MPV", "VLC", "Watch")
3. See a grey screen

**Expected behavior**
Livestream showing the actual video

**Screenshots**
![PNG showing the issue](https://user-images.githubusercontent.com/48421663/162607496-e4392a27-07e5-4cfb-b57a-82dd846f08fb.png)
[WebM showing the issue](https://mindgeek.zendesk.com/attachments/token/lnZ3WSmeceKBY2JJd0tOwKtsU/?name=mpv_7B4vqKyFaz.webm)

**Desktop (please complete the following information):**
 - Windows 11 (21H2, Build 22000.593)
 - 64-bit system
 - Version 2.5.4

**F1TV account**
- Subscription type - F1 TV Pro
- Austria
- With and without using VPN

**Additional context**
Also doesn't work when I copy the link and use it with Mpv.net

**Comment by SelleslaghGianni** [comment]
#413 duplicate. This is a DRM issue.

**Comment by D3XX3R** [comment]
Thank you for bringing this to my attention. 
Will close the issue
