### ISSUE TITLE
[BUG] Login screen empty

### ISSUE THREAD

**Issue by Matthijsy** [robvdpol/RaceControl#424]
**Describe the bug**
I installed the new version of RaceControl 2.6.4, and now the login function does not work. I just get an empty login screen, but cannot do anything (see screenshot). I already tried removing the credentials from the credential manager, and also a complete reinstall of RaceControl.

<img width="1072" alt="Screenshot 2022-04-10 at 12 58 48" src="https://user-images.githubusercontent.com/5302372/162614893-8f7f3d97-20f8-4f88-88f6-af9b430ca1a0.png">

**To Reproduce**
1. Install RaceControl
2. Start RaceControl

**Desktop (please complete the following information):**
 - Windows 10 Home
 - 64-bit
 - Running in a Virtual Machine
 - RaceControl 2.6.4

**F1TV account**
- Pro
- The Netherlands
- No

**Comment by xcaliber93** [comment]
Didi you read the important note?

![image](https://user-images.githubusercontent.com/36753272/162614998-b8a7293c-80bf-4c16-8c01-4a6cd37f7b6d.png)

**Comment by Matthijsy** [comment]
Thanks! I did read the comment, but did forget to install it. That fixed it
