### ISSUE TITLE
[BUG] big blank login screen after program start

### ISSUE THREAD

**Issue by tdemeyer** [robvdpol/RaceControl#425]
**Describe the bug**
Version 2.6.4: after the progam start, I get a big white window  (window title : login), but nothing else happens.

**To Reproduce**
start program..

**Expected behavior**
login screen?

**Screenshots**
<cannot insert or attach>

**Desktop (please complete the following information):**
 - Windows edition and version W10 21H2
 - System type (32 or 64 bit); 64
 - Version (see title bar) 2.6.4

**F1TV account**
- Subscription type (none, Access, Pro): pro
- Country: belgium
- Using VPN or proxy? none

**Additional context**
When going to f1tv.com: I can login with my credentials..

**Comment by gerritjm** [comment]
Follow instructions. 

IMPORTANT NOTE: Make sure to install the Microsoft Edge WebView2 Runtime on your system!

**Comment by robvdpol** [comment]
I added a hint to install the runtime in the login window.

![image](https://user-images.githubusercontent.com/56960828/162619012-f37791a4-c3bd-4153-b381-7197b148f7b9.png)

**Comment by Tanguille** [comment]
I still got the weird DRM visuals when I tried to watch the race live. Watching it after it's over works.
