### ISSUE TITLE
[BUG] Forbidden error trying to login

### ISSUE THREAD

**Issue by dmayan** [robvdpol/RaceControl#435]
Trying to log in I get a FORBIDDEN error.

![image](https://user-images.githubusercontent.com/23533736/164910894-5458e2c2-8870-4316-a027-e7ceb662c845.png)

Windows 11 22598
F1 TV pro account

Can watch normally on Firefox

**Comment by sidewinder94** [comment]
This has been fixed in the newer versions of the app

Duplicate #414

**Comment by Rhytmick** [comment]
im getting a different login issue, never seen this one before. 

![racecontrolpbroken](https://user-images.githubusercontent.com/102380364/164970475-abded6dd-98a7-4716-85bb-69c32a660a1a.PNG)

**Comment by ExtraFarmate** [comment]
This is the old login prompt. Download [the latest release](https://github.com/robvdpol/RaceControl/releases/tag/2.6.4) and try again.

**Comment by dmayan** [comment]
Thanks, the app always remembers me to download the last version. As it is not logging in, it is not doing that.
