### ISSUE TITLE
v2.0 Installer: I have .NET Runtime 5.0.4 x64 installed, but the RaceControl V2 installer keeps prompting me to install 5.0

### ISSUE THREAD

**Issue by mikeev261** [robvdpol/RaceControl#44]
I have 5.0.4 .NET installed, but for some reason the .MSI installer keeps prompting me to install .NET 5.0.

**Comment by rocksonrocks** [comment]
Make sure you install the Desktop Runtime.  I installed the host bundle at first and had the same problem.

**Comment by robvdpol** [comment]
Yes you need to install the 64-bit Desktop Runtime:

https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.4-windows-x64-installer
