### ISSUE TITLE
[BUG] Can't login

### ISSUE THREAD

**Issue by Kdog332** [robvdpol/RaceControl#445]
**Describe the bug**
Installed newest version after dealing with the "Status code forbidden" issue. Now when I open the progran the Login window opens and it just displays an empty white box and nothing happens.

**To Reproduce**
2. Play stream '...'
3. Press button '...'

**Expected behavior**
Login window to display fields for login credentials

Screenshot of issue posted to imgur: [https://imgur.com/a/YZMDflB](https://imgur.com/a/YZMDflB) 

**Desktop (please complete the following information):**
 - Windows edition and version: Windows 7.
 - System type (32 or 64 bit): 64 bit
 - Version (see title bar). 2.6.4

**F1TV account**
- Subscription type (none, Access, Pro). F1tv pro
- Country. USA
- Using VPN or proxy?. No

**Additional context**

**Comment by Kdog332** [comment]
![race control](https://user-images.githubusercontent.com/105088113/167230880-4aa64746-51fa-4cdd-b82f-3750ebcf305f.PNG)

**Comment by dhuit90** [comment]
@Kdog332 could you try (re)installing this: https://go.microsoft.com/fwlink/p/?LinkId=2124703

**Comment by Kdog332** [comment]
@dhuit90 That worked! Thankyou!!
