### ISSUE TITLE
[FEATURE] Change default install path

### ISSUE THREAD

**Issue by jdschuitemaker** [robvdpol/RaceControl#45]
**Is your feature request related to a problem? Please describe.**
The default installation path for applications on Windows is 'C:\Program Files'  or 'C:\Program Files (x86)'. The most recent version of this application suggest to install in 'C:\RACECONTROL' 

**Describe the solution you'd like**
Default installation path should either be: 
- C:\Program Files
- C:\Program Files (x86)

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by robvdpol** [comment]
Good call, I changed this because of Streamlink, but since Streamlink has now been removed I can change it back to the Program Files folder.

**Comment by robvdpol** [comment]
Fixed
