### ISSUE TITLE
[BUG] Error Load failed when casting 2020 or older race stream

### ISSUE THREAD

**Issue by REUW** [robvdpol/RaceControl#48]
**Describe the bug**
Error windows when trying to cast a 2020 or older race stream to my Mi Box S with Chromecast built in.
Stream does load normally when playing with Race Control built in player or VLC on desktop.
Error message: Load failed

**To Reproduce**
Press 'Scan' in 'Options' section
Select Chromecast device from dropdown
Select 2020 or older race stream
Press Cast
Error message will pop-up

**Expected behavior**
Start casting selected stream to Chromecast device

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/33600397/111610268-72e30400-87db-11eb-84e8-af3c80040d85.png)

**Desktop (please complete the following information):**
Windows 10 x64 20H2 build 19042.867
Casting device: Mi Box S (Chromecast built in)
Race Control version: 2.0.1

**F1TV account**
F1 TV Pro
Netherlands
No VPN or proxy

**Additional context**

**Comment by robvdpol** [comment]
This seems to be a limitation of the Chromecast, apparantly it cannot handle the pre-2021 streams. Does casting these races from the website work? I wonder how the website has implemented casting. Race Control simply generates a tokenized stream URL and sends it to the Chromecast. There's not much more that I can do.

**Comment by PierreTweakers** [comment]
I have the same issue but then on a Nvidea Shield TV, and yes casting the races from the website works normal.

**Comment by outkaj** [comment]
Noticing the same issue. This appears to be a regression, as we were able to cast 2020 races before one of the 2.x updates.

Desktop (please complete the following information):
Windows 10 x64 20H2 build 19042.906
Casting device: Vizio PX65-G1 (Chromecast Ultra/4K built-in)
Race Control version: 2.x

F1TV account
F1 TV Pro
US
No VPN or proxy

**Comment by robvdpol** [comment]
If you want to use the old casting method, you can still do that. Simply open the stream in VLC (instead of the internal player) and cast it from there (Playback menu -> Renderer -> select your device). That's basically what the old casting implementation did.
