### ISSUE TITLE
[BUG] Installer doesn't remove previous version

### ISSUE THREAD

**Issue by xconverge** [robvdpol/RaceControl#49]
I upgraded from 2.0.0 to 2.0.1 and had 2 versions installed, and needed to manually remove the previous version

I think for this sort of project it is not a big deal at all but wanted to at least let you know

I looked through the vdproj and didn't see anything obvious to me (but I am more familiar with the WiX installer framework). But I will check back and take a stab at it if it isn't something super obvious/trivial for you

Also, huge thanks, the app is really awesome, I look forward to using it throughout the season :)

**Comment by xconverge** [comment]
Ah actually just noticed #44 this probably was the reason

**Comment by robvdpol** [comment]
The installer should remove the previous version, no matter where you installed it. I just tested this by first installing 2.0.0 in C:\RaceControl and then upgrading to 2.0.1, which installs to Program Files by default. This seems to work fine: it removes the C:\RaceControl folder from the previous version and installs the new version in Program Files.

So I'm not sure what was happening on your machine. In the past there would be some cache files left over which would cause the folder not to be removed, but that's not an issue anymore.

Anyway, in the future the recommended way to get Race Control would be to [get it from the Microsoft store](https://www.microsoft.com/en-us/p/f1-race-control/9mwc9pj4jfww). Currently it lags behind one version, but I'll upload 2.0.1 for certification shortly.

**Comment by xconverge** [comment]
I might have checked "for all users" the first time and not the second. I'll switch to the store version though, thanks again!
