### ISSUE TITLE
[BUG] Changing audio track in internal player breaks audio playback

### ISSUE THREAD

**Issue by telelisast** [robvdpol/RaceControl#5]
Changing audio track when using internal player mutes audio even if re-selecting original track. You have to close player window and reopen stream to regain audio playback. 
Chaging audio track works ok with MPV.

**Comment by robvdpol** [comment]
I noticed this as well, seems to be a bug or compatibility problem in VLC (the problem also occurs in standalone VLC player). When the audiotrack is changed VLC actually reports that it succeeded, but stops outputting audio. Will need to dive in the VLC log output and maybe report it to Videolan forum.

It only occurs when watching replays. Live streams are piped through Streamlink which for some reason fixes it.

**Comment by bramceulemans** [comment]
Still happening in 2.0.

**Comment by robvdpol** [comment]
Fixed in upcoming release.

**Comment by bramceulemans** [comment]
Awesome Rob!

Read your interview on Tweakers yesterday, interesting stuff.
