### ISSUE TITLE
[BUG] Only some races are showing in the archive. 

### ISSUE THREAD

**Issue by lca96** [robvdpol/RaceControl#50]
![image](https://user-images.githubusercontent.com/81212485/112099300-27de3d80-8b9b-11eb-956b-c4454b377a62.png)
For some reason only some of the races are showing in the archive section. I've reinstalled the app but it's still the same :)

**Comment by lca96** [comment]
![image](https://user-images.githubusercontent.com/81212485/112104775-85768800-8ba3-11eb-99d2-68e0455147c8.png)
this also seems to happen to all of the years, even the most recent 2020 season

**Comment by robvdpol** [comment]
I think they changed the API yesterday, the number of results of every query seems to be limited to 10 (instead of 100 before). I'll look into it tonight.

**Comment by lca96** [comment]
I've downloaded a old version (1.8.2) and that one still works

**Comment by robvdpol** [comment]
Yes, but that release uses the old API, so doesn't have the new 50fps streams.

**Comment by robvdpol** [comment]
Fixed.

64d49a6ce390e650ddb2ed7a1c881146391f0cae
