### ISSUE TITLE
Session overzicht 

### ISSUE THREAD

**Issue by rickschwarz** [robvdpol/RaceControl#53]
Hallo Rob,

In versie 1.8.2 zie ik keurig een overzicht van de komende sessies maar in versie 2.0.2 zie ik dit overzicht niet.

Hoe komt dit ?

![v182](https://user-images.githubusercontent.com/73534617/112604003-0046d980-8e16-11eb-960d-4cfdc2d7c3be.JPG)
![v202](https://user-images.githubusercontent.com/73534617/112604007-00df7000-8e16-11eb-9411-9bcbd79b13a3.JPG)

**Comment by robvdpol** [comment]
De nieuwe API is helaas wat beperkter dan de oude API, vandaar dat je de komende sessies niet kunt zien. Staat nog wel op mijn lijstje om uit te zoeken.

**Comment by rickschwarz** [comment]
Ok. Duidelijk ! Geweldig programma overigens. Is het ook mogelijk om bij 
het weergeven in VLC de netwerk stream te openen want ik kan dan vanaf een 
andere pc play pauze te besturen en dat werkt nu niet. Nu moet ik op copy 
drukken en dan de link in VLC plaatsen via f1 viewer

Groet Rick Schwarz

Op 26 maart 2021 13:40:03 schreef Rob ***@***.***>:
