### ISSUE TITLE
[BUG] Unable to pause live sessions in the native player

### ISSUE THREAD

**Issue by TagForce** [robvdpol/RaceControl#54]
**Describe the bug**
Unable to pause the live feed in the native session, which means there's no way to sync the feeds.

**To Reproduce**
1. Go to a live session
2. Play multiple streams
3. Press pause button
4. Nothing happens.

**Expected behavior**
Stream to stop and fill a buffer which is played back when pause pressed again, like earlier versions.

**Desktop (please complete the following information):**
 - Windows 10 2004
 - 64-bit
 - RC 2.0.2

**F1TV account**
- F1TV Pro
- Netherlands
- No VPN or Proxy used

**Comment by robvdpol** [comment]
This is a VLC bug. You can switch to MPV player instead.

**Comment by ginkeltjes** [comment]
Same problem here in the native player (So not MPV or VLC).

**Comment by robvdpol** [comment]
> Same problem here in the native player (So not MPV or VLC).

Using the sync button you should be able to get the streams reasonably in sync.

**Comment by Park0** [comment]
I was unable to get video when using the native option. Opening with VLC gives me VLC but a error on opening the stream. Using copy url and opening in VLC worked

**Comment by robvdpol** [comment]
Fixed in upcoming release.
