### ISSUE TITLE
[BUG] changing audio tracks is only working in MVP player

### ISSUE THREAD

**Issue by Ralph75** [robvdpol/RaceControl#55]
*Describe the bug**
All the different movie players (mvp, VLC, watch) will start the stream correctly in English. But only MVP works when changing the audio track to another track then English.  For VLC and Watch player, changing the audio track back to english doesn't work either. 

**Desktop (please complete the following information):**
 - Windows 10 Version 20h2
 -  64 bit
 - 2.0.2

**F1TV account**
- Pro
- Belgium
- Zscaler proxy

**Comment by Tecko71** [comment]
when casting audio tracks can also not be choose from, only english language.

**Comment by robvdpol** [comment]
This is a VLC issue. However, audio track switching seems to work fine when using DASH stream type. You can select DASH streaming in the dropdown in the bottom left corner of the main window.

**Comment by Ralph75** [comment]
Hi Appreciate the quick response. Yes when setting the stream to DASH I can switch the audio track. But then I can't cast :( My goal is to cast the stream with Dutch audio track. Any tips on how to get that ?

thnx

**Comment by Tecko71** [comment]
> This is a VLC issue. However, audio track switching seems to work fine when using DASH stream type. You can select DASH streaming in the dropdown in the bottom left corner of the main window.

With dash I can not cast load error. Me too want to cast dutch audio track.

**Comment by Pschirki** [comment]
> _Describe the bug_*
> All the different movie players (mvp, VLC, watch) will start the stream correctly in English. But only MVP works when changing the audio track to another track then English. For VLC and Watch player, changing the audio track back to english doesn't work either.
> 
> **Desktop (please complete the following information):**
> 
> * Windows 10 Version 20h2
> * 64 bit
> * 2.0.2
> 
> **F1TV account**
> 
> * Pro
> * Belgium
> * Zscaler proxy

I have the same problem with the german stream. When trying the dash stream while the session was ongoing, it started from the beginning :(

**Comment by BigApple1988** [comment]
@Ralph75 @Pschirki 
You can pass --alang argument with your preferrable language. 
![image](https://user-images.githubusercontent.com/9944869/112715605-0666b400-8f03-11eb-9a65-b53a660cb505.png)
Launching with "selected" language works well for some reason

**Comment by Pschirki** [comment]
Great! Will try this in a few ho🫂

**Comment by Ralph75** [comment]
Couldn't get it working, anyone any idea what country codes to use ? I used "--alang=nl,nl"

Also as the goal is to cast the F1 stream with Dutch language track and MPV doesn't support cast (well I couldn't find the option). 
Anyway thanks for helping :-)

**Comment by Tecko71** [comment]
If we could cast with vlc (render) than was the problem solft. But the vlc casting option does not work either.

**Comment by robvdpol** [comment]
See issue #56, next release will have audio track switching when casting.

![image](https://user-images.githubusercontent.com/56960828/112723329-251e7800-8f0e-11eb-848f-fc8aa3fb8798.png)

**Comment by robvdpol** [comment]
> Couldn't get it working, anyone any idea what country codes to use ? I used "--alang=nl,nl"
> 
> Also as the goal is to cast the F1 stream with Dutch language track and MPV doesn't support cast (well I couldn't find the option).
> Anyway thanks for helping :-)

For Dutch language in MPV use "--alang=nld"

**Comment by Tecko71** [comment]
That is great change that option! Was thinking about that, nice that next version has the option audio select

**Comment by Pschirki** [comment]
Setting the language to german in MPV  brings up the pre race screen :( maybe because the german audio stream comes from SKY?
![image](https://user-images.githubusercontent.com/70758565/112725954-299d5d80-8f1b-11eb-858b-62bccf858f8b.png)

**Comment by robvdpol** [comment]
Fixed in upcoming release.
