### ISSUE TITLE
[FEATURE] Add different Audio tracks for Casting

### ISSUE THREAD

**Issue by LoVega1337** [robvdpol/RaceControl#56]
They new native Casting option works great, although it automatically defaults the audio track to English. A feature to select the Audio track before Casting would be extremely convenient.

(I tried casting it through VLC like last year, but something broke so I'm basically stuck using the integrated Vasting option.)

**Comment by robvdpol** [comment]
Fixed in next release, audio track can be selected when casting has started.

47f1e65e0231d487d8ce992e8bf768523cfc5b79

**Comment by robvdpol** [comment]
Released.
