### ISSUE TITLE
[BUG] F2 stream not working ? 

### ISSUE THREAD

**Issue by AymericFerreira** [robvdpol/RaceControl#57]
I tried to watch F2 live qualifying and I receive this error :
`An error occurrence while retrieving the stream URL.` I have this error with all player (MPV, VLC and Internal through Watch).

I also have this error with Practice session. I think API is not retrieving the good URL.
Formula 1 is working good.

I have F1 TV Pro, Windows 10 64 bit and Race control 2.0.2

**Comment by robvdpol** [comment]
Where are you located? I've seen this issue reported before and I'm suspecting it might have something to do with the region you're in.

**Comment by AymericFerreira** [comment]
Canada

**Comment by Blakout007** [comment]
Same error in Denmark, win10x64, race control 2.0.2
else a great app

**Comment by Blakout007** [comment]
Hi, when showing F2 stream the audio is default deutch and after changing to english or something else language the stream STOPs. Have to close and start the player again to have a running stream. Same error for internal Player and VLC. Hope you can help. 👍 
PC, win10x64, race control 2.0.2, Denmark.

**Comment by AymericFerreira** [comment]
I confirm the problem of Blakout007, live and previous F2 stream are working now, but language is Deutsch and changing to any other language make it crash

**Comment by Blakout007** [comment]
> 
> 
> I confirm the problem of Blakout007, live and previous F2 stream are working now, but language is Deutsch and changing to any other language make it crash

Great - whats fast work - thank you...

**Comment by arthurpoortman** [comment]
I have the same issue as Blakout007, tested today with RC 2.0.4.
Issue confirmed with MPV and VLC (copy and pase Url stream in VLC).
Platform: Windows 10 Enterprise Version 20H2 OS build 19042.906
.NET Runtime 5.0.5 (x64)

**Comment by robvdpol** [comment]
Fixed in upcoming release.
