### ISSUE TITLE
Internal Player Black Screen

### ISSUE THREAD

**Issue by nilskk** [robvdpol/RaceControl#58]
I tried to watch some videos with the internal player, but it doesnt play. Just a black screen. Does someone have an idea what would cause that?

**Comment by robvdpol** [comment]
Does it work with MPV? Can you give some examples of videos that don't work?

**Comment by nilskk** [comment]
MPV and VLC works. Its just the internal player. It didn't work in any video I tried so far

**Comment by robvdpol** [comment]
Try switching to DASH stream type.

**Comment by koonweee** [comment]
I am getting the same issue. As an additional note, launching VLC is much faster than MPV (almost a full minute)

**Comment by nilskk** [comment]
> 
> 
> Try switching to DASH stream type.

That fixed it :)
Thanks a lot. Awesome tool btw <3
