### ISSUE TITLE
Session list sorting

### ISSUE THREAD

**Issue by CodeCasterNL** [robvdpol/RaceControl#59]
When multiple series are checked, but also for at least one entry within the F1 series itself, the ordering of sessions is inconsistent. See the 2018 Austrian Grand Prix:

* 2018 Austrian Grand Prix - Full Race
* 2018 Austrian Grand Prix - Qualifying

For for example the British GP of that year, it's the other way around. And for 2018-2021 (so far), when F1, F2 and F3 are checked, the F1 race always comes last. And for the current race (2021 Bahrain), the F2 sessions are shown before F1 Practice 1, which came before F2 Qualifying.

Sessions should perhaps be ordered by date and time, where they aren't? Perhaps even in ascending order, so the F1 race is always on top of the session list?

**Comment by robvdpol** [comment]
The data from previous years is pretty crappy in the new API, the old API was much better in that respect. The archive on the F1TV website has the same issues (inconsistent naming and sorting).

I've added sorting by session start date (for the sessions that have a start date).
