### ISSUE TITLE
[BUG] Download randomly freezes with no user feedback

### ISSUE THREAD

**Issue by telelisast** [robvdpol/RaceControl#6]
Downloading any stream has a high chance of random freeze/stuck without any user feedback that this has happened. Freeze can be observed by looking at file size not increasing or network monitor showing zero network activity. Download window remains in "downloading" state indefinitely when this happens. Tested on 2020 Belgian GP onboard footage.
Suspected "Pipe copy aborted" error is happening in the background. Same error can occur when using streamlink directly in command prompt.

**Comment by robvdpol** [comment]
I changed the download function to use VLC instead of Streamlink. It's less complicated and seems to work better. And I can also report the progress of the download this way. Will be available in the coming release.
