### ISSUE TITLE
[FEATURE/DISCUSSION] Prefix session names with series short name

### ISSUE THREAD

**Issue by CodeCasterNL** [robvdpol/RaceControl#60]
Not all sessions have their series name prefixed in their `titleBrief` property. You can see variants like this:

* "Practice" (F2 practice, 2021 Bahrain)
* "F1 Practice 1" (2019 Azerbaijan)
* "Practice 1" / "Practice 2" / ... / "Race" (F1, almost all Grand Prix 2018)
* "2019 Bahrain Grand Prix - F2 Feat Race" (titleBrief is longer than title, which is "2019 Bahrain GP - F2 Feature Race")

Should the session name be prefixed consistently with the series name? And maybe be cleaned up? Or even reconstructed from the genres and other metadata? So the examples above become:

* "F2 Practice"
* "F1 Practice 1"
* "F1 Practice 1" / "F1 Practice 2" / ... / "F1 Race"
* "F2 Feature Race"

**Comment by robvdpol** [comment]
Fixed.
