### ISSUE TITLE
[BUG] System Exception

### ISSUE THREAD

**Issue by jorntie1** [robvdpol/RaceControl#62]
**Describe the bug**
System Exception error on login

**To Reproduce**
1. try to put in credentials

**Expected behavior**
it going through

**Screenshots**
imgur link of the error: https://imgur.com/a/HGapf3o
log file: 
[RaceControl_without_emails.log](https://github.com/robvdpol/RaceControl/files/6214306/RaceControl_without_emails.log)

**Desktop (please complete the following information):**
 - Windows edition and version: Microsoft Windows 10 Pro, Version 10.0.19042 Build 19042
 - System type: 64 bit

**F1TV account**
- Subscription type: pro
- country: Germany
- no vpn or proxy

**Comment by robvdpol** [comment]
Thanks for providing the log file, however I don't have enough information to troubleshoot this issue. For anyone who is experiencing this issue, would you please help by performing the following steps:

- Install [Fiddler Classic](https://www.telerik.com/download/fiddler)
- Start Fiddler and then start Race Control
- When you log in to Race Control, a POST request to **api.formula1.com/v2/account/subscriber/authenticate/by-password** should appear
- Select this request and click the 'Inspectors' tab
- In the bottom (response) part of the window, select 'Raw'
- Copy/paste the entire response (you can remove or obfuscate any private information such as email addresses or names)

Thank you.

**Comment by chrcoluk** [comment]
I will try and do this tomorrow, I have to wait until then as I need to have the VPN on when I test this, and cannot have it on at this moment of time, thanks.

**Comment by chrcoluk** [comment]
I am getting failed to register fiddler as system proxy.

Isnt it easier to add debug logging to the app instead?

**Comment by chrcoluk** [comment]
Ok I got by the proxy error, but sadly I am not seeing the post request you mentioned, the app just generates a "tunnel to" api.formula1.com

I have the raw paste below, there is no private info inside it.  Also I enabled the option in fiddler to see inside encrypted traffic.

`CONNECT api.formula1.com:443 HTTP/1.1
Host: api.formula1.com:443
User-Agent: RaceControl

A SSLv3-compatible ClientHello handshake was found. Fiddler extracted the parameters below.

Version: 3.3 (TLS/1.2)
Random: 60 61 D0 BA C7 48 5A 0A AB 5E 2D 26 84 5B EC 84 CF 71 61 DB 78 17 79 14 E6 2F 82 C5 C1 B7 AC 38
"Time": 26/04/2069 17:16:32
SessionID: empty
Extensions: 
	server_name	api.formula1.com
	supported_groups	x25519 [0x1d], secp256r1 [0x17], secp384r1 [0x18]
	ec_point_formats	uncompressed [0x0]
	signature_algs	rsa_pkcs1_sha256, rsa_pkcs1_sha384, rsa_pkcs1_sha1, ecdsa_secp256r1_sha256, ecdsa_secp384r1_sha384, ecdsa_sha1, dsa_sha1, rsa_pkcs1_sha512, ecdsa_secp521r1_sha512
	SessionTicket	empty
	extended_master_secret	empty
	renegotiation_info	00
Ciphers: 
	[C02C]	TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
	[C02B]	TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
	[C030]	TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
	[C02F]	TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
	[009F]	TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
	[009E]	TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
	[C024]	TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
	[C023]	TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
	[C028]	TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
	[C027]	TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
	[C00A]	TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
	[C009]	TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
	[C014]	TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
	[C013]	TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
	[009D]	TLS_RSA_WITH_AES_256_GCM_SHA384
	[009C]	TLS_RSA_WITH_AES_128_GCM_SHA256
	[003D]	TLS_RSA_WITH_AES_256_CBC_SHA256
	[003C]	TLS_RSA_WITH_AES_128_CBC_SHA256
	[0035]	TLS_RSA_WITH_AES_256_CBC_SHA
	[002F]	TLS_RSA_WITH_AES_128_CBC_SHA
	[000A]	SSL_RSA_WITH_3DES_EDE_SHA

Compression: 
	[00]	NO_COMPRESSION
`

**Comment by chrcoluk** [comment]
also attaching raw output from the second box as well.

`HTTP/1.1 200 Connection Established
FiddlerGateway: Direct
StartTime: 14:06:02.038
Connection: close

Encrypted HTTPS traffic flows through this CONNECT tunnel. HTTPS Decryption is enabled in Fiddler, so decrypted sessions running in this tunnel will be shown in the Web Sessions list.

Secure Protocol: Tls12
Cipher: Aes128 128bits
Hash Algorithm: Sha256 ?bits
Key Exchange: ECDHE_RSA (0xae06) 255bits

== Server Certificate ==========
[Subject]
  CN=api.formula1.com

[Issuer]
  CN=Amazon, OU=Server CA 1B, O=Amazon, C=US

[Serial Number]
  019E79AD6B437DDB5DA05558A88F4F8D

[Not Before]
  14/10/2020 01:00:00

[Not After]
  13/11/2021 23:59:59

[Thumbprint]
  60D53E15591134E70AD2100E92941062549365FA

[SubjectAltNames]
api.formula1.com
`

**Comment by robvdpol** [comment]
These fiddler logs are not really useful, so I'll add some better logging in the next release.

**Comment by robvdpol** [comment]
Please try version 2.0.4, it should give a more meaningful error.

**Comment by chrcoluk** [comment]
Sorry for taking so long to test this.

Error as below.

"An attempt was made to access a socket in a way forbidden by its access permssions (api.formul1.com:443)"

**Comment by robvdpol** [comment]
I suspected it would be something like this, thanks for letting me know.

**Comment by BoleMNE** [comment]
> Sorry for taking so long to test this.
> 
> Error as below.
> 
> "An attempt was made to access a socket in a way forbidden by its access permssions (api.formul1.com:443)"
> 
> So this is firewall related it turns out I had set the rule to private network profile only, of course nordvpn is on a public profile and it was blocked, the newer clearer error message allowed me to fix this quickly, so in the end it was operator error but I think its good you made the error changes as it will help others moving forward.
> 
> Thank you for your time on this.

How did you end up fixing this, i still cant figure out what to do with firewall to fix this issue
