### ISSUE TITLE
[FEATURE] Include date & time when "episodes" are released / broadcast

### ISSUE THREAD

**Issue by therealabradolf** [robvdpol/RaceControl#63]
**Is your feature request related to a problem? Please describe.**
Whenever i come into a race weekend and i want to watch everything chronologically (press conference, paddock pass, weekend warm-up, ...) i can't seem to figure out in which order they were aired.
![image](https://user-images.githubusercontent.com/16636556/112713303-c8529b80-8ed4-11eb-9388-3d52db071b95.png)

**Describe the solution you'd like**
It would be nice to have a sorting option so we could sort it by "date aired" or something similar

**Comment by robvdpol** [comment]
Unfortunately, the air date is not available in the API, so I can not show it or sort by it. I have tried to improve the ordering of sessions and episodes a bit though.
