### ISSUE TITLE
MPV streams repeating audio

### ISSUE THREAD

**Issue by Gerbildral** [robvdpol/RaceControl#65]
When you open an MPV live stream the audio is repeating itself,
sometimes the video is also repeating.

**Comment by robvdpol** [comment]
Which stream type are you using? HLS or DASH?

**Comment by Gerbildral** [comment]
I was using DASH,
Just tried HLS but then the english audio is working fine, but when i go to an other language the stream goes to to picture below
![image](https://user-images.githubusercontent.com/29066252/112720795-e2a26e80-8f00-11eb-9f20-939f75020d00.png)

**Comment by robvdpol** [comment]
Yeah... MPV is having some issues with the new streams apparently. DASH doesn't work properly for the live streams, HLS does work but switching audio streams seems to be broken and for F2 it defaults to german. F1 seems to default to English.
