### ISSUE TITLE
[FEATURE] Add Option for change video quality per stream

### ISSUE THREAD

**Issue by ssomma** [robvdpol/RaceControl#66]
**Is your feature request related to a problem? Please describe.**
Given that the download bandwidth could not support multiple streams simoultaneus on 1080p, some of them buffers and will be not synchronized after that.

**Describe the solution you'd like**
The best way to address should be being able to change the quality of any stream opened. With this way you could manage the quality in order to keep the total bandwidth used aligned with what your ISP provides you.

**Describe alternatives you've considered**
As a first approach this could be a general option for all streams opened.

**Additional context**
As context, in general cases you dont need to have the same quality for the main stream and timigs or driver cameras.

**Comment by robvdpol** [comment]
Working on this.

**Comment by robvdpol** [comment]
Added in upcoming release.

df9919a573fadb18f88b72b1876234d887ee8092
