### ISSUE TITLE
Sponsor Offer

### ISSUE THREAD

**Issue by fayeackceypa83** [robvdpol/RaceControl#69]
Hi, just discovered this project and it's amazing! Saw that the project needed sponsors on the reddit thread, and i'd like to contribute a one time sum instead of the monthly $5 on the sponsor page. How can i get in touch about this? Thanks!

**Comment by robvdpol** [comment]
Hi, you can make a one time donation through [ko-fi](https://ko-fi.com/robvdpol).

Thanks!
