### ISSUE TITLE
Program works over Microsoft Store download but not with manual installation

### ISSUE THREAD

**Issue by Robi2003** [robvdpol/RaceControl#70]
First of all: WHAT A F#%&ing GREAT TOOL! A big thank you to the programmer!

I tried to install it first over your .msi installation here on Github. And I installed the Net Core Runtime programme. But every time I want to install Race Control I get the message that Net Core Runtime is required.

On the other side: The installation from the Windows Store works fine so far. 

But the Github version is more up to date and that is what I want to use.

**Comment by johnnelus** [comment]
I ran into the same issue this afternoon. Installing .NET Desktop Runtime fixed it for me.

**Comment by robvdpol** [comment]
Yes, please make sure you have the **desktop x64** runtime installed. This one:
https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.4-windows-x64-installer
