### ISSUE TITLE
[BUG] VODs are not available when there is a live session

### ISSUE THREAD

**Issue by famguy07** [robvdpol/RaceControl#71]
**Describe the bug**
No VODs are available to select and play if there is any live session. I had this issue trying to watch F2 race 1 while F2 race 2 was live, and now the same issue is here when I'm trying to watch F2 feature race with the F1 Post Race Show being live. 

F2 isn't the only thing affected, I can't view any sessions or videos from anywhere in Race Control when there is a live session.

**To Reproduce**
1. Open the app during a live session
2. Attempt to open any VOD

**Expected behavior**
The VOD should appear in the list and be playable at any time.

**Screenshots**
![image](https://user-images.githubusercontent.com/11774511/112761330-cd911280-8fc8-11eb-944b-c304b7d8c375.png)

**Desktop (please complete the following information):**
 - Windows 10 20H2 64 bit
 - Version 2.0.0 (newest came out right before the race today)
**F1TV account**
- Pro
- US
- No VPN/Proxy

**Comment by LoVega1337** [comment]
Click the "Formula 1/2" checkbox on the left side under "Series".

**Comment by famguy07** [comment]
I did that during the F2 race1/race 2 thing and the VODs still did not appear. I forgot to do the same with my screenshot here and now there's no live session to test for another screenshot.

**Comment by robvdpol** [comment]
Upgrade to the latest version first. If it still happens, please provide a screenshot with the series selected and reopen the issue.
