### ISSUE TITLE
[FEATURE] Download Resolution

### ISSUE THREAD

**Issue by MiSeRy81** [robvdpol/RaceControl#73]
Hi.

Can you add an option to change the download resolution ?

**Comment by robvdpol** [comment]
Should be possible, I'll put it on the roadmap.

**Comment by DoeEensGek** [comment]
Possible to make this an option for copy link as well?

**Comment by robvdpol** [comment]
> Possible to make this an option for copy link as well?

No, because the link that is copied refers to a playlist that has all the different video streams embedded in it. So it's up to the media player that you're using to select a specific video stream (you should be able to switch during playback).

**Comment by robvdpol** [comment]
Fixed in upcoming release, downloading will respect the selected default video quality.
