### ISSUE TITLE
[FEATURE] Support for ARM64 architecture

### ISSUE THREAD

**Issue by k818mn1** [robvdpol/RaceControl#77]
I cant install Race Control on my surface pro x, because it is ARM64 architecture. Any chance you can compile a version that can run on ARM 64.

**Comment by robvdpol** [comment]
Should be possible, I'll look into it.

**Comment by robvdpol** [comment]
The x86 build is in the Microsoft Store now, can you please check if it works?

**Comment by k818mn1** [comment]
Hi Rob. I successfully installed Race Control x86 on my Surface Pro X and have played some of the sessions from the Spanish GP. Thanks for your time and effort!Martin
-------- Original message --------From: Rob ***@***.***> Date: 5/18/21  11:55 AM  (GMT-04:00) To: robvdpol/RaceControl ***@***.***> Cc: k818mn1 ***@***.***>, Author ***@***.***> Subject: Re: [robvdpol/RaceControl] [FEATURE] Support for ARM64 architecture (#77) 
The x86 build is in the Microsoft Store now, can you please check if it works?
