### ISSUE TITLE
[BUG] Does not find ChromeCast devices

### ISSUE THREAD

**Issue by mvl64** [robvdpol/RaceControl#79]
**Describe the bug**
When I click the "SCAN" button, no chromecast device is found.
In my network, all Chromecasts are in a separate subnet (in a VLAN).
mDNS traffic is repeated between subnets,, and appropriate ports opened in the firewall to allow traffic from main network to the chromecast devices. This setup works for all apps using the chromecasts, e.g. Netflix, NPO Plus, YouTube , etc.
 

**To Reproduce**
1. Press "Scan" button
2. software starts searching
2. after the search, no devices is available in the picklist

**Expected behavior**
The available devices are shown and selectable in the picklist

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10 
 - 64 bit
 - Version 2.0.4
 - 
**F1TV account**
- Subscription type: Pro
- Netherlands
- no VPN

**Additional context**

**Comment by robvdpol** [comment]
I'll look into it. I might need to fork the Googlecast library and upgrade its dependencies (zeroconf). That might fix it.

**Comment by mvl64** [comment]
Dank je Rob, ik ga straks even testen!
Veel plezier morgen met de race.

**Comment by robvdpol** [comment]
Testen kan pas zodra ik een release maak ;) Tenzij je zelf de broncode compileert natuurlijk.

________________________________
Van: mvl64 ***@***.***>
Verzonden: zaterdag 17 april 2021 18:25
Aan: robvdpol/RaceControl ***@***.***>
CC: Rob ***@***.***>; State change ***@***.***>
Onderwerp: Re: [robvdpol/RaceControl] [BUG] Does not find ChromeCast devices (#79)


Dank je Rob, ik ga straks even testen!
Veel plezier morgen met de race.

**Comment by mvl64** [comment]
Ah, ik dacht dat je dat had gedaan, omdat de issue gesloten was. Dan wacht
ik nog even af ;)

**Comment by rienheuver** [comment]
Dus hier komt geen release meer voor voor de race straks? Zou me wel goed uitkomen om de race op m'n android-tv te kunnen kijken ipv m'n 13" laptop :P

**Comment by robvdpol** [comment]
> Dus hier komt geen release meer voor voor de race straks? Zou me wel goed uitkomen om de race op m'n android-tv te kunnen kijken ipv m'n 13" laptop :P

https://github.com/robvdpol/RaceControl/releases/tag/2.0.5

**Comment by mvl64** [comment]
Chromecast werkt wel hoor, als je telefoon maar in hetzelfde netwerk
segment zit
