### ISSUE TITLE
x386 installation[FEATURE]

### ISSUE THREAD

**Issue by Biersmurf** [robvdpol/RaceControl#80]
Is it correct that it only works on the 64Bit or is their a x386 installer somewhere?

**Comment by robvdpol** [comment]
Correct, but I'll look into adding a 32-bit build as well.

It has been 64-bit only because of Streamlink integration, but that has been removed so I should be able to create builds for different architectures now.

**Comment by Biersmurf** [comment]
Mooi werk Rob,

Vandaag werkte er niets maar dat lag volgens mij aan F1  😉

Van: Rob ***@***.***>
Verzonden: 16 April 2021 08:21
Aan: robvdpol/RaceControl ***@***.***>
CC: Waldo Hogendoorn ***@***.***>; Author ***@***.***>
Onderwerp: Re: [robvdpol/RaceControl] x386 installation[FEATURE] (#80)


Correct, but I'll look into adding a 32-bit build as well.

It has been 64-bit only because of Streamlink integration, but that has been removed so I should be able to create builds for different architectures now.

**Comment by k818mn1** [comment]
An x86 build would also be useful for my Surface Pro X, which is native ARM64 architecture but can also run x86 apps with a built-in x86 emulator.

**Comment by robvdpol** [comment]
The x86 build is in the Microsoft Store now, can you please check if it works?

**Comment by Biersmurf** [comment]
Hi Rob

Dit doet een maatje van mij die nog op de x386 werkt dus zal ik hem vragen

Wel “ enorm” bale zeg dat we naar Viaplay-abonnementen volgend jaar moeten wat best wat roet in het eten zal gooien voor jou mooie oplossing

Groet Waldo

Op 18 mei 2021 om 17:55 heeft Rob ***@***.***> het volgende geschreven:

﻿

The x86 build is in the Microsoft Store now, can you please check if it works?

**Comment by robvdpol** [comment]
F1TV Pro zal gelukkig gewoon beschikbaar blijven in Nederland:
https://corp.formula1.com/nent-group-secures-exclusive-formula-1-rights-in-the-netherlands-for-viaplay/
