### ISSUE TITLE
[BUG] VLC can't open live stream

### ISSUE THREAD

**Issue by Bramgus12** [robvdpol/RaceControl#81]
When I choose the world feed for the 2021 Emilia Romagna Grand Prix Practice 1 I get an error that VLC can't open the link. Also the built in player will not work. The only player that seems to work is MPV at the moment.

**To Reproduce**
1. go to the current live session and press the VLC or watch button.

**Expected behavior**
The Stream starts.

**Screenshots**
![image](https://user-images.githubusercontent.com/42220620/115002582-36bbc580-9ea5-11eb-8a4a-1affc76ac681.png)
![image](https://user-images.githubusercontent.com/42220620/115002632-45a27800-9ea5-11eb-852b-16f0a2a06df3.png)

**Desktop (please complete the following information):**
 - Windows 10 20H2 19042.928
 - 64 bit
 - version 2.0.4

**F1TV account**
- Subscription type: Pro
- Netherlands
- Using VPN or proxy? no

**Comment by tsshadow** [comment]
An temporary workaround is to copy the channellink (with button copy) and manually open in VLC.

**Comment by robvdpol** [comment]
Yes, I'm aware of this issue.

Workaround for people running into this issue is selecting the 'HLS' stream type. Problem is that switching audio tracks won't work with that stream type. If you want to switch audio tracks I would recommend using MPV.

**Comment by jdschuitemaker** [comment]
I am having the same experience. In addition, I cannot change language to Dutch in the MPV stream. It results to a stream that shows a message in 6 languages saying that the stream will start shortly.

![2021_04_16_11_22_54_Window](https://user-images.githubusercontent.com/2353413/115003709-5d2e3080-9ea6-11eb-8293-f1b6c9029cea.png)

**Comment by rickvand** [comment]
Im using the F1TV website for the main feed, because thats the only stream where I use the audio from. That might be a temporary workaround for those struggling with the audio switching...

**Comment by nikitakrykhtin** [comment]
Hi everyone, at first I want to say huuuuge thank you to the author, it's amazing software! I have same bug, tryin to use HLS stream type, it works in VLC, but you have to start it two times, on the first time VLC starts the stream in 1080, but hangs in couple seconds, on the second time it starts normally, but the stream quality is going down to 720. Copying the link to the VCL doesn't help, same issue. F1TVPro webplayer works in 1080 flawlessly. The problem appears after the last update. Any idea how I can start VLC in 1080?

**Comment by robvdpol** [comment]
> Hi everyone, at first I want to say huuuuge thank you to the author, it's amazing software! I have same bug, tryin to use HLS stream type, it works in VLC, but you have to start it two times, on the first time VLC starts the stream in 1080, but hangs in couple seconds, on the second time it starts normally, but the stream quality is going down to 720. Copying the link to the VCL doesn't help, same issue. F1TVPro webplayer works in 1080 flawlessly. The problem appears after the last update. Any idea how I can start VLC in 1080?

You can change the following setting, it might improve playback in VLC:
Tools -> Preferences -> Show all settings -> Input / Codecs -> Demuxers -> MPEG-TS -> uncheck 'Trust in-stream PCR'

And also the following setting to force highest stream quality:
Tools -> Preferences -> Show all settings -> Input / Codecs -> Demuxers -> Adaptive -> change 'Adaptive Logic' to 'Highest Bandwidth / Quality'

**Comment by nikitakrykhtin** [comment]
> > Hi everyone, at first I want to say huuuuge thank you to the author, it's amazing software! I have same bug, tryin to use HLS stream type, it works in VLC, but you have to start it two times, on the first time VLC starts the stream in 1080, but hangs in couple seconds, on the second time it starts normally, but the stream quality is going down to 720. Copying the link to the VCL doesn't help, same issue. F1TVPro webplayer works in 1080 flawlessly. The problem appears after the last update. Any idea how I can start VLC in 1080?
> 
> You can change the following setting, it might improve playback in VLC:
> Tools -> Preferences -> Show all settings -> Input / Codecs -> Demuxers -> MPEG-TS -> uncheck 'Trust in-stream PCR'
> 
> And also the following setting to force highest stream quality:
> Tools -> Preferences -> Show all settings -> Input / Codecs -> Demuxers -> Adaptive -> change 'Adaptive Logic' to 'Highest Bandwidth / Quality'

Eternal thanks, you're the best! It helped, now it works just fine in VLC, thank you very much for you support!
