### ISSUE TITLE
[ISSUE] Streams take a very long time to load

### ISSUE THREAD

**Issue by AleshoN** [robvdpol/RaceControl#84]
Hey guys! I started using Race Control today after only having used the F1TV site and Im very very happy with it, thanks for creating it! But I have an issue: When I try to open streams (for example the FP1 session from today and it doesn't matter which player) it takes 2-3 minutes for the stream to properly load and play. And it takes another 1-2 minutes for the Audio Track to establish itself. 

Is there a setting I can change to make it load faster? Just to clarify: I have no loading issues with the F1TV site so maybe Im just a little dull and missed something 😁

Im using F1TV Pro and I'm not using a VPN or Proxy.

Thanks in advance! 😁

**Comment by pro2call-nl** [comment]
with MPV they load quickley. with the internal viewer no luck

**Comment by Oaquasis** [comment]
I can confirm and after trying a couple of thing it seems to have something to do with stream type.
When I set it to DASH or Automatic, loading seems to take forever.
When I set it to HLS it loads within a minute. Still quite a bit slower then the MPV player but acceptable.

**Comment by pro2call-nl** [comment]
> I can confirm and after trying a couple of thing it seems to have something to do with stream type.
> When I set it to DASH or Automatic, loading seems to take forever.
> When I set it to HLS it loads within a minute. Still quite a bit slower than the MPV player but acceptable.

I can confirm this is working.

**Comment by AleshoN** [comment]
> > I can confirm and after trying a couple of thing it seems to have something to do with stream type.
> > When I set it to DASH or Automatic, loading seems to take forever.
> > When I set it to HLS it loads within a minute. Still quite a bit slower than the MPV player but acceptable.
> 
> I can confirm this is working.

Thank you, I will try that.

**Comment by AleshoN** [comment]
> I can confirm and after trying a couple of thing it seems to have something to do with stream type.
> When I set it to DASH or Automatic, loading seems to take forever.
> When I set it to HLS it loads within a minute. Still quite a bit slower than the MPV player but acceptable.

Hopefully it works, fingers crossed for qualy 😅

**Comment by AleshoN** [comment]
> with MPV they load quickley. with the internal viewer no luck

Sounds like imma have to try that player again 😁👍 Thanks!

**Comment by jvgoch** [comment]
+1
I'm having issues with the internal player as well. MPV loads fine.

**Comment by Br-ian** [comment]
+1 same issue, VLC/internal don't work, MPV does

**Comment by AleshoN** [comment]
Thank you guys for the massive help! Using MPV did the trick even with automatic stream type. Cheers!
