### ISSUE TITLE
[BUG] Installer (Race Control 2.0.4) doesn't make shortcut to "RaceControl.exe" but to the installer

### ISSUE THREAD

**Issue by MrBreaker666** [robvdpol/RaceControl#86]
**Describe the bug**
Installer (Race Control 2.0.4) doesn't make shortcut to "RaceControl.exe" but to the installer

**To Reproduce**
1. Download Race Control 2.0.4 
2. Install Race Control 2.0.4  (next, next, next e.g. leave values to the default)
3. Start Race Control from ShortCut on desktop
4. Now it's starting the installer again instead off "RaceControl.exe"

**Expected behavior**
Start Race Control instead off the installer.

**Screenshots**
Do not provide 

**Desktop (please complete the following information):**
 - Windows 10, 20H2 19042.928
 - System type x64
 - Version 2.0.4

**F1TV account**
- Subscription type Pro
- The Netherlands
- Using VPN or proxy => No

**Additional context**

**Comment by MrBreaker666** [comment]
Could be an antivirus program issue... (after de-installation and re-installation) it the installer seems to do the job, just fine...

**Comment by robvdpol** [comment]
Ok, will close the issue then.
