### ISSUE TITLE
[BUG]Live freeze when change language

### ISSUE THREAD

**Issue by BasteamGT** [robvdpol/RaceControl#87]
In MPV or Watch when I watch the direct in English it's OK.
When I change Language (English to French). The screen freeze.
For "watch" no image, no sound for all time
For "MPV" return to the start of record of race and freeze when I want to return to the race direct.

**Desktop (please complete the following information):**
 - Windows 10 X64
 - System type (32 or 64 bit)
 
Race controle 2.0.5

**F1TV account**
- Subscription type Pro
- France
- No VPN or proxy

**Comment by avassem85** [comment]
I had the same thing changing from English to Dutch

Windows 10 X64
Race controle 2.0.5
Subscription type Pro

**Comment by robvdpol** [comment]
Fixed in upcoming release.
