### ISSUE TITLE
[FEATURE] Ability to load layout from file

### ISSUE THREAD

**Issue by bootsie123** [robvdpol/RaceControl#89]
Hi! Before I describe the feature, I just wanted to say a big thanks for working on this project! It’s been fantastic to use so far and is always getting better. Great job!

Feature:

Basically I would love the ability to load a layout from a custom config file instead of being limited to one saved layout slot. As someone who likes to fine tune the sizes for everything with the config file, it gets kinda cumbersome to have to replace the existing config file with the one I want to use. Adding on this, either a simple load file dialog would work or better yet, having a layout directory and being able to select the layout from a list would be great

**Comment by robvdpol** [comment]
I will add a load file dialog for now. Might make a more comprehensive solution later.

**Comment by robvdpol** [comment]
Implemented an import button for the next release.
