### ISSUE TITLE
[FEATURE]Would Language selection for live streams from Race Control be possible

### ISSUE THREAD

**Issue by Pschirki** [robvdpol/RaceControl#9]
First i want to thank you for this awesome program! Great work!

So, would it be possible to select a language before starting live streams or, maybe set a special language as default for the used player? This would be great!!

Keep up the great work!!

**Comment by robvdpol** [comment]
I'll have a look to see what's possible, it depends on what Streamlink can do.

**Comment by robvdpol** [comment]
Not possible with current streaming platform, so closing this issue.
