### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by vikdb** [robvdpol/RaceControl#91]
How do you update to Race Control 2.0.5 if you installed it through the Microsoft store? 

I tried downloading the Race Control 2.0.5 zip, but there is no installer.exe?

**Comment by robvdpol** [comment]
If you're using the Microsoft Store app it will automatically update itself. However, the certification process from Microsoft usually takes some time so the 2.0.5 release isn't in the store yet. Just be patient, and 2.0.5 isn't a big update anyway, so you're fine to use 2.0.4.

**Comment by vikdb** [comment]
Ok thnx, maybe i'll switch to the manual install so i'll get my updates faster. :)

**Comment by robvdpol** [comment]
By the way, you need to download the .msi-file, not the zip-file.
