### ISSUE TITLE
[BUG] Switching audio device not working after switching video quality

### ISSUE THREAD

**Issue by rickschwarz** [robvdpol/RaceControl#92]
When in the internal player the Video Quality is set to

Medium
Low
Potato

Then in Setting > Audio device when selecting an other device then Standard the standard device cant be disabled.
In High quality it works fine

**Comment by robvdpol** [comment]
I'm working on switching to another mediaplayer for the internal player which should solve this issue.

**Comment by robvdpol** [comment]
Fixed in upcoming release.
