### ISSUE TITLE
[Bug]: Internal players freezes or starts to stutter after syncing them

### ISSUE THREAD

**Issue by MasoLinguist** [robvdpol/RaceControl#93]
I can watch 2  or 4 or 6 internal players simultaniously  without any problem.

I can manipulate timelines manually and all player keep working fine. If I hit the s key or the sync button on a random internal player the timelines allign but the videos stop playing or stutter. 

Audio is fine by the way but I can't bring the video streams back. I pause them and hit play again, no effect, audio works but video struggles. 

 
Windows 10 X64
System type (64 bit)
Race control 2.0.5

Subscription type Pro
NL acc but streaming from Germany
No VPN or proxy

**Comment by robvdpol** [comment]
I'm working on switching to another mediaplayer for the internal player which should solve this issue.

**Comment by MasoLinguist** [comment]
> I'm working on switching to another mediaplayer for the internal player which should solve this issue.

Great to hear! Thank you for your time and effort. I'm looking forward to it. 

KR

Marc

**Comment by robvdpol** [comment]
Fixed in upcoming release.
