### ISSUE TITLE
Hi Robvdpol

### ISSUE THREAD

**Issue by JC38818** [robvdpol/RaceControl#95]
Hi Robvdpol, 
I can watch videos on this app, but when I try to download them I get an error as below: 

Name: 2021 Emilia Romagna Grand Prix - World Feed
Destination: C:\Program Files\WindowsApps\16380RobvanderPol.F1RaceControl_2.0.4.0_x64_ ...
Status: Failed (see log for details)
Progress: 0.0%

![image](https://user-images.githubusercontent.com/83104662/115945326-34e79880-a489-11eb-807f-4bb6549c2d54.png)

 - Windows 10 64 bit 
 - 
![image](https://user-images.githubusercontent.com/83104662/115945464-f43c4f00-a489-11eb-99bd-b3ea1d453fc4.png)

**F1TV account**
- Subscription type (Pro)
- USA
- Using VPN or proxy? - No

**Additional context**
Where is the error log file please?  Any idea how I can fix this issue?

**Comment by robvdpol** [comment]
Log file is located at %LOCALAPPDATA%\RaceControl.

However, the next release will have a new video player which will probably fix this issue.

**Comment by JC38818** [comment]
Hi Rob,

I resolved the issue. It was just that the default location that it was
trying to save to was read only... when I changed it to the videos folder,
it worked perfectly!

Thanks so much for writing this software. It’s a great app!

Best regards,
Phil
