### ISSUE TITLE
Looking for a certain section of code

### ISSUE THREAD

**Issue by bootsie123** [robvdpol/RaceControl#96]
Hi! I'm trying to make my own edits to the program and was wondering if I could get help looking for a piece of code. When a request is made to get a list of events for a particular season, in this case, the 2021 season, the API returns a list of all of the events whether or not they already happened (only in the case of the 2021 season). However, in the UI, it only shows a list of events that have or are currently happening.

I assume it's filtering this list somewhere and can't seem to find it. Any ideas on where it might be? Or have I gotten something wrong? Thanks!

**Comment by robvdpol** [comment]
That's done in the mainwindow xaml, look for usage of the DatePassedConverter.

**Comment by bootsie123** [comment]
ah, thanks! Looks like I missed it the first time around
